#pragma once
// Французский перевод прошивки. Правила (проверяет tools/smoke_i18n_firmware.py):
//  - по одной строке #define LANG_<KEY> "text" на каждый ключ TR(KEY, "...") из кода;
//    полнота: нет ключа - ошибка компиляции, лишних ключей быть не должно;
//  - в переводе нет кириллицы;
//  - набор printf-спецификаторов (%d %s %.1f ...) совпадает с русским по порядку;
//  - длина перевода в байтах UTF-8 не больше русской (буферы рассчитаны на русский);
//  - секции ключей идут по файлам с комментарием // <имя файла>.
#define SAMOVAR_LANG_NAME "Français"

// nbk.h
#define LANG_NBK_WASH_PROCESSED "Moût traité "
#define LANG_NBK_UNIT_L_SP " l "
#define LANG_NBK_CFG_COLUMN_INERTIA "inertie de la colonne In"
#define LANG_NBK_CFG_DELTA_T "correction dT"
#define LANG_NBK_CFG_TANK_TEMP "température bouilleur Tn"
#define LANG_NBK_CFG_FLOOD_PRESSURE "pression d’engorgement PS"
#define LANG_NBK_CFG_POWER_STEP "pas de puissance dM"
#define LANG_NBK_CFG_FEED_STEP "pas de débit dP"
#define LANG_NBK_CFG_STEAM_LIMIT "limite de température vapeur Tp"
#define LANG_NBK_CFG_MAINS_INPUT_INVALID "tension secteur (saisie non reconnue)"
#define LANG_NBK_CFG_HEATER_INPUT_INVALID "résistance (saisie non reconnue)"
#define LANG_NBK_CFG_MAINS_RANGE "tension secteur hors plage"
#define LANG_NBK_CFG_HEATER_RANGE "résistance hors plage"
#define LANG_NBK_CEILING_LOWERED_TO "Plafond de pression abaissé à "
#define LANG_NBK_MM_FLOODING_AT " mm (engorgement à "
#define LANG_NBK_MM_CLOSE " mm)"
#define LANG_NBK_SRC_FLOOD_SENSOR "DE"
#define LANG_NBK_SRC_NO_PRESSURE_DATA "pas de données PS"
#define LANG_NBK_SRC_PRESSURE_SENSOR "PS"
#define LANG_NBK_HEATUP_ACTUATORS_NOT_CONFIRMED "La montée en puissance CMC n’a pas confirmé les commandes des actionneurs."
#define LANG_NBK_SAFE_WAIT "Attente sécurisée CMC."
#define LANG_NBK_ACTUATOR_CONFIRM_TIMEOUT "Délai de confirmation des actionneurs CMC dépassé. Attente sécurisée."
#define LANG_NBK_ACTUATOR_CMD_HEATING_OFF "Commande des actionneurs CMC rejetée, chauffe coupée."
#define LANG_NBK_REGULATOR_NOT_CONFIRMED "Le régulateur n’a pas confirmé la commande CMC. Attente sécurisée."
#define LANG_NBK_PUMP_NOT_CONFIRMED "La pompe CMC n’a pas confirmé la commande. Chauffe coupée."
#define LANG_NBK_WORK_RESUMED "Travail CMC repris."
#define LANG_NBK_WARMUP_POWER_FEED_SET "Puissance et débit de préchauffage CMC réglés."
#define LANG_NBK_MODE_NAME "CMC"
#define LANG_NBK_SENSOR_VAPOR "vapeur"
#define LANG_NBK_SENSOR_BOILER "bouill."
#define LANG_NBK_RESTART_IMPOSSIBLE "Redémarrage CMC impossible : "
#define LANG_NBK_HEATING_NOT_OFF_YET "chauffe pas encore coupée"
#define LANG_NBK_PUMP_STOP_NOT_CONFIRMED "la pompe n’a pas confirmé l’arrêt"
#define LANG_NBK_SESSION_CONFIG_NOT_CAPTURED "Configuration de session CMC non enregistrée."
#define LANG_NBK_PROGRAM_LINE_OUT_OF_RANGE "Erreur de programme CMC : numéro de ligne hors plage"
#define LANG_NBK_PROGRAM_LINE_NOT_SET "Erreur de programme CMC : ligne non définie"
#define LANG_NBK_WARMUP_TOO_HIGH_PREFIX "Valeurs trop élevées au préchauffage : "
#define LANG_NBK_AND_OR_FEED_PROGRAM_STOP " et/ou débit ! Arrêt du programme."
#define LANG_NBK_AFTER_FLOOD_REDUCE_REJECTED "Réduction des actionneurs CMC après engorgement refusée."
#define LANG_NBK_FLOODING_BY "Engorgement par "
#define LANG_NBK_FEED_THIRD_POWER_HALF ". Débit 1/3, puissance 1/2."
#define LANG_NBK_BEFORE_OPT_SETUP_PREFIX "Avant même l’Optimisation, les valeurs du Réglage de "
#define LANG_NBK_AND_FEED_TOO_HIGH_STOP " et le débit sont trop élevés. Arrêt."
#define LANG_NBK_MANUAL_WORK_WAIT_PREFIX "En attente du passage manuel au Travail, les valeurs de "
#define LANG_NBK_OPT_INITIAL_REJECTED "Paramètres initiaux d’Optimisation CMC refusés."
#define LANG_NBK_OPT_ACCEPTED_FROM "Optimisation acceptée depuis : "
#define LANG_NBK_UNIT_LPH_SP " l/h "
#define LANG_NBK_SET_PARAMS_PREFIX "Les valeurs de "
#define LANG_NBK_AND_SPEED_TOO_HIGH_OPT_STOP " et la Vitesse sont trop élevées, optimisation impossible. Arrêt."
#define LANG_NBK_TN_REFINED_BY_SENSOR "Tn de référence affinée par le capteur de vinasse : "
#define LANG_NBK_OPT_NO_FLOOD_SENSOR "Optimisation impossible : pas de capteur d’engorgement. Réglez à la main les paramètres voulus dans le programme de l’étape Travail et appuyez sur Programme suivant. Dans 10 minutes, le processus passera en attente sécurisée (chauffe et débit coupés)."
#define LANG_NBK_C_IN_SETTINGS " °C (dans les paramètres "
#define LANG_NBK_FEED_LIMIT_REACHED "Débit limite atteint ("
#define LANG_NBK_LPH_RESULT_COLON " l/h). Résultat : "
#define LANG_NBK_OPT_TB_GE_TN "Optimisation : Tb >= Tn ("
#define LANG_NBK_INCREASING_FEED_ITER "), on augmente le débit. Itération "
#define LANG_NBK_POWER_LIMIT_REACHED "Puissance limite atteinte. ("
#define LANG_NBK_W_RESULT_COLON " W). Résultat : "
#define LANG_NBK_UNIT_LPH_DOT " l/h."
#define LANG_NBK_OPT_NOT_FOUND_TB_TN "Optimum introuvable : Tb n’a pas atteint Tn ("
#define LANG_NBK_NO_ITERATION_CHECK_TB ") à aucune itération. Vérifiez le capteur Tb."
#define LANG_NBK_OPT_TP_LT_TPMIN "Optimisation : Tp < Tp min("
#define LANG_NBK_INCREASING "), on augmente "
#define LANG_NBK_ITERATION_SP ". Itération "
#define LANG_NBK_OPT_TB_LT_TN "Optimisation : Tb < Tn("
#define LANG_NBK_OPT_CORRECTION_REJECTED "Correction d’Optimisation CMC refusée."
#define LANG_NBK_ITER_LIMIT_RESULT "Limite d’itérations atteinte. Résultat : "
#define LANG_NBK_UNIT_LPH " l/h"
#define LANG_NBK_TEMP_REDUCE_FEED_HEATING "Baisse temporaire du débit et de la chauffe."
#define LANG_NBK_WORK_WASH_SPILL "Travail : débordement du moût (Tb "
#define LANG_NBK_FEED_REDUCED_BY "), débit réduit de "
#define LANG_NBK_TO_COLON ", à : "
#define LANG_NBK_WORK_TB_LT_TN_DT "Travail : Tb < Tn-dT ("
#define LANG_NBK_REDUCING_FEED_BY "), on réduit le débit de "
#define LANG_NBK_WORK_TP_BELOW_LIMIT "Travail : Tp sous la limite ("
#define LANG_NBK_WORK_PRESSURE "Travail : pression "
#define LANG_NBK_GE_CEILING " ≥ plafond "
#define LANG_NBK_MM_REDUCING_FEED_BY " mm, on réduit le débit de "
#define LANG_NBK_WORK_TB_GT_TN_DT "Travail : Tb > Tn+dT ("
#define LANG_NBK_INCREASING_FEED_BY "), on augmente le débit de "
#define LANG_NBK_WORK_CORRECTION_REJECTED "Correction du Travail CMC refusée."
#define LANG_NBK_REPEAT_FLOODING_BY "Nouvel engorgement par "
#define LANG_NBK_DURING_PAUSE_EXTENDED " pendant la pause. Pause prolongée, puissance divisée par deux."
#define LANG_NBK_REPEAT_POWER_REDUCE_REJECTED "Nouvelle réduction de puissance CMC refusée."
#define LANG_NBK_WORK_RESUME_REJECTED "Reprise du Travail CMC refusée."
#define LANG_NBK_WORK_RESUME_AFTER_FLOOD "Travail : reprise après engorgement, paramètres corrigés : "
#define LANG_NBK_WORK_CONTINUE_AFTER_PAUSE "Travail : le cycle continue après la pause."
#define LANG_NBK_RESUME_IMPOSSIBLE_EMERGENCY "Reprise du Travail CMC impossible : urgence verrouillée."
#define LANG_NBK_RESUME_IMPOSSIBLE_NO_SNAPSHOT "Reprise du Travail CMC impossible : pas d’instantané de configuration de session."
#define LANG_NBK_RESUME_REJECTED_CMD_BUSY "Reprise du Travail CMC refusée : la commande précédente des actionneurs est encore en cours."
#define LANG_NBK_WORK_WAITS_HEATING_OFF "Le Travail CMC attend la fin de la coupure de chauffe."
#define LANG_NBK_RESUME_UNAVAILABLE_PUMP_STOP "Reprise du Travail CMC indisponible : arrêt de la pompe non confirmé."
#define LANG_NBK_HEATING_NOT_ON_RESUME "Chauffe CMC non activée lors de la reprise du Travail."
#define LANG_NBK_RESUME_PARAMS_REJECTED "Reprise du Travail CMC : paramètres refusés par les actionneurs."
#define LANG_NBK_WORK_RESUMED_M "Travail CMC repris : M="
#define LANG_NBK_COMMA_P ", P="
#define LANG_NBK_START_REJECTED_NO_REGULATOR "Démarrage CMC refusé : régulateur de puissance indisponible dans cette version."
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_NO_REGULATOR "Arrêt de la pompe CMC non confirmé dans la configuration indisponible."
#define LANG_NBK_LINE_SWITCH_HEATING_STARTING "Changement de ligne CMC refusé : le démarrage de la chauffe n’est pas terminé"
#define LANG_NBK_PROGRAM_NOT_SET "Programme CMC non défini"
#define LANG_NBK_GOTO_WORK_NO_SNAPSHOT "Passage au Travail CMC refusé : pas d’instantané de configuration de session."
#define LANG_NBK_AUTO_WORK_IMPOSSIBLE "Entrée auto en Travail CMC impossible : chauffe coupée ou optimum introuvable."
#define LANG_NBK_AUTO_WORK_PARAMS_REJECTED "Paramètres d’entrée auto en Travail refusés par les actionneurs CMC."
#define LANG_NBK_OPT_FINISHED "Optimisation terminée"
#define LANG_NBK_BY_PRESSURE " par pression ("
#define LANG_NBK_COLON_MO ": Mo="
#define LANG_NBK_COMMA_PO ", Po="
#define LANG_NBK_LPH_PAUSE " l/h. Pause "
#define LANG_NBK_S_THEN_WORK " s, puis Travail."
#define LANG_NBK_AUTO_WORK_FORBIDDEN "Le passage automatique au Travail CMC est interdit. Réglez Power/Speed de la ligne W et appuyez sur Programme suivant."
#define LANG_NBK_LINE_W_NEEDS_NONZERO "La ligne W exige Power et Speed non nuls, ou des valeurs optimales enregistrées."
#define LANG_NBK_WORK_UNAVAILABLE_PUMP_STOP "Travail CMC indisponible : arrêt de la pompe non confirmé."
#define LANG_NBK_HEATING_NOT_ON_EXPLICIT_WORK "Chauffe CMC non activée après la commande explicite de passage au Travail."
#define LANG_NBK_HEATING_OFF_WORK_REJECTED "Chauffe CMC coupée. Passage au Travail refusé."
#define LANG_NBK_LINE_W_PARAMS_REJECTED "Paramètres de la ligne W refusés par les actionneurs CMC."
#define LANG_NBK_EXPLICIT_WORK_ACCEPTED_M "Passage explicite au Travail CMC accepté : M="
#define LANG_NBK_W_COMMA_P " W, P="
#define LANG_NBK_SAFE_WAIT_STOPPED_BY_OPERATOR "Attente sécurisée arrêtée par l’opérateur."
#define LANG_NBK_SAFE_WAIT_SESSION_ENDED "Attente sécurisée CMC : session terminée sur ordre de l’opérateur."
#define LANG_NBK_START_HEATING_OFF_PENDING "Coupure de chauffe pas encore terminée. Démarrage CMC annulé."
#define LANG_NBK_HEATING_OFF_GOTO_LINE "Chauffe CMC coupée. Passage à la ligne n°"
#define LANG_NBK_CANCELLED_DOT " annulé."
#define LANG_NBK_START_REJECTED_BAD_SETTING "Démarrage CMC refusé : réglage incorrect - "
#define LANG_NBK_START_LOG_FILE_ERROR "Erreur de création du fichier journal. Démarrage CMC annulé."
#define LANG_NBK_PROGRAM_STARTED_WARMUP "Démarrage du programme CMC. Préchauffage"
#define LANG_NBK_NO_FLOOD_SENSORS_WARNING "Attention : aucun capteur d’engorgement (DE désactivé, PS ne répond pas). La protection contre l’engorgement ne fonctionne pas."
#define LANG_NBK_START_SESSION_BUSY "Description de session occupée. Démarrage CMC annulé."
#define LANG_NBK_GOTO_LINE "Passage à la ligne n°"
#define LANG_NBK_TYPE_SP ". Type : "
#define LANG_NBK_START_HEATING_NOT_ON "Chauffe CMC non activée. Démarrage annulé."
#define LANG_NBK_HEATUP_TRANSITION_STARTED "Transition de montée CMC lancée."
#define LANG_NBK_MANUAL_NEEDS_NONZERO "Le réglage manuel CMC exige une puissance et un débit non nuls."
#define LANG_NBK_MANUAL_PARAMS_REJECTED "Paramètres du réglage manuel CMC refusés."
#define LANG_NBK_PROGRAM_LINE_EMPTY "Erreur de programme CMC : ligne de programme vide"
#define LANG_NBK_STEAM_98_WASH_OUT "Température vapeur supérieure à 98°C pendant 60 secondes. Plus de moût. Programme CMC terminé."
#define LANG_NBK_EMERGENCY_WASH_OUT "Arrêt d’urgence ! Impossible de terminer normalement le programme CMC (plus de moût)"
#define LANG_NBK_TP_ROSE_BY "Tp a augmenté de "
#define LANG_NBK_C_RELATIVE_TO_MIN " °C par rapport au minimum "
#define LANG_NBK_C_WASH_ENDING " °C : le moût s’épuise. Programme CMC terminé."
#define LANG_NBK_EMERGENCY_TP_RISE "Arrêt d’urgence ! Impossible de terminer normalement le programme CMC (hausse de Tp vapeur)"
#define LANG_NBK_STEAM_OVER_LIMIT_MANUAL "T vapeur au-dessus de la limite pendant 60 secondes en réglage manuel. Risque de marche à sec du générateur de vapeur. Programme CMC terminé."
#define LANG_NBK_EMERGENCY_STEAM_OVERHEAT_MANUAL "Arrêt d’urgence ! Impossible de terminer normalement le programme CMC (surchauffe vapeur en réglage manuel)"
#define LANG_NBK_INSUFFICIENT_COOLING "Refroidissement insuffisant ! Arrêt."
#define LANG_NBK_PRESSURE_SENSOR_FAILED "Panne du capteur de pression ! Aucune mesure depuis plus de 60 secondes. Arrêt."
#define LANG_NBK_LOG_BUSY_CLOSE_SKIPPED "Fichier journal occupé : fermeture non effectuée"
#define LANG_NBK_HEATUP_TRANSITION_ABORTED "Transition de montée CMC interrompue."
#define LANG_NBK_HEATING_START_ABORTED "Démarrage de la chauffe CMC interrompu : condition de démarrage violée, processus arrêté."
#define LANG_NBK_HEATUP_NEEDS_CONFIRMED_FEED "La montée en température CMC exige un débit non nul confirmé."
#define LANG_NBK_RUN_FINISHED "Travail CMC terminé"
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_ON_FINISH "Arrêt de la pompe CMC non confirmé à la fin."
#define LANG_NBK_AVG_SESSION_RATE "avec un débit moyen de session de "
#define LANG_NBK_AND_AVG_FEED_RATE "et un débit d’alimentation moyen de "
#define LANG_NBK_OVER_COLON "en : "
#define LANG_NBK_UNIT_H_DOT " h."
#define LANG_NBK_RUN_FINISHED_DOT "Travail CMC terminé."
#define LANG_NBK_RUN_ABORTED_EMERGENCY "Travail CMC interrompu par une urgence."
#define LANG_NBK_FLOOD_FEED_REDUCE_UNCONFIRMED "Réduction du débit CMC lors de l’engorgement non confirmée."
#define LANG_NBK_EMERGENCY_FLOODING "Arrêt d’urgence ! Impossible de terminer normalement le programme CMC (engorgement)"
#define LANG_NBK_FLOOD_ACTUATOR_REDUCE_REJECTED "Réduction des actionneurs CMC lors de l’engorgement refusée."
// BK.h
#define LANG_BK_WORK_POWER_APPLIED "Puissance de travail CM appliquée."
#define LANG_BK_PROGRAMS_DONE_CONTINUE "Programmes terminés, le soutirage continue"
#define LANG_BK_LUA_LINE_SCRIPT_NOT_STARTED "Erreur Lua : script de ligne non lancé"
#define LANG_BK_PROGRAM_L_NEEDS_LUA "Erreur de programme : le type L exige USE_LUA"
#define LANG_BK_GOTO_PROGRAM_LINE "Passage à la ligne de programme n°"
#define LANG_BK_DEPHLEGMATOR_WATER_MANUAL "Eau du déflegmateur : commande manuelle"
#define LANG_BK_PUMP_CONTROL_UNSUPPORTED "La commande de pompe n’est pas prise en charge par votre matériel"
#define LANG_BK_MODE_NAME "CM"
#define LANG_BK_SENSOR_BOILER "bouill."
#define LANG_BK_SENSOR_VAPOR "vapeur"
#define LANG_BK_START_NO_TANK_SENSOR "CM non lancée : capteur du bouilleur non assigné ou muet"
#define LANG_BK_START_NEEDS_STEAM_SENSOR "CM non lancée : le programme exige un capteur de vapeur"
#define LANG_BK_START_LOG_FILE_ERROR "Erreur de création du fichier journal. Démarrage CM annulé."
#define LANG_BK_START_SESSION_BUSY "Description de session occupée. Démarrage CM annulé."
#define LANG_BK_HEATING_ON "Chauffe de la colonne à moût activée"
#define LANG_BK_WAIT_WORK_POWER "Attente de la puissance de travail CM."
#define LANG_BK_LUA_TIMEOUT "Lua n’a pas terminé l’opération avant le délai"
#define LANG_BK_LUA_FAILED "Lua s’est terminée avec une erreur"
#define LANG_BK_RUN_FINISHED_DOT "Travail CM terminé."
#define LANG_BK_RUN_FINISHED "Travail de la colonne à moût terminé"
// distiller.h
#define LANG_DIST_NO_ALCOHOL_LEFT "Plus d’alcool dans le bouilleur"
#define LANG_DIST_ABV_UNAVAILABLE "Degré indisponible : la ligne en pourcentage continue"
#define LANG_DIST_MODE_NAME "Distillation"
#define LANG_DIST_SENSOR_BOILER "bouill."
#define LANG_DIST_START_NO_TANK_SENSOR "Distillation non lancée : capteur du bouilleur non assigné ou muet. Ouvrez les paramètres et vérifiez l’affectation du capteur du bouilleur."
#define LANG_DIST_START_LOG_FILE_ERROR "Erreur de création du fichier journal. Démarrage de la distillation annulé."
#define LANG_DIST_START_SESSION_BUSY "Description de session occupée. Démarrage de la distillation annulé."
#define LANG_DIST_HEATING_ON "Chauffe du distillateur activée"
#define LANG_DIST_LUA_TIMEOUT "Lua n’a pas terminé l’opération avant le délai"
#define LANG_DIST_LUA_FAILED "Lua s’est terminée avec une erreur"
#define LANG_DIST_FINISHED "Distillation terminée."
#define LANG_DIST_TOTAL_TIME " Durée totale : "
#define LANG_DIST_UNIT_MIN " min."
#define LANG_DIST_PROGRAMS_DONE_CONTINUE "Programmes terminés, le soutirage continue"
#define LANG_DIST_LUA_LINE_SCRIPT_NOT_STARTED "Erreur Lua : script de ligne non lancé"
#define LANG_DIST_PROGRAM_L_NEEDS_LUA "Erreur de programme : le type L exige USE_LUA"
#define LANG_DIST_GOTO_PROGRAM_LINE "Passage à la ligne de programme n°"

// logic.h
#define LANG_LOGIC_PRG_NUM "Lgn n°"
#define LANG_LOGIC_PROG_LINE_START "Programme : début de la ligne  n°"
#define LANG_LOGIC_PROG_LINE_START_LUA "Programme : début de la ligne n°"
#define LANG_LOGIC_TAKEOFF_TO_CONTAINER ", soutirage vers le récipient "
#define LANG_LOGIC_I2C_PUMP_CMD_HEAD "Pompe I2C sur PC : commande «"
#define LANG_LOGIC_I2C_PUMP_CMD_TAIL "» non confirmée après 10 envois."
#define LANG_LOGIC_LUA_OP_DONE "Opération Lua terminée"
#define LANG_LOGIC_LUA_OP_NOT_DONE "Opération Lua non terminée"
#define LANG_LOGIC_LUA_TIMEOUT "Lua n’a pas terminé l’opération avant le délai"
#define LANG_LOGIC_LUA_OP_FAILED "L’opération Lua s’est terminée avec une erreur"
#define LANG_LOGIC_LUA_ERROR "Lua s’est terminée avec une erreur"
#define LANG_LOGIC_AUTOPAUSE_BUSY_SKIP "Type de pause auto occupé. Contrôle du soutirage ignoré."
#define LANG_LOGIC_PAUSE_SET_FAIL_HEAD "Impossible de définir la pause sur "
#define LANG_LOGIC_PAUSE_TYPE_BUSY_TAIL ": type de pause occupé."
#define LANG_LOGIC_AUTOPAUSE_TAIL "Pause automatique du soutirage"
#define LANG_LOGIC_PAUSE_BY "Pause sur "
#define LANG_LOGIC_RESUME_AFTER_AUTOPAUSE "Reprise du soutirage après la pause automatique"
#define LANG_LOGIC_TAKEOFF_RESUMED "Soutirage repris"
#define LANG_LOGIC_LABEL_T_STEAM "T vapeur"
#define LANG_LOGIC_LABEL_T_PIPE "T colonne"
#define LANG_LOGIC_DETECTOR_RESUME "Détecteur : reprise du soutirage après la pause"
#define LANG_LOGIC_PUMP_CAL_BAD_STEPS "Erreur d’étalonnage de la pompe : nombre de pas incorrect"
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_HEAD "Étalonnage de la pompe non enregistré : "
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_TAIL ". Résultat perdu, recommencez l’étalonnage."
#define LANG_LOGIC_ACTION_PAUSE "pause"
#define LANG_LOGIC_ACTION_RESUME "reprise"
#define LANG_LOGIC_MANUAL_PAUSE_TAKEOFF "Pause manuelle du soutirage"
#define LANG_LOGIC_MANUAL_PAUSE_MASH "Pause manuelle de l’empâtage"
#define LANG_LOGIC_MASH_PAUSE_NEXT_STEP "La pause sera appliquée à la prochaine étape d’empâtage."
#define LANG_LOGIC_MASH_PAUSED "Empâtage mis en pause."
#define LANG_LOGIC_AUTOPAUSE_RESET_FAIL "Impossible de réinitialiser le type de pause auto."
#define LANG_LOGIC_MASH_RESUMED_TAIL "Empâtage repris"
#define LANG_LOGIC_MASH_RESUMED_MSG "Empâtage repris."
#define LANG_LOGIC_DIST_MODE_SEP "; Mode distillation"
#define LANG_LOGIC_DIST_PROGRAMS_DONE "Programmes exécutés, soutirage jusqu’à T bouilleur "
#define LANG_LOGIC_DIST_MODE_DEG "° ; Mode distillation"
#define LANG_LOGIC_DIST_ROW_LEFT "; Ligne : reste "
#define LANG_LOGIC_OF_APPROX " sur ~"
#define LANG_LOGIC_UNIT_MIN " min"
#define LANG_LOGIC_DIST_ROW_FORECAST_WAIT "; Prévision de la ligne : attente de données"
#define LANG_LOGIC_DIST_PROCESS_LEFT "; Processus jusqu’à DistTemp, reste :"
#define LANG_LOGIC_DIST_TOTAL "; Total :"
#define LANG_LOGIC_DIST_PROCESS_FORECAST_WAIT "; Prévision du processus : attente d’ébullition/données"
#define LANG_LOGIC_BK_MODE "Mode colonne à moût"
#define LANG_LOGIC_NBK_STAGE_H "Préchauffage"
#define LANG_LOGIC_NBK_STAGE_S "Réglage"
#define LANG_LOGIC_NBK_STAGE_O "Optimisation"
#define LANG_LOGIC_NBK_STAGE_W "Travail"
#define LANG_LOGIC_BEER_ON_PAUSE "En pause ; "
#define LANG_LOGIC_BEER_WAIT_SKIP_COOL "Attente de confirmation du saut du refroidissement ; "
#define LANG_LOGIC_BEER_HEAT_TO_MALT "Chauffe jusqu’à la température d’ajout du malt"
#define LANG_LOGIC_CUR_T "; T actuelle : "
#define LANG_LOGIC_BEER_WAIT_MALT "Attente de l’ajout du malt"
#define LANG_LOGIC_BEER_PAUSE "Pause "
#define LANG_LOGIC_BEER_DEG_HEATING "° ; Chauffe"
#define LANG_LOGIC_BEER_COOL_TO "Refroidissement à "
#define LANG_LOGIC_BEER_WAIT_PRESS_NEXT "Attente. Appuyez sur ’Programme suivant’ ; "
#define LANG_LOGIC_BEER_AUTOCAL "Auto-étalonnage. Une fois terminé, "
#define LANG_LOGIC_BEER_AUTOCAL_POWER_OFF "l’alimentation sera coupée"
#define LANG_LOGIC_BEER_AUTOCAL_NEXT_LINE "passage à la ligne suivante"
#define LANG_LOGIC_BEER_BOIL_HEATING "Ébullition - chauffe"
#define LANG_LOGIC_BEER_BOIL "Ébullition "
#define LANG_LOGIC_BEER_FERM_HOLD "Fermentation ; Maintien T="
#define LANG_LOGIC_CUR_SHORT "; Act : "
#define LANG_LOGIC_PAREN_HEATING " (Chauffe)"
#define LANG_LOGIC_PAREN_THERMOSTAT " (Thermostat)"
#define LANG_LOGIC_BEER_FERM_STOPPED "Fermentation (arrêtée)"
#define LANG_LOGIC_RUNNING_LUA_SCRIPT "Exécution du script Lua"
#define LANG_LOGIC_PROGRESS "; Progression : "
#define LANG_LOGIC_STATUS_OFF "Arrêt"
#define LANG_LOGIC_PAREN_ERROR "(erreur)"
#define LANG_LOGIC_AUTOPAUSE_READ_FAIL "Impossible de lire le type de pause auto."
#define LANG_LOGIC_PAUSE_SP " pause "
#define LANG_LOGIC_RESUME_IN ". Reprise dans "
#define LANG_LOGIC_UNIT_SEC " s."
#define LANG_LOGIC_PROGRAM_DONE_STATUS "Exécution du programme terminée"
#define LANG_LOGIC_STATUS_CALIBRATION "Étalonnage"
#define LANG_LOGIC_STATUS_PAUSE "Pause"
#define LANG_LOGIC_SUVID_HOLD "Sous-vide ; Maintien T="
#define LANG_LOGIC_DEG_CUR "° ; Act : "
#define LANG_LOGIC_SUVID_HOLD_TIME "; Maintien : "
#define LANG_LOGIC_COLUMN_HEATUP "Montée de la colonne"
#define LANG_LOGIC_HEATUP_DONE_STAB "Montée en température terminée. Stabilisation/reflux total"
#define LANG_LOGIC_STAB_DONE "Stabilisation terminée/reflux total"
#define LANG_LOGIC_LEFT "; Reste :"
#define LANG_LOGIC_BODY_T_STEAM ";T cœur vapeur :"
#define LANG_LOGIC_BODY_T_PIPE ";T cœur colonne :"
#define LANG_LOGIC_PUMP_NOT_CALIBRATED "La pompe n’est pas étalonnée (pas par ml = 0). Démarrage de la rectification impossible."
#define LANG_LOGIC_RECT_PROG_LINE_UNSET "Erreur du programme de rectification : ligne non définie"
#define LANG_LOGIC_RECT_PROG_FIRST_LINE "Erreur de programme : la première ligne doit définir une puissance/tension absolue. Démarrage de la rectification impossible."
#define LANG_LOGIC_PROG_ERR_LINE "Erreur de programme : ligne "
#define LANG_LOGIC_PROG_LINE_NEVER_ENDS " ne se terminera jamais (volume et température non définis)"
#define LANG_LOGIC_ACTION_PROGRAM_END "fin du programme"
#define LANG_LOGIC_PROGRAM_FINISHED "Programme terminé"
#define LANG_LOGIC_LOG_BUSY_CLOSE_SKIPPED "Fichier journal occupé : fermeture ignorée"
#define LANG_LOGIC_PROGRAM_DONE_MSG "Exécution du programme terminée."
#define LANG_LOGIC_LUA_LINE_SCRIPT_NOT_STARTED "Erreur Lua : script de ligne non lancé"
#define LANG_LOGIC_NEXT_LINE "Passage à la ligne suivante"
#define LANG_LOGIC_LUA_OP_STARTED "Opération Lua lancée"
#define LANG_LOGIC_PROG_TYPE_L_NEEDS_LUA "Erreur de programme : le type L exige USE_LUA"
#define LANG_LOGIC_ACTION_LINE_START "début de ligne "
#define LANG_LOGIC_PROG_LINE_SPEED "Programme : débit de la ligne n°"
#define LANG_LOGIC_SPEED_OVER_PUMP_LIMIT " l/h) dépasse la limite de la pompe, limité à "
#define LANG_LOGIC_UNIT_LPH_DOT " l/h."
#define LANG_LOGIC_COMMA_PAUSE ", pause "
#define LANG_LOGIC_PROGRAM_PAUSE "Pause du programme"
#define LANG_LOGIC_NEW_BODY_T_STEAM "Nouvelles T du cœur : vapeur = "
#define LANG_LOGIC_COMMA_PIPE_EQ ", colonne = "
#define LANG_LOGIC_BODY_T_SET_FAIL "Impossible de définir la T du cœur."
#define LANG_LOGIC_BOILING_STARTED_ABV "L’ébullition a commencé dans le bouilleur ! Degré "
#define LANG_LOGIC_BOILING_STARTED "Ébullition dans le bouilleur !"
#define LANG_LOGIC_WETTING_START "Début du mouillage du garnissage de la colonne. Surveillez le niveau de flegme !"
#define LANG_LOGIC_WETTING_OK "Garnissage de la colonne mouillé avec succès !"
#define LANG_LOGIC_WETTING_TIMEOUT "Durée maximale de mouillage dépassée. Échec du mouillage - arrêtez le processus manuellement."
#define LANG_LOGIC_WETTING_VOLT_RAMP_START "Début de la baisse progressive de tension"
#define LANG_LOGIC_WETTING_VOLT_TO "Baisse de la tension à "
#define LANG_LOGIC_WETTING_MIN_VOLT "Tension minimale atteinte : "
#define LANG_LOGIC_WETTING_WAIT_SENSOR ". Attente du déclenchement du capteur."
#define LANG_LOGIC_WETTING_MIN_VOLT_TIMEOUT "Délai d’attente à la tension minimale dépassé. Échec du mouillage - arrêtez le processus manuellement."
#define LANG_LOGIC_WETTING_NO_SENSOR "Capteur de niveau de flegme non installé, mouillage du garnissage impossible"
// alarm.h
#define LANG_ALARM_SENSORS_UNASSIGNED "Capteurs non assignés. Ouvrez les paramètres et assignez les capteurs de vapeur, d’eau et du bouilleur."
#define LANG_ALARM_EMERGENCY_STOP "Arrêt d’urgence !"
#define LANG_ALARM_COOLING_HOLD_3MIN "Le refroidissement tournera encore 3 minutes puis se fermera."
#define LANG_ALARM_EMERGENCY_STOP_TAIL "Arrêt d’urgence"
#define LANG_ALARM_EMERGENCY_STOP_SP "Arrêt d’urgence ! "
#define LANG_ALARM_NO_SENSOR_DATA ": pas de données du capteur "
#define LANG_ALARM_RECT_SENSORS_UNASSIGNED "Arrêt d’urgence ! Rectification : capteurs non assignés"
#define LANG_ALARM_MODE_RECT "Rectification"
#define LANG_ALARM_SENSOR_STEAM "vapeur"
#define LANG_ALARM_SENSOR_TANK "bouill."
#define LANG_ALARM_FLOOD_SENSOR "Capteur d’engorgement déclenché !"
#define LANG_ALARM_REDUCING_FROM " on réduit de "
#define LANG_ALARM_RAISING_TO " on monte à "
#define LANG_ALARM_OVERTEMP_STEAM " Vapeur"
#define LANG_ALARM_OVERTEMP_WATER " Eau"
#define LANG_ALARM_OVERTEMP_ACP " TCA"
#define LANG_ALARM_TANK_LIMIT_FINISHED "Limite de température maximale du bouilleur. Programme terminé."
#define LANG_ALARM_TANK_LIMIT_FINISH_FAIL "Arrêt d’urgence ! Impossible de terminer normalement le programme sur la température du bouilleur"
#define LANG_ALARM_MAX_TEMP_EXCEEDED "Arrêt d’urgence ! Température maximale dépassée"
#define LANG_ALARM_WATER_CRIT_SUPPLY_ERR "Température d’eau critique ! Erreur d’alimentation en eau. "
#define LANG_ALARM_HEATUP_DONE_STAB "Montée en température terminée. Stabilisation/reflux total."
#define LANG_ALARM_ABV "Degré "
#define LANG_ALARM_STAB_DONE_STABLE "Stabilisation terminée, la colonne fonctionne de façon stable."
// mode_switch.h
#define LANG_MSW_I2C_MIXER_STOP "L’agitateur I2C n’a pas confirmé l’arrêt"
#define LANG_MSW_I2C_PUMP_STOP "La pompe I2C n’a pas confirmé l’arrêt"
#define LANG_MSW_STEPPER_STOP "le moteur pas à pas ne s’est pas arrêté"
#define LANG_MSW_VALVE_CLOSE "la vanne ne s’est pas fermée"
#define LANG_MSW_MIXER_STOP "l’agitateur ne s’est pas arrêté"
#define LANG_MSW_COOLING_PUMP_STOP "la pompe de refroidissement ne s’est pas arrêtée"
#define LANG_MSW_PUMP_CAL_NOT_DONE "étalonnage de la pompe non terminé"
#define LANG_MSW_HEATING_NOT_CONFIRMED "chauffe non confirmée"
#define LANG_MSW_ACTUATOR_NOT_CONFIRMED "actionneur non confirmé"
#define LANG_MSW_FORCE_COMPLETED "Changement de mode forcé : "
#define LANG_MSW_LUA_NOT_CONFIRMED "Lua non confirmé"
#define LANG_MSW_QUEUE_NOT_CONFIRMED "file d’attente non confirmée"
#define LANG_MSW_PENDING_CMDS_CANCELLED "Commandes de contrôle en attente annulées par le changement de mode"
#define LANG_MSW_READINESS_NOT_CONFIRMED "disponibilité non confirmée"
#define LANG_MSW_LOG_NOT_CONFIRMED "journal non confirmé"
#define LANG_MSW_POWER_TRANSITION_NOT_CONFIRMED "transition de puissance non confirmée"
#define LANG_MSW_NBK_TRANSITION_NOT_CONFIRMED "transition CMC non confirmée"
#define LANG_MSW_HEATING_START_NOT_CONFIRMED "démarrage de la chauffe non confirmé"
#define LANG_MSW_SELF_TEST_NOT_CONFIRMED "autotest non confirmé"
#define LANG_MSW_OWNER_NOT_CONFIRMED "propriétaire du mode non confirmé"
#define LANG_MSW_LUA_NOT_RELOADED "script Lua non relu"
#define LANG_MSW_PROFILE_NOT_SAVED "profil non enregistré"
// mode_common.h
#define LANG_MCOM_SENSOR_WATER "eau"
#define LANG_MCOM_SENSOR_ACP "TCA"
#define LANG_MCOM_WATER_SUPPLY_STOPPED "Arrêt d’urgence ! Alimentation en eau interrompue."
#define LANG_MCOM_OVERTEMP_WATER " Eau"
#define LANG_MCOM_OVERTEMP_ACP " TCA"
#define LANG_MCOM_MAX_TEMP_EXCEEDED "Arrêt d’urgence ! Température maximale dépassée"
#define LANG_MCOM_WATER_HIGH_HEAD "Température d’eau élevée : "
#define LANG_MCOM_WATER_WARN_THRESHOLD "°C (seuil d’avertissement "
#define LANG_MCOM_CHECK_COOLING_DOT "°C). Vérifiez le refroidissement."
#define LANG_MCOM_ACP_HIGH_HEAD "Température TCA élevée : "
#define LANG_MCOM_ACP_THRESHOLD "°C (seuil "
#define LANG_MCOM_CHECK_COOLING_BANG "°C) ! Vérifiez le refroidissement."
#define LANG_MCOM_WATER_CRIT_REDUCING "Température d’eau critique ! On abaisse "
#define LANG_MCOM_FROM " de "
#define LANG_MCOM_LOG_BUSY_CLOSE_SKIPPED "Fichier journal occupé : fermeture ignorée"
#define LANG_MCOM_HEATING_LATCHED "Chauffe bloquée par la protection d’urgence, redémarrage requis"
#define LANG_MCOM_HEATING_OFF_PENDING "Coupure de chauffe pas encore terminée. Démarrage annulé."
#define LANG_MCOM_HEATING_NOT_RESUMED "Chauffe non reprise automatiquement. Une nouvelle commande de démarrage est requise."
// mode_registry.h
#define LANG_MREG_NAME_DIST "distillation"
#define LANG_MREG_NAME_BEER "bière"
#define LANG_MREG_NAME_BK "CM"
#define LANG_MREG_NAME_NBK "CMC"
#define LANG_MREG_NAME_CHEESE "fromagerie"
#define LANG_MREG_UNAVAILABLE_NO_REGULATOR "Indisponible dans cette version du firmware : pas de régulateur de puissance"
#define LANG_MREG_UNAVAILABLE_NO_LUA "Indisponible dans cette version du firmware : Lua non activé"
#define LANG_MREG_START_REJECTED_SWITCH "Commande de démarrage refusée : changement de mode pas terminé"
#define LANG_MREG_START_UNAVAILABLE_MODE "Commande de démarrage indisponible dans le mode actuel"
#define LANG_MREG_QUEUE_BUSY_START "File de commandes occupée : démarrage "
#define LANG_MREG_NOT_QUEUED " non mis en file"
#define LANG_MREG_STATUS_MISMATCH "Le statut n’appartient pas au mode actuel - tick ignoré, vérifiez la synchronisation du mode"

// beer.h
#define LANG_BEER_ADD_HOPS "Ajoutez le houblon !"
#define LANG_BEER_ESTOP_COOLING_OPEN "Arrêt d’urgence ! Impossible d’ouvrir le refroidissement"
#define LANG_BEER_ESTOP_COOLING_SAFE "Arrêt d’urgence ! Impossible de remettre le refroidissement en état sûr"
#define LANG_BEER_ESTOP_COOL_PUMP_ON "Arrêt d’urgence ! Impossible d’activer la pompe de refroidissement"
#define LANG_BEER_ESTOP_COOL_PUMP_OFF "Arrêt d’urgence ! Impossible d’arrêter la pompe de refroidissement"
#define LANG_BEER_ESTOP_COOLING_RESTORE "Arrêt d’urgence ! Impossible de remettre le refroidissement en état de marche"
#define LANG_BEER_ESTOP_COOLING_CLOSE "Arrêt d’urgence ! Impossible de fermer le refroidissement"
#define LANG_BEER_SENSOR_TANK "bouill."
#define LANG_BEER_SENSOR_WATER "eau"
#define LANG_BEER_SENSOR_PIPE "colonne"
#define LANG_BEER_SENSOR_STEAM "vapeur"
#define LANG_BEER_SENSOR_ACP "TCA"
#define LANG_BEER_ERR_ROW_NOT_SET "Erreur du programme Bière : ligne non définie"
#define LANG_BEER_ERR_BAD_STAGE_TYPE "Erreur de programme : type d’étape incorrect à la ligne "
#define LANG_BEER_ERR_PROGRAM_PREFIX "Erreur de programme : "
#define LANG_BEER_ERR_PROGRAM "Erreur de programme"
#define LANG_BEER_IN_LINE " à la ligne "
#define LANG_BEER_ERR_BAD_TEMP_SENSOR "Erreur de programme : capteur de température incorrect à la ligne "
#define LANG_BEER_ERR_I2C_PUMP_LINE "Pompe I2C indisponible à la ligne "
#define LANG_BEER_ERR_I2C_PUMP_RELAY_LINE "Relais de pompe I2C indisponible à la ligne "
#define LANG_BEER_ERR_I2C_MIXER_LINE "Agitateur I2C indisponible à la ligne "
#define LANG_BEER_MODE_NAME "Bière"
#define LANG_BEER_START_HEAT_OFF_PENDING "Coupure de chauffe pas encore terminée. Démarrage de l’empâtage annulé."
#define LANG_BEER_START_SAFETY_LATCH "Verrou de sécurité de chauffe actif. Démarrage de l’empâtage annulé."
#define LANG_BEER_START_LOG_FILE "Erreur de création du fichier journal. Démarrage de l’empâtage annulé."
#define LANG_BEER_START_SESSION_BUSY "Description de session occupée. Démarrage de l’empâtage annulé."
#define LANG_BEER_START_POWER_ON_FAILED "Impossible d’activer l’alimentation de la chauffe. Démarrage de l’empâtage annulé."
#define LANG_BEER_WAIT_SKIP_COOL_CONFIRM "Attente de confirmation du saut du refroidissement"
#define LANG_BEER_WORT_NOT_COOLED "Le moût n’a pas encore refroidi jusqu’à la cible. Répétez la transition dans les 10 secondes pour confirmer."
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_NEXT "Erreur Lua : impossible d’arrêter l’agitateur avant la transition"
#define LANG_BEER_LUA_STOP_LOCK_BUSY "Impossible d’arrêter aussitôt le job Lua - verrou occupé. Répétez la transition dans une seconde."
#define LANG_BEER_LUA_STOP_REQUEST_FAILED "Erreur Lua : impossible de demander l’arrêt du job"
#define LANG_BEER_ERR_L_NEEDS_USE_LUA "Erreur de programme : le type L exige USE_LUA"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_START "Erreur Lua : impossible d’arrêter l’agitateur avant le lancement"
#define LANG_BEER_LUA_JOB_NOT_ACCEPTED "Erreur Lua : job non accepté pour le lancement"
#define LANG_BEER_MOVE_TO_LINE "Passage à la ligne de programme n°"
#define LANG_BEER_MSG_HEAT_MALT "; Chauffe jusqu’à la température d’ajout du malt : "
#define LANG_BEER_MSG_TEMP_PAUSE "; Pause de température : "
#define LANG_BEER_MSG_DEG_TIME "°, durée : "
#define LANG_BEER_MIN " min"
#define LANG_BEER_MSG_BOIL_TIME "; Ébullition, durée : "
#define LANG_BEER_MSG_COOL_TO "; Refroidissement à la température : "
#define LANG_BEER_MSG_FERMENT_HOLD "; Fermentation, maintien de la température : "
#define LANG_BEER_MSG_WAIT_MODE "; Mode attente"
#define LANG_BEER_NEXT_LINE "Passage à la ligne suivante"
#define LANG_BEER_LUA_JOB_ACCEPTED_MSG "Tâche Lua acceptée"
#define LANG_BEER_FINISH_ACTUATOR_FAILED "Erreur de fin de brassage : impossible d’arrêter l’actionneur"
#define LANG_BEER_LUA_JOB_WITHOUT_USE_LUA "Erreur Lua : job actif sans USE_LUA"
#define LANG_BEER_BREW_STOPPED_ERROR "Brassage arrêté à cause d’une erreur"
#define LANG_BEER_BREW_DONE "Brassage terminé"
#define LANG_BEER_MASH_PROGRAM_DONE "Programme d’empâtage terminé"
#define LANG_BEER_ESTOP_WORT_OVERTEMP "Arrêt d’urgence ! Température maximale du moût dépassée"
#define LANG_BEER_HOLD_PAUSE_BELOW_TARGET "Pause du maintien : température sous la cible"
#define LANG_BEER_HOLD_RESUMED "Maintien repris"
#define LANG_BEER_MANUAL_PAUSE_ACTUATOR_FAILED "Erreur de pause manuelle : impossible d’arrêter l’actionneur"
#define LANG_BEER_ERR_UNKNOWN_STAGE_TYPE "Erreur de programme : type d’étape inconnu à la ligne "
#define LANG_BEER_LUA_TIMEOUT "Lua n’a pas terminé l’opération avant le délai"
#define LANG_BEER_LUA_MIXER_OFF_ON_STOP "Erreur Lua : impossible d’arrêter l’agitateur à l’arrêt du job"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_CONFIRM "Erreur Lua : impossible d’arrêter l’agitateur avant la confirmation du job"
#define LANG_BEER_LUA_JOB_CONFIRMED "Tâche Lua confirmée"
#define LANG_BEER_LUA_JOB_NO_START_CONFIRM "Erreur Lua : le job n’a pas confirmé le lancement"
#define LANG_BEER_LUA_JOB_FAILED "Erreur Lua : le job s’est terminé avec une erreur"
#define LANG_BEER_WAIT_OPERATOR "Attente d’une action de l’opérateur"
#define LANG_BEER_AUTOTUNE_QUEUE_BUSY "File de commandes occupée : la fin de l’autoréglage de la bière sera répétée"
#define LANG_BEER_MALT_TEMP_REACHED "Température d’ajout du malt atteinte !"
#define LANG_BEER_WAIT_MALT "Attente de l’ajout du malt"
#define LANG_BEER_TEMP_PAUSE_REACHED "Pause de température atteinte "
#define LANG_BEER_DEG_WAITING "°. Attente "
#define LANG_BEER_MINUTES_DOT " minutes."
#define LANG_BEER_COOL_TIMEOUT_24H "Impossible de refroidir le bouilleur à la température cible en 24 heures. Vérifiez le capteur du bouilleur, l’arrivée d’eau de refroidissement et la vanne de refroidissement."
#define LANG_BEER_BOIL_STARTED "Mode ébullition démarré"
#define LANG_BEER_BOIL_NOT_DETECTED_120 "Début d’ébullition non détecté en 120 minutes. Vérifiez le capteur du bouilleur, le volume de liquide, le couvercle et si le seuil d’ébullition est atteignable (basse pression)."
#define LANG_BEER_ESTOP_MIXER_RESTORE "Arrêt d’urgence ! Impossible de restaurer l’état de l’agitateur"
#define LANG_BEER_PID_AUTOTUNE_NO_MEM "Autoréglage PID non lancé : mémoire insuffisante"
#define LANG_BEER_PID_AUTOTUNE_NOT_SAVED "Autoréglage PID non enregistré : "
// cheese.h
#define LANG_CHEESE_TEMP_CONFIRM_STARTED "Confirmation de la température lancée"
#define LANG_CHEESE_PH_CONFIRM_STARTED "Confirmation du pH lancée"
#define LANG_CHEESE_ESTOP_EQUIPMENT_OFF "Arrêt d’urgence ! Impossible d’arrêter l’équipement de fromagerie"
#define LANG_CHEESE_STAGE_HEAT "Chauffe"
#define LANG_CHEESE_STAGE_HOLD "Maintien"
#define LANG_CHEESE_STAGE_COOL "Refroidissement"
#define LANG_CHEESE_STAGE_MIX "Brassage"
#define LANG_CHEESE_STAGE_DOSE "Dosage"
#define LANG_CHEESE_STAGE_PH "Attente du pH"
#define LANG_CHEESE_STAGE_MANUAL "Action manuelle"
#define LANG_CHEESE_STAGE_DRAIN "Vidange"
#define LANG_CHEESE_STAGE_FLOC "Floculation"
#define LANG_CHEESE_STAGE_UNKNOWN "Opération inconnue"
#define LANG_CHEESE_ROW "Ligne "
#define LANG_CHEESE_ERR_ROW_NOT_SET "Erreur du programme Fromage : ligne non définie"
#define LANG_CHEESE_ERR_PROGRAM_PREFIX "Erreur de programme : "
#define LANG_CHEESE_ERR_PROGRAM "Erreur de programme"
#define LANG_CHEESE_IN_LINE " à la ligne "
#define LANG_CHEESE_ERR_TEMP_SENSOR_LINE "Erreur du capteur de température à la ligne "
#define LANG_CHEESE_ERR_I2C_MIXER_LINE "Agitateur I2C indisponible à la ligne "
#define LANG_CHEESE_ERR_LOCAL_DOSER_LINE "Doseur local indisponible à la ligne "
#define LANG_CHEESE_ERR_I2C_PUMP_LINE "Pompe I2C indisponible à la ligne "
#define LANG_CHEESE_ERR_COOLING_NOT_IN_BUILD "Refroidissement indisponible dans cette version"
#define LANG_CHEESE_ERR_PH_CAL_LINE "Étalonnage du pH non autorisé à la ligne "
#define LANG_CHEESE_ERR_LUA_NOT_IN_BUILD "Lua indisponible dans cette version"
#define LANG_CHEESE_ERR_LUA_FILE_LINE "Fichier Lua introuvable à la ligne "
#define LANG_CHEESE_LUA_JOB_ACCEPTED "Tâche Lua acceptée"
#define LANG_CHEESE_NEXT_LINE "Passage à la ligne suivante"
#define LANG_CHEESE_WAIT_OPERATOR "Attente d’une action de l’opérateur"
#define LANG_CHEESE_DOSER_STARTED "Doseur démarré"
#define LANG_CHEESE_LUA_OUTPUTS_OFF_FAILED "Erreur Lua : impossible de couper les sorties"
#define LANG_CHEESE_ERR_ROW_TRANSITION "Erreur de passage à la ligne du programme fromager"
#define LANG_CHEESE_FLOC_RECORDED "|Floc enregistré : "
#define LANG_CHEESE_SEC_UNIT " s"
#define LANG_CHEESE_FLOC_TIMEOUT "Délai de floculation dépassé"
#define LANG_CHEESE_CUT_AFTER_TIMEOUT "L’instant de coupe calculé dépasse le délai de floculation"
#define LANG_CHEESE_FLOC_NO_SESSION "Session de floculation non créée"
#define LANG_CHEESE_LUA_TIMEOUT "Lua n’a pas terminé l’opération avant le délai"
#define LANG_CHEESE_LUA_JOB_DONE "Tâche Lua terminée"
#define LANG_CHEESE_ERR_AFTER_LUA "Erreur de passage après Lua"
#define LANG_CHEESE_LUA_NO_NEXT_LINE "Lua s’est terminée sans passer à la ligne suivante"
#define LANG_CHEESE_LUA_FAILED "Lua s’est terminée avec une erreur"
#define LANG_CHEESE_ERR_UNKNOWN_OPERATION "Erreur de programme : opération inconnue"
#define LANG_CHEESE_MODE_NAME "Fromag"
#define LANG_CHEESE_ERR_TEMP_SENSOR "Erreur du capteur de température"
#define LANG_CHEESE_ERR_MIXER "Erreur de l’agitateur"
#define LANG_CHEESE_OPERATION_TIMEOUT "Délai d’opération du programme fromager dépassé"
#define LANG_CHEESE_TEMP_CONFIRMED "Température confirmée"
#define LANG_CHEESE_HOLD_RESUMED "Maintien repris"
#define LANG_CHEESE_HOLD_PAUSED_OUT_OF_BAND "Maintien en pause : température hors bande"
#define LANG_CHEESE_HOLD_TIMEOUT "Délai de maintien dépassé"
#define LANG_CHEESE_ERR_COOLING "Erreur de refroidissement"
#define LANG_CHEESE_COOLING_OFF_FAILED "Impossible d’arrêter le refroidissement"
#define LANG_CHEESE_DOSING_DONE "Dosage terminé"
#define LANG_CHEESE_I2C_DOSING_ABORTED "Dosage par la pompe I2C interrompu"
#define LANG_CHEESE_PH_INVALID_10S "pH invalide pendant 10 secondes"
#define LANG_CHEESE_PH_CONFIRMED "pH confirmé"
#define LANG_CHEESE_FINISH_OUTPUTS_NOT_OFF "Erreur de fin de fabrication : sorties non coupées"
#define LANG_CHEESE_STOPPED_ERROR "Fabrication du fromage arrêtée à cause d’une erreur"
#define LANG_CHEESE_DONE "Fabrication du fromage terminée"
#define LANG_CHEESE_PROGRAM_DONE "Programme de fromagerie terminé"
#define LANG_CHEESE_START_NO_ADS1115 "ADS1115 introuvable. Démarrage de la fromagerie annulé."
#define LANG_CHEESE_START_HEAT_UNAVAILABLE "Chauffe indisponible. Démarrage de la fromagerie annulé."
#define LANG_CHEESE_START_LOG_FILE "Erreur de création du fichier journal. Démarrage de la fromagerie annulé."
#define LANG_CHEESE_START_SESSION_BUSY "Description de session occupée. Démarrage de la fromagerie annulé."
#define LANG_CHEESE_START_POWER_ON_FAILED "Impossible d’activer l’alimentation de la chauffe. Démarrage de la fromagerie annulé."
#define LANG_CHEESE_STATUS_WAITING "Attente"
#define LANG_CHEESE_STATUS_LINE "; ligne "
// suvid.h
#define LANG_SUVID_MODE_NAME "Sous-vide"
#define LANG_SUVID_SENSOR_WATER "eau"
#define LANG_SUVID_SENSOR_ACP "TCA"
#define LANG_SUVID_SENSOR_TANK "bouill."
#define LANG_SUVID_FINISHED "Sous-vide terminé"
#define LANG_SUVID_HOLD_PAUSED_OUT_OF_BAND "Maintien en pause : température hors bande"
#define LANG_SUVID_DEVIATION_WARNING "Sous-vide : la température s’écarte de la consigne de plus de 2° depuis 60 s."
#define LANG_SUVID_HOLD_RESUMED "Maintien repris"
#define LANG_SUVID_REACH_TIMEOUT "Sous-vide : température de travail non atteinte en 120 minutes, la chauffe est coupée. Vérifiez la résistance, le capteur du bouilleur et le volume de charge."
#define LANG_SUVID_HOLD_DONE "Sous-vide : maintien terminé, chauffe coupée."
#define LANG_SUVID_HOLD_DONE_QUEUE_BUSY "Sous-vide : maintien terminé, mais l’arrêt normal n’est pas mis en file : file de commandes occupée."
// program_io.h
#define LANG_PROG_ERR_PROGRAM "Erreur de programme"
#define LANG_PROG_LINE_OPEN " (ligne "
#define LANG_PROG_LUA_TEXT_BAD "texte Lua vide ou trop long"
#define LANG_PROG_LUA_FILE_REQUIRED "indiquez un fichier .lua ; un argument vide s’écrit «»"
#define LANG_PROG_BEER_DEVICE_MASK "l’appareil doit être 0^0^0^0^0 ou un masque 1..3 avec un horaire non nul"
#define LANG_PROG_BEER_TYPE_MC "pour le type M/C Temp > 0 et Time=0"
#define LANG_PROG_BEER_TYPE_F "pour le type F Temp > 0"
#define LANG_PROG_BEER_TYPE_P "pour le type P Temp et Time doivent être supérieurs à 0"
#define LANG_PROG_BEER_TYPE_B "pour le type B Temp=0 et Time supérieur à 0"
#define LANG_PROG_BEER_TYPE_W "pour le type W Temp=0 et Time=0"
#define LANG_PROG_BEER_TYPE_L "le type L exige un délai et des paramètres nuls"
#define LANG_PROG_L_NEEDS_USE_LUA "le type L exige USE_LUA"
#define LANG_PROG_BEER_TYPE_A "pour le type A Temp est supérieur à 0, Time=0 et appareil=0^0^0^0^0"
#define LANG_PROG_BEER_UNKNOWN_TYPE "type beer inconnu"
#define LANG_PROG_L_TIMEOUT_RANGE "L exige un délai de 1..65535 secondes et des champs numériques nuls"
#define LANG_PROG_SPEED_SR "pour le type S/R Speed doit être dans la plage (0,1)"
#define LANG_PROG_SPEED_AP "pour le type A/P Speed doit être dans la plage [0,100)"
#define LANG_PROG_SPEED_T "pour le type T Speed doit être dans la plage (0,150]"
#define LANG_PROG_STEAM_TEMP_RANGE "T vapeur : 0 ou 30..100"
#define LANG_PROG_BEER_BAD_DEVICE "modèle d’appareil beer incorrect"
#define LANG_PROG_CHEESE_MIXER_FORM "agitateur : 0^0^0^0, relais 1^0, I2C 2 avec RPM non nul ou I2C avec inversion 3 avec RPM, ON et OFF"
#define LANG_PROG_CHEESE_H "H exige Temp, Time, vitesse de chauffe et un capteur"
#define LANG_PROG_CHEESE_P "P exige un capteur et Param pas inférieur à Time"
#define LANG_PROG_CHEESE_C "C exige Temp, Time, un capteur et Param=0"
#define LANG_PROG_CHEESE_M "M exige Time, un agitateur et Temp/Param/capteur nuls"
#define LANG_PROG_CHEESE_D "D exige Time, une méthode et les paramètres du dosage manuel, volumétrique ou pas à pas"
#define LANG_PROG_CHEESE_N "N exige Temp, Time, pH 0..14 et un capteur"
#define LANG_PROG_CHEESE_F "F exige Temp, Time, un multiplicateur pas inférieur à 1 et un capteur"
#define LANG_PROG_CHEESE_W "W exige Time, un code d’action 1..8 et TempSensor=0"
#define LANG_PROG_CHEESE_S "S exige des sorties sûres, Time et des champs nuls"
#define LANG_PROG_CHEESE_L "L exige des sorties sûres, Time et des champs nuls"
#define LANG_PROG_CHEESE_UNKNOWN_TYPE "type cheese inconnu"
#define LANG_PROG_CHEESE_F_MULT "le multiplicateur F ne se représente pas en m=round(MULTIPLIER*1000)"
#define LANG_PROG_CHEESE_BAD_DEVICE "modèle d’appareil cheese incorrect"
#define LANG_PROG_EMPTY_USE_CLEAR "Programme vide : utilisez l’effacement explicite"
#define LANG_PROG_RECT_LINE_TOO_LONG "ligne trop longue (rect)"
#define LANG_PROG_RECT_BAD_FORMAT "format de ligne rect incorrect"
#define LANG_PROG_RECT_TOO_MANY "trop de lignes rect"
#define LANG_PROG_DIST_LINE_TOO_LONG "ligne trop longue (dist)"
#define LANG_PROG_DIST_BAD_FORMAT "format de ligne dist incorrect"
#define LANG_PROG_DIST_TOO_MANY "trop de lignes dist"
#define LANG_PROG_BK_LINE_TOO_LONG "ligne trop longue (bk)"
#define LANG_PROG_BK_BAD_FORMAT "format de ligne bk incorrect"
#define LANG_PROG_BK_TOO_MANY "trop de lignes bk"
#define LANG_PROG_BEER_LINE_TOO_LONG "ligne trop longue (beer)"
#define LANG_PROG_BEER_BAD_FORMAT "format de ligne beer incorrect"
#define LANG_PROG_BEER_TOO_MANY "trop de lignes beer"
#define LANG_PROG_NBK_LINE_TOO_LONG "ligne trop longue (nbk)"
#define LANG_PROG_NBK_BAD_FORMAT "format de ligne nbk incorrect"
#define LANG_PROG_NBK_TOO_MANY "trop de lignes nbk"
#define LANG_PROG_CHEESE_LINE_TOO_LONG "ligne trop longue (cheese)"
#define LANG_PROG_CHEESE_BAD_FORMAT "format de ligne cheese incorrect"
#define LANG_PROG_CHEESE_TOO_MANY "trop de lignes cheese"
#define LANG_PROG_NBK_FOUR_ROWS "La CMC doit contenir 4 lignes H/S/O/W"
#define LANG_PROG_UNSUPPORTED_MODE "mode non pris en charge"
#define LANG_PROG_FIRST_ROW_ABSOLUTE "la première ligne doit définir une puissance/tension absolue (sinon la colonne reste à pleine puissance de montée en température)"
#define LANG_PROG_FIRST_NONZERO_ABSOLUTE "la première ligne avec tension/puissance non nulle doit définir une valeur absolue, pas une correction (sinon la chauffe pendant la montée en température peut s’éteindre sans prévenir)"

// Samovar.ino
// Заголовок уровня V26/push: в любом языке, кроме русского, - только знак ⛔/⚠ (PIN_SPEC.md §6).
#define LANG_MAIN_V26_ALARM_HEADER "⛔ "
#define LANG_MAIN_V26_WARNING_HEADER "⚠ "
#define LANG_MAIN_ASSERT_BLYNK_TIMEOUT "BLYNK_TIMEOUT_MS de Samovar.h sans effet : BlynkConfig.h est inclus plus tôt"
#define LANG_MAIN_ASSERT_BLYNK_SENDBYTES "BLYNK_MAX_SENDBYTES de Samovar.h sans effet : BlynkConfig.h est inclus plus tôt"
#define LANG_MAIN_ASSERT_BLYNK_MSG_LIMIT "BLYNK_MSG_LIMIT de Samovar.h sans effet : BlynkConfig.h est inclus plus tôt"
#define LANG_MAIN_ERR_SENSOR_STEAM "Erreur du capteur de température de la vapeur !"
#define LANG_MAIN_ERR_SENSOR_PIPE "Erreur du capteur de température de la colonne !"
#define LANG_MAIN_ERR_SENSOR_WATER "Erreur du capteur de température de l’eau !"
#define LANG_MAIN_ERR_SENSOR_TANK "Erreur du capteur de température du bouilleur !"
#define LANG_MAIN_ERR_SENSOR_ACP "Erreur du capteur de température de la TCA !"
#define LANG_MAIN_PROG_UNCHANGED_ALL_DONE "Programme inchangé : toutes ses lignes sont déjà exécutées."
#define LANG_MAIN_PROG_UNCHANGED_LINE "Programme inchangé : la ligne "
#define LANG_MAIN_PROG_LINE_LOCKED " ne peut plus être modifiée : elle est en cours ou terminée."
#define LANG_MAIN_PROFILE_OP_CANCELLED_BUSY "Opération de profil annulée : runtime state occupé."
#define LANG_MAIN_NBK_PROG_NOT_SAVED "Programme CMC non enregistré : "
#define LANG_MAIN_MODE_SWITCHED_NOT_SAVED "Mode changé mais non enregistré, un redémarrage rétablit le précédent : "
#define LANG_MAIN_SETTINGS_NOT_SAVED "Paramètres non enregistrés : "
#define LANG_MAIN_PROFILE_OP_TERMINAL_NOT_PUBLISHED "Opération de profil : terminal state non publié ; redémarrage requis."
#define LANG_MAIN_PROFILE_OP_RECORD_UNAVAILABLE "Opération de profil : record indisponible au démarrage ; redémarrage requis."
#define LANG_MAIN_EMERGENCY_BUTTON_TRIGGERED "Arrêt d’urgence ! Entrée du bouton d’urgence déclenchée (bouton ou capteur qui lui est relié)."
#define LANG_MAIN_ACP_TEMP_LABEL " Température TCA "
#define LANG_MAIN_PRESSURE_LIMIT_EXCEEDED "Pression limite dépassée !"
#define LANG_MAIN_SENSOR_SCAN_REJECTED "Scan des capteurs refusé : processus actif."
#define LANG_MAIN_UNFINISHED_SESSION_MODE "Session inachevée détectée, mode "
#define LANG_MAIN_PROGRAM_NUM ", programme n°"
#define LANG_MAIN_HEATING_NOT_RESUMED_AUTO "; chauffe NON reprise automatiquement."
#define LANG_MAIN_NBK_PROG_LEN_BAD_NVS "Longueur du programme CMC incorrecte dans NVS"
#define LANG_MAIN_SESSION_INTERRUPTED_LINE "Session interrompue par un redémarrage : ligne "
#define LANG_MAIN_PROGRAM_RESTORED ", programme restauré"
#define LANG_MAIN_PROGRAM_NOT_RESTORED ", programme non restauré"
#define LANG_MAIN_HEATING_NOT_RESUMED ". Chauffe non reprise."
#define LANG_MAIN_SUVID_HOLD_AT_FAILURE " Maintien Sous-vide cumulé au moment de la panne : "
#define LANG_MAIN_CHEESE_SNAPSHOT_CLEARED "Programme Fromage de l’instantané non restauré et effacé. Programme par défaut non défini."
#define LANG_MAIN_SNAPSHOT_DEFAULT_SET "Programme de l’instantané non restauré, programme par défaut défini."
#define LANG_MAIN_REASON_LABEL " Cause : "
#define LANG_MAIN_EMERGENCY_BUTTON_TASK_NOT_STARTED "Arrêt d’urgence ! Tâche du bouton d’urgence non lancée"
#define LANG_MAIN_BOOT_WITH_ERRORS "Démarrage avec erreurs ("
#define LANG_MAIN_BOOT_LIMITED_MODE "). Certaines fonctions sont indisponibles, fonctionnement en mode limité."
#define LANG_MAIN_EMERGENCY_LOCKOUT "Verrouillage d’urgence : "
#define LANG_MAIN_EMERGENCY_LOCKOUT_NBK_NVS "Verrouillage d’urgence : programme CMC dans NVS endommagé : "
#define LANG_MAIN_EMERGENCY_REGULATOR_TASK_NOT_STARTED "Arrêt d’urgence ! Tâche du régulateur non lancée"
#define LANG_MAIN_EMERGENCY_STACK_LOW "Arrêt d’urgence ! Espace de pile critiquement faible"
#define LANG_MAIN_STACK_OVERFLOW_REBOOT "Débordement de pile. Redémarrage"
#define LANG_MAIN_EMERGENCY_TASK_STACK_LOW "Arrêt d’urgence ! Espace de pile critiquement faible pour la tâche "
#define LANG_MAIN_TASK_STACK_LABEL "Pile de la tâche "
#define LANG_MAIN_TASK_STACK_OVERFLOW_REBOOT " a débordé. Redémarrage"
#define LANG_MAIN_EMERGENCY_SYSTICKER_HUNG "Arrêt d’urgence ! Tâche de surveillance SysTicker bloquée"
#define LANG_MAIN_SYSTICKER_HUNG_REBOOT "Tâche de surveillance SysTicker bloquée. Redémarrage"
#define LANG_MAIN_OP_EXPIRED_FORCED "Opération expirée terminée de force (reaper)"
#define LANG_MAIN_MIXER_CMD_FAILED "Commande de l’agitateur échouée : l’exécutant n’a pas confirmé l’état"
#define LANG_MAIN_NBK_MANUAL_UNAVAILABLE "Commande manuelle indisponible pendant l’Optimisation et le Travail CMC."
#define LANG_MAIN_NBK_BUTTON_ONLY_MANUAL_WORK "Bouton disponible seulement en Réglage manuel et en Travail CMC."
#define LANG_MAIN_OPTIMAL_VALUES_SET "Valeurs optimales définies : "
#define LANG_MAIN_UNIT_LPH " l/h"
#define LANG_MAIN_NBK_CMD_PUMP_UNAVAILABLE "Commande CMC refusée : pompe I2C choisie indisponible."
#define LANG_MAIN_NBK_CMD_BAD_SPEED_CAL "Commande CMC refusée : étalonnage de débit incorrect."
#define LANG_MAIN_NBK_START_NO_REGULATOR "Démarrage CMC refusé : régulateur de puissance indisponible dans cette version."
#define LANG_MAIN_MANUAL_TAKEOFF_PAUSE "Pause manuelle du soutirage"
#define LANG_MAIN_MODE_FROM_SETTINGS_NOT_ACTIVATED "Mode des paramètres non activé : "
#define LANG_MAIN_UNAVAILABLE_IN_BUILD "indisponible dans cette version du firmware"
#define LANG_MAIN_CHEESE_FACT_QUEUE_OVERFLOW "F1 : file des faits saturée, programme fromager arrêté"
#define LANG_MAIN_CHEESE_FLOCCULATION_SAVE_FAILED "Impossible d’enregistrer le fait de floculation"
// power_regulator.h
#define LANG_PWR_QUEUE_BUSY_RESET_AFTER_OFF "File de commandes occupée : reset après coupure de chauffe non mis en file"
#define LANG_PWR_HEAT_REJECTED_TASK_NOT_STARTED "Chauffe refusée : tâche du régulateur non lancée"
#define LANG_PWR_HEAT_BLOCKED_EMERGENCY "Chauffe bloquée par la protection d’urgence, redémarrage requis"
#define LANG_PWR_HEAT_REJECTED_OFF_IN_PROGRESS "Chauffe refusée : coupure de chauffe en cours, réessayez plus tard"
#define LANG_PWR_HEAT_REJECTED_EXCLUSIVE_OP "Chauffe refusée : opération exclusive active (autotest/étalonnage)"
#define LANG_PWR_HEAT_REJECTED_MODE_SWITCH "Chauffe refusée : changement de mode en cours"
#define LANG_PWR_HEAT_REJECTED_START_PENDING "Chauffe refusée : commande de mise en marche déjà en cours, réessayez plus tard"
#define LANG_PWR_CMD_TIMEOUT_HEAT_OFF "Délai de commande du régulateur dépassé ; chauffe coupée"
#define LANG_PWR_START_CMD_FAILED "La commande de démarrage du régulateur a échoué"
#define LANG_PWR_START_CMD_TIMEOUT_HEAT_OFF "Délai de la commande de démarrage du régulateur dépassé ; chauffe coupée"
#define LANG_PWR_START_CMD_SUPERSEDED "Commande de démarrage du régulateur explicitement annulée par une nouvelle commande"
#define LANG_PWR_SESSION_ABORTED_REGULATOR_FAILURE "Session interrompue : panne du régulateur de chauffe. Redémarrage requis."
#define LANG_PWR_CMD_TIMEOUT_AT_HEAT_OFF "Délai de commande du régulateur dépassé à la coupure de chauffe"
#define LANG_PWR_OFF_CMD_FAILED "La commande d’arrêt du régulateur a échoué"
#define LANG_PWR_OFF_CMD_TIMEOUT "Délai de la commande d’arrêt du régulateur dépassé"
#define LANG_PWR_OFF_CMD_SUPERSEDED "Commande d’arrêt du régulateur explicitement annulée par une nouvelle commande"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_OFF "Délai de commande du régulateur dépassé, relais locaux coupés"
#define LANG_PWR_NO_REGULATOR_LINK "Pas de liaison avec le régulateur !"
#define LANG_PWR_EMERGENCY_NO_REGULATOR_LINK "Arrêt d’urgence ! Pas de liaison avec le régulateur de chauffe."
#define LANG_PWR_EMERGENCY_HEATER_CONTROL "Arrêt d’urgence ! Erreur de commande du chauffage."
#define LANG_PWR_UNKNOWN_REGULATOR_MODE "Mode de régulateur inconnu : "
#define LANG_PWR_START_REJECTED_SAFETY_BARRIER "Commande de mise en marche du régulateur refusée par safety-barrier"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_RELEASED "Délai de commande du régulateur dépassé ; relais locaux coupés"
#define LANG_PWR_BG_APPLY_TIMEOUT "Délai d’application en arrière-plan de la commande du régulateur dépassé"
#define LANG_PWR_BG_APPLY_FAILED "L’application en arrière-plan de la commande du régulateur a échoué"
// crash_handler.ino
#define LANG_CRASH_RST_UNKNOWN "Cause de redémarrage inconnue (0)"
#define LANG_CRASH_RST_POWERON "Redémarrage dû à la mise sous tension (1)"
#define LANG_CRASH_RST_EXT "Réinitialisation externe par la broche RESET (2)"
#define LANG_CRASH_RST_SW "Réinitialisation logicielle par esp_restart() (3)"
#define LANG_CRASH_RST_PANIC "Réinitialisation due à une panique ou une exception non gérée (4)"
#define LANG_CRASH_RST_INT_WDT "Réinitialisation due au watchdog interne (5)"
#define LANG_CRASH_RST_TASK_WDT "Réinitialisation due au watchdog de tâche (6)"
#define LANG_CRASH_RST_WDT "Réinitialisation due à l’un des watchdogs (7)"
#define LANG_CRASH_RST_DEEPSLEEP "Réinitialisation après sortie du sommeil profond (8)"
#define LANG_CRASH_RST_BROWNOUT "Réinitialisation due à une tension d’alimentation trop basse (9)"
#define LANG_CRASH_RST_SDIO "Réinitialisation due à une erreur SDIO (10)"
#define LANG_CRASH_RST_UNKNOWN_CODE "Code de cause inconnu : "
#define LANG_CRASH_EMERGENCY_REBOOT "Redémarrage d’urgence"
// WebServer.ino
#define LANG_WEB_STALE_SETTINGS "Les paramètres ont changé sur l’appareil lui-même. Actualisez la page et réessayez."
#define LANG_WEB_ADS1115_PH_BLOCKED "ADS1115 indisponible : étalonnage du pH bloqué"
#define LANG_WEB_MODE_UNAVAILABLE_IN_BUILD "Mode indisponible dans cette version du firmware"
#define LANG_WEB_INVALID_REQUEST_PARAM "Paramètre de requête invalide"
#define LANG_WEB_PARAMS_MUST_BE_UNIQUE "Les paramètres numériques et texte doivent être uniques"
#define LANG_WEB_WPROGRAM_MUST_BE_TEXT "WProgram doit être un paramètre texte"
#define LANG_WEB_CLEAR_REQUIRES_CLEAR1 "L’effacement du programme exige exactement clear=1"
#define LANG_WEB_CLEAR_MUST_BE_SEPARATE "L’effacement du programme doit être une action séparée"
#define LANG_WEB_DESCR_INVALID "Description incorrecte"
#define LANG_WEB_DESCR_TOO_LONG "Description de plus de 250 octets"
#define LANG_WEB_UPDATE_CANCELLED_LOW_SPACE "Mise à jour de l’interface web annulée : manque d’espace disque"
#define LANG_WEB_UPDATE_INCOMPLETE "Mise à jour de l’interface web non terminée, version inchangée"
// Blynk.ino
// Подписи V21 без цифр: приложения берут первое число строки (PIN_SPEC.md §2).
#define LANG_BLYNK_V21_CURRENT "Act:"
#define LANG_BLYNK_V21_TARGET " Cons:"
#define LANG_BLYNK_QUEUE_BUSY_V12 "File de commandes occupée : commande Blynk V12 non mise en file"
#define LANG_BLYNK_QUEUE_BUSY_RESET "File de commandes occupée : reset depuis Blynk non mis en file"
#define LANG_BLYNK_QUEUE_BUSY_V4 "File de commandes occupée : commande Blynk V4 non mise en file"
#define LANG_BLYNK_V34_LINE_BEGIN "V34 : ligne de journal ("
#define LANG_BLYNK_V34_BYTES_NO_FIT " octets) ne tient pas dans le tampon ("
#define LANG_BLYNK_V34_NOT_SENT "), non envoyée"
#define LANG_BLYNK_V35_TRUNCATED_FROM "V35 : description de session tronquée de "
#define LANG_BLYNK_V35_TO " à "
#define LANG_BLYNK_V35_BYTES_BUFFER " octets (tampon "
// lua.h
#define LANG_LUA_CHUNK_TIMEOUT "Lua : exécution du chunk interrompue par délai"
#define LANG_LUA_SENSOR_WATER "eau"
#define LANG_LUA_SENSOR_ACP "TCA"
#define LANG_LUA_SENSOR_TANK "bouill."
#define LANG_LUA_SCRIPT1_STOPPED_AFTER "script.lua arrêté après "
#define LANG_LUA_ERRORS_IN_ROW_SEE_ERR " erreurs de suite, voir les ERR précédentes"
#define LANG_LUA_SCRIPT1_DISABLED "Script commun script.lua désactivé après des erreurs répétées"
#define LANG_LUA_MODE_SCRIPT_BEGIN "script de mode ("
#define LANG_LUA_MODE_SCRIPT_STOPPED_AFTER ") arrêté après "
// Menu.ino
#define LANG_MENU_SETTINGS_NOT_SAVED "Paramètres du menu non enregistrés : "
#define LANG_MENU_QUEUE_BUSY_START "File de commandes occupée : démarrage depuis le menu non mis en file"
#define LANG_MENU_LOG_CREATE_FAILED "Erreur de création du fichier journal. Démarrage de la rectification annulé."
#define LANG_MENU_DESCR_BUSY "Description de session occupée. Démarrage de la rectification annulé."
#define LANG_MENU_LAST_LINE_FINISH "fin de la dernière ligne"
#define LANG_MENU_PROGRAM_DONE_SELF_RUN "Programme terminé. Reflux total ("
#define LANG_MENU_MIN_TO_AUTO_OFF " min avant arrêt auto)."
#define LANG_MENU_STOPPED_BY_USER "Arrêté par l’utilisateur"
#define LANG_MENU_LUA_STOP_FAILED "Impossible d’arrêter Lua : runtime lock occupé."
#define LANG_MENU_RESET_STOP_UNCONFIRMED "Processus arrêté par reset : fin non confirmée"
// impurity_detector.h
#define LANG_DET_LINE_NUM "Ligne n°"
#define LANG_DET_STOP_PAUSES_RATE_CUT " pauses d’arrêt de suite. Débit de base réduit à "
#define LANG_DET_UNIT_LPH_DOT " l/h."
#define LANG_DET_PAUSE_TYPE_BUSY "Détecteur : type de pause auto occupé. Contrôle ignoré."
#define LANG_DET_PAUSE_TYPE_SET_FAILED "Détecteur : impossible de définir le type de pause."
#define LANG_DET_PAUSE_CRITICAL_TREND "Pause du soutirage : tendance critique"
#define LANG_DET_CRITICAL_TREND_PAUSE "Détecteur : tendance critique ! Pause du soutirage. (tendance : "
#define LANG_DET_NEW_BODY_T "Détecteur : définition d’une nouvelle T du cœur (premier programme du cœur, tendance "
#define LANG_DET_RATE_REDUCTION "Détecteur : baisse du débit (tendance "
#define LANG_DET_THRESHOLD ", seuil : "
// FS.ino
#define LANG_FS_MOUNT_FAILED_FORMATTING "Impossible de monter le système de fichiers, formatage..."
#define LANG_FS_FORMAT_FAILED "Impossible de formater le système de fichiers, chargez l’interface via Arduino"
#define LANG_FS_ERROR_UPLOAD "Erreur du système de fichiers ! Chargez via Arduino"
#define LANG_FS_LOW_MEMORY_TOTAL "Mémoire presque épuisée ! Total : "
#define LANG_FS_USED ", utilisé : "
// Samovar.h
#define LANG_SAMH_ASSERT_WPROGRAM_SIZE "WProgram : taille de structure inattendue - vérifiez l’ordre des champs et l’alignement"
#define LANG_SAMH_PWR_MSG_POWER "Puissance"
#define LANG_SAMH_PWR_SIGN_W "W"
#define LANG_SAMH_PWR_MSG_VOLTAGE "Tension"
#define LANG_SAMH_PWR_SIGN_V "V"
// runtime_helpers.h
#define LANG_RT_WAIT_STEAM "(vapeur)"
#define LANG_RT_WAIT_PIPE "(colonne)"
#define LANG_RT_WAIT_DETECTOR "(Détecteur)"
#define LANG_RT_EVENT_RING_REINIT "Journal des événements réinitialisé après corruption"
// valve_buzzer.h
#define LANG_VALVE_OPEN_WATER_SUPPLY "Ouvrez l’arrivée d’eau !"
#define LANG_VALVE_COOLING_OPENED "Vanne d’eau de refroidissement ouverte !"
#define LANG_VALVE_CLOSE_WATER_SUPPLY "Fermez l’arrivée d’eau !"
#define LANG_VALVE_COOLING_CLOSED "Vanne d’eau de refroidissement fermée !"
// selftest.h
#define LANG_SELF_FINISHED "Autotest terminé."
#define LANG_SELF_REJECTED "Autotest refusé : un processus ou un changement de mode est actif"
#define LANG_SELF_STARTING "Lancement de l’autotest."
// sensorinit.h
#define LANG_SENS_UNSUPPORTED_DEFAULT_MODE "mode non pris en charge du programme par défaut"
#define LANG_SENS_LUA_STATUS_RESET_FAILED "Impossible de réinitialiser Lua_status : runtime lock occupé."
#define LANG_SENS_LOG_BUSY_CLOSE_SKIPPED "Fichier journal occupé : fermeture ignorée"
// I2CStepper.h
#define LANG_I2C_LINK_LOST "Liaison perdue avec le stepper I2C, adresse "
#define LANG_I2C_LOCAL_STOP "Arrêt local du stepper I2C, adresse "
// SPIFFSEditor.h
#define LANG_EDIT_JSON_ESCAPE_TRUNCATED "spiffsEditorJsonEscape : chaîne tronquée, mémoire insuffisante"
// string_utils.h
#define LANG_STR_JSON_STRING_TRUNCATED "toJsonString : chaîne tronquée, mémoire insuffisante"
