#pragma once
// Немецкий перевод прошивки. Правила (проверяет tools/smoke_i18n_firmware.py):
//  - по одной строке #define LANG_<KEY> "text" на каждый ключ TR(KEY, "...") из кода;
//    полнота: нет ключа - ошибка компиляции, лишних ключей быть не должно;
//  - в переводе нет кириллицы;
//  - набор printf-спецификаторов (%d %s %.1f ...) совпадает с русским по порядку;
//  - длина перевода в байтах UTF-8 не больше русской (буферы рассчитаны на русский);
//  - секции ключей идут по файлам с комментарием // <имя файла>.
#define SAMOVAR_LANG_NAME "Deutsch"

// nbk.h
#define LANG_NBK_WASH_PROCESSED "Maische verarbeitet "
#define LANG_NBK_UNIT_L_SP " l "
#define LANG_NBK_CFG_COLUMN_INERTIA "Kolonnenträgheit In"
#define LANG_NBK_CFG_DELTA_T "dT-Korrektur"
#define LANG_NBK_CFG_TANK_TEMP "Kesseltemperatur Tn"
#define LANG_NBK_CFG_FLOOD_PRESSURE "Flutdruck DS"
#define LANG_NBK_CFG_POWER_STEP "Leistungsschritt dM"
#define LANG_NBK_CFG_FEED_STEP "Zulaufschritt dP"
#define LANG_NBK_CFG_STEAM_LIMIT "Dampftemperaturgrenze Tp"
#define LANG_NBK_CFG_MAINS_INPUT_INVALID "Netzspannung (Eingabe nicht erkannt)"
#define LANG_NBK_CFG_HEATER_INPUT_INVALID "Heizelement-Widerstand (Eingabe nicht erkannt)"
#define LANG_NBK_CFG_MAINS_RANGE "Netzspannung außerhalb des Bereichs"
#define LANG_NBK_CFG_HEATER_RANGE "Heizelement-Widerstand außerhalb des Bereichs"
#define LANG_NBK_CEILING_LOWERED_TO "Druckobergrenze gesenkt auf "
#define LANG_NBK_MM_FLOODING_AT " mm (Fluten bei "
#define LANG_NBK_MM_CLOSE " mm)"
#define LANG_NBK_SRC_FLOOD_SENSOR "FS"
#define LANG_NBK_SRC_NO_PRESSURE_DATA "keine DS-Daten"
#define LANG_NBK_SRC_PRESSURE_SENSOR "DS"
#define LANG_NBK_HEATUP_ACTUATORS_NOT_CONFIRMED "KMK-Aufheizen hat Aktor-Befehle nicht bestätigt."
#define LANG_NBK_SAFE_WAIT "KMK-Sicherheitswarten."
#define LANG_NBK_ACTUATOR_CONFIRM_TIMEOUT "Zeitüberschreitung bei Aktor-Bestätigung der KMK. Sicherheitswarten."
#define LANG_NBK_ACTUATOR_CMD_HEATING_OFF "KMK-Aktor-Befehl bei ausgeschalteter Heizung abgelehnt."
#define LANG_NBK_REGULATOR_NOT_CONFIRMED "Regler hat KMK-Befehl nicht bestätigt. Sicherheitswarten."
#define LANG_NBK_PUMP_NOT_CONFIRMED "KMK-Pumpe hat Befehl nicht bestätigt. Heizung aus."
#define LANG_NBK_WORK_RESUMED "KMK-Arbeit fortgesetzt."
#define LANG_NBK_WARMUP_POWER_FEED_SET "Leistung und Zulauf für KMK-Aufwärmen eingestellt."
#define LANG_NBK_MODE_NAME "KMK"
#define LANG_NBK_SENSOR_VAPOR "Dampf"
#define LANG_NBK_SENSOR_BOILER "Kessel"
#define LANG_NBK_RESTART_IMPOSSIBLE "KMK-Neustart nicht möglich: "
#define LANG_NBK_HEATING_NOT_OFF_YET "Heizung noch nicht aus"
#define LANG_NBK_PUMP_STOP_NOT_CONFIRMED "Pumpe hat Stopp nicht bestätigt"
#define LANG_NBK_SESSION_CONFIG_NOT_CAPTURED "KMK-Sitzungskonfiguration nicht erfasst."
#define LANG_NBK_PROGRAM_LINE_OUT_OF_RANGE "KMK-Programmfehler: Zeilennummer außerhalb des Bereichs"
#define LANG_NBK_PROGRAM_LINE_NOT_SET "KMK-Programmfehler: Zeile nicht gesetzt"
#define LANG_NBK_WARMUP_TOO_HIGH_PREFIX "Beim Aufwärmen zu hohe Werte gesetzt: "
#define LANG_NBK_AND_OR_FEED_PROGRAM_STOP " und/oder Zulauf! Programm gestoppt."
#define LANG_NBK_AFTER_FLOOD_REDUCE_REJECTED "KMK-Aktor-Absenkung nach Fluten nicht angenommen."
#define LANG_NBK_FLOODING_BY "Fluten durch "
#define LANG_NBK_FEED_THIRD_POWER_HALF ". Zulauf 1/3, Leistung 1/2."
#define LANG_NBK_BEFORE_OPT_SETUP_PREFIX "Schon vor Beginn der Optimierung: die im Setup gesetzten "
#define LANG_NBK_AND_FEED_TOO_HIGH_STOP " und Zulauf sind zu hoch. Stopp."
#define LANG_NBK_MANUAL_WORK_WAIT_PREFIX "Beim Warten auf manuellen Wechsel zur Arbeit: die gesetzten "
#define LANG_NBK_OPT_INITIAL_REJECTED "KMK-Optimierung: Startparameter nicht angenommen."
#define LANG_NBK_OPT_ACCEPTED_FROM "Optimierung übernommen von: "
#define LANG_NBK_UNIT_LPH_SP " l/h "
#define LANG_NBK_SET_PARAMS_PREFIX "Die gesetzten "
#define LANG_NBK_AND_SPEED_TOO_HIGH_OPT_STOP " und Geschwindigkeit sind zu hoch - Optimierung unmöglich. Stopp."
#define LANG_NBK_TN_REFINED_BY_SENSOR "Referenz-Tn per Schlempensensor präzisiert: "
#define LANG_NBK_OPT_NO_FLOOD_SENSOR "Optimierung unmöglich - kein Flutsensor vorhanden. Stellen Sie die nötigen Parameter manuell im Programm der Phase Arbeit ein und drücken Sie Nächstes Programm. Nach 10 Minuten geht der Prozess ins Sicherheitswarten (Heizung und Zulauf aus)."
#define LANG_NBK_C_IN_SETTINGS " °C (in den Einstellungen "
#define LANG_NBK_FEED_LIMIT_REACHED "Zulaufgrenze erreicht ("
#define LANG_NBK_LPH_RESULT_COLON " l/h). Ergebnis: "
#define LANG_NBK_OPT_TB_GE_TN "Optimierung: Tb >= Tn ("
#define LANG_NBK_INCREASING_FEED_ITER "), Zulauf wird erhöht. Iteration "
#define LANG_NBK_POWER_LIMIT_REACHED "Leistungsgrenze erreicht. ("
#define LANG_NBK_W_RESULT_COLON " W.). Ergebnis: "
#define LANG_NBK_UNIT_LPH_DOT " l/h."
#define LANG_NBK_OPT_NOT_FOUND_TB_TN "Optimum nicht gefunden: Tb erreichte Tn nicht ("
#define LANG_NBK_NO_ITERATION_CHECK_TB ") in keiner Iteration. Tb-Sensor prüfen."
#define LANG_NBK_OPT_TP_LT_TPMIN "Optimierung: Tp < Tp min("
#define LANG_NBK_INCREASING "), erhöhe "
#define LANG_NBK_ITERATION_SP ". Iteration "
#define LANG_NBK_OPT_TB_LT_TN "Optimierung: Tb < Tn("
#define LANG_NBK_OPT_CORRECTION_REJECTED "KMK-Optimierungskorrektur nicht angenommen."
#define LANG_NBK_ITER_LIMIT_RESULT "Iterationslimit erreicht. Ergebnis: "
#define LANG_NBK_UNIT_LPH " l/h"
#define LANG_NBK_TEMP_REDUCE_FEED_HEATING "Zulauf und Heizung vorübergehend gesenkt."
#define LANG_NBK_WORK_WASH_SPILL "Arbeit: Maische-Überlauf (Tb "
#define LANG_NBK_FEED_REDUCED_BY "), Zulauf gesenkt um "
#define LANG_NBK_TO_COLON ", auf: "
#define LANG_NBK_WORK_TB_LT_TN_DT "Arbeit: Tb < Tn-dT ("
#define LANG_NBK_REDUCING_FEED_BY "), senke Zulauf um "
#define LANG_NBK_WORK_TP_BELOW_LIMIT "Arbeit: Tp unter Grenze ("
#define LANG_NBK_WORK_PRESSURE "Arbeit: Druck "
#define LANG_NBK_GE_CEILING " ≥ Obergrenze "
#define LANG_NBK_MM_REDUCING_FEED_BY " mm, senke Zulauf um "
#define LANG_NBK_WORK_TB_GT_TN_DT "Arbeit: Tb > Tn+dT ("
#define LANG_NBK_INCREASING_FEED_BY "), erhöhe Zulauf um "
#define LANG_NBK_WORK_CORRECTION_REJECTED "KMK-Arbeitskorrektur nicht angenommen."
#define LANG_NBK_REPEAT_FLOODING_BY "Erneutes Fluten durch "
#define LANG_NBK_DURING_PAUSE_EXTENDED " während der Pause. Pause verlängert, Leistung halbiert."
#define LANG_NBK_REPEAT_POWER_REDUCE_REJECTED "Erneute KMK-Leistungssenkung nicht angenommen."
#define LANG_NBK_WORK_RESUME_REJECTED "Fortsetzen der KMK-Arbeit nicht angenommen."
#define LANG_NBK_WORK_RESUME_AFTER_FLOOD "Arbeit: Fortsetzung nach Fluten, korrigierte Parameter: "
#define LANG_NBK_WORK_CONTINUE_AFTER_PAUSE "Arbeit: Zyklus nach Pause wird fortgesetzt."
#define LANG_NBK_RESUME_IMPOSSIBLE_EMERGENCY "Fortsetzen der KMK-Arbeit unmöglich: Notfall gespeichert."
#define LANG_NBK_RESUME_IMPOSSIBLE_NO_SNAPSHOT "Fortsetzen der KMK-Arbeit unmöglich: kein Sitzungskonfig-Abbild."
#define LANG_NBK_RESUME_REJECTED_CMD_BUSY "Fortsetzen der KMK-Arbeit abgelehnt: vorheriger Aktor-Befehl läuft noch."
#define LANG_NBK_WORK_WAITS_HEATING_OFF "KMK-Arbeit wartet auf das Ende der Heizungsabschaltung."
#define LANG_NBK_RESUME_UNAVAILABLE_PUMP_STOP "Fortsetzen der KMK-Arbeit nicht möglich: Pumpenstopp nicht bestätigt."
#define LANG_NBK_HEATING_NOT_ON_RESUME "KMK-Heizung beim Fortsetzen der Arbeit nicht eingeschaltet."
#define LANG_NBK_RESUME_PARAMS_REJECTED "Fortsetzen der KMK-Arbeit: Parameter von Aktoren nicht angenommen."
#define LANG_NBK_WORK_RESUMED_M "KMK-Arbeit fortgesetzt: M="
#define LANG_NBK_COMMA_P ", P="
#define LANG_NBK_START_REJECTED_NO_REGULATOR "KMK-Start abgelehnt: Leistungsregler in diesem Build nicht verfügbar."
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_NO_REGULATOR "KMK-Pumpenstopp in nicht verfügbarer Konfiguration nicht bestätigt."
#define LANG_NBK_LINE_SWITCH_HEATING_STARTING "KMK-Zeilenwechsel abgelehnt: Heizungsstart noch nicht abgeschlossen"
#define LANG_NBK_PROGRAM_NOT_SET "KMK-Programm nicht gesetzt"
#define LANG_NBK_GOTO_WORK_NO_SNAPSHOT "Wechsel zur KMK-Arbeit abgelehnt: kein Sitzungskonfig-Abbild."
#define LANG_NBK_AUTO_WORK_IMPOSSIBLE "Automatischer Eintritt in KMK-Arbeit unmöglich: Heizung aus oder Optimum nicht gefunden."
#define LANG_NBK_AUTO_WORK_PARAMS_REJECTED "Parameter des Auto-Eintritts in die Arbeit von KMK-Aktoren nicht angenommen."
#define LANG_NBK_OPT_FINISHED "Optimierung beendet"
#define LANG_NBK_BY_PRESSURE " nach Druck ("
#define LANG_NBK_COLON_MO ": Mo="
#define LANG_NBK_COMMA_PO ", Po="
#define LANG_NBK_LPH_PAUSE " l/h. Pause "
#define LANG_NBK_S_THEN_WORK " s, dann Arbeit."
#define LANG_NBK_AUTO_WORK_FORBIDDEN "Automatischer Wechsel zur KMK-Arbeit verboten. Power/Speed der Zeile W setzen und Nächstes Programm drücken."
#define LANG_NBK_LINE_W_NEEDS_NONZERO "Zeile W braucht Power und Speed ungleich null oder gespeicherte Optimalwerte."
#define LANG_NBK_WORK_UNAVAILABLE_PUMP_STOP "KMK-Arbeit nicht verfügbar: Pumpenstopp nicht bestätigt."
#define LANG_NBK_HEATING_NOT_ON_EXPLICIT_WORK "KMK-Heizung nach explizitem Wechsel zur Arbeit nicht eingeschaltet."
#define LANG_NBK_HEATING_OFF_WORK_REJECTED "KMK-Heizung ist aus. Wechsel zur Arbeit abgelehnt."
#define LANG_NBK_LINE_W_PARAMS_REJECTED "Parameter der Zeile W von KMK-Aktoren nicht angenommen."
#define LANG_NBK_EXPLICIT_WORK_ACCEPTED_M "Expliziter Wechsel zur KMK-Arbeit angenommen: M="
#define LANG_NBK_W_COMMA_P " W, P="
#define LANG_NBK_SAFE_WAIT_STOPPED_BY_OPERATOR "Sicherheitswarten vom Bediener gestoppt."
#define LANG_NBK_SAFE_WAIT_SESSION_ENDED "KMK-Sicherheitswarten: Sitzung per Bedienerbefehl beendet."
#define LANG_NBK_START_HEATING_OFF_PENDING "Heizungsabschaltung noch nicht beendet. KMK-Start abgebrochen."
#define LANG_NBK_HEATING_OFF_GOTO_LINE "KMK-Heizung ist aus. Wechsel zu Zeile #"
#define LANG_NBK_CANCELLED_DOT " abgebrochen."
#define LANG_NBK_START_REJECTED_BAD_SETTING "KMK-Start abgelehnt: ungültige Einstellung - "
#define LANG_NBK_START_LOG_FILE_ERROR "Fehler beim Erstellen der Logdatei. KMK-Start abgebrochen."
#define LANG_NBK_PROGRAM_STARTED_WARMUP "KMK-Programm gestartet. Aufwärmen"
#define LANG_NBK_NO_FLOOD_SENSORS_WARNING "Achtung: kein Flutsensor vorhanden (FS aus, DS antwortet nicht). Flutschutz ist unwirksam."
#define LANG_NBK_START_SESSION_BUSY "Sitzungsbeschreibung belegt. KMK-Start abgebrochen."
#define LANG_NBK_GOTO_LINE "Wechsel zu Zeile #"
#define LANG_NBK_TYPE_SP ". Typ: "
#define LANG_NBK_START_HEATING_NOT_ON "KMK-Heizung nicht eingeschaltet. Start abgebrochen."
#define LANG_NBK_HEATUP_TRANSITION_STARTED "KMK-Aufheiz-Übergang gestartet."
#define LANG_NBK_MANUAL_NEEDS_NONZERO "Manuelle KMK-Einstellung braucht Leistung und Zulauf ungleich null."
#define LANG_NBK_MANUAL_PARAMS_REJECTED "Parameter der manuellen KMK-Einstellung nicht angenommen."
#define LANG_NBK_PROGRAM_LINE_EMPTY "KMK-Programmfehler: leere Programmzeile"
#define LANG_NBK_STEAM_98_WASH_OUT "Dampftemperatur 60 Sekunden über 98°C. Maische ist aufgebraucht. KMK-Programm beendet."
#define LANG_NBK_EMERGENCY_WASH_OUT "Notabschaltung! KMK-Programm nicht regulär beendet (Maische aufgebraucht)"
#define LANG_NBK_TP_ROSE_BY "Tp stieg um "
#define LANG_NBK_C_RELATIVE_TO_MIN " °C relativ zum Minimum "
#define LANG_NBK_C_WASH_ENDING " °C — Maische geht zur Neige. KMK-Programm beendet."
#define LANG_NBK_EMERGENCY_TP_RISE "Notabschaltung! KMK-Programm nicht regulär beendet (Anstieg Dampf-Tp)"
#define LANG_NBK_STEAM_OVER_LIMIT_MANUAL "Dampf-T 60 Sekunden über Grenze bei manueller Einstellung. Dampferzeuger evtl. trocken. KMK-Programm beendet."
#define LANG_NBK_EMERGENCY_STEAM_OVERHEAT_MANUAL "Notabschaltung! KMK-Programm nicht regulär beendet (Dampfüberhitzung bei manueller Einstellung)"
#define LANG_NBK_INSUFFICIENT_COOLING "Unzureichende Kühlung! Stopp."
#define LANG_NBK_PRESSURE_SENSOR_FAILED "Drucksensor ausgefallen! Seit über 60 Sekunden keine Werte. Stopp."
#define LANG_NBK_LOG_BUSY_CLOSE_SKIPPED "Logdatei belegt: Schließen nicht ausgeführt"
#define LANG_NBK_HEATUP_TRANSITION_ABORTED "KMK-Aufheiz-Übergang abgebrochen."
#define LANG_NBK_HEATING_START_ABORTED "KMK-Heizungsstart abgebrochen: Startbedingung verletzt, Prozess gestoppt."
#define LANG_NBK_HEATUP_NEEDS_CONFIRMED_FEED "KMK-Aufheizen braucht bestätigten Zulauf ungleich null."
#define LANG_NBK_RUN_FINISHED "KMK-Arbeit beendet"
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_ON_FINISH "KMK-Pumpenstopp beim Beenden nicht bestätigt."
#define LANG_NBK_AVG_SESSION_RATE "mit durchschnittlicher Sitzungsrate "
#define LANG_NBK_AND_AVG_FEED_RATE "und durchschnittlicher Zulaufrate "
#define LANG_NBK_OVER_COLON "in: "
#define LANG_NBK_UNIT_H_DOT " h."
#define LANG_NBK_RUN_FINISHED_DOT "KMK-Arbeit beendet."
#define LANG_NBK_RUN_ABORTED_EMERGENCY "KMK-Arbeit durch Notfall abgebrochen."
#define LANG_NBK_FLOOD_FEED_REDUCE_UNCONFIRMED "KMK-Zulaufsenkung bei Fluten nicht bestätigt."
#define LANG_NBK_EMERGENCY_FLOODING "Notabschaltung! KMK-Programm nicht regulär beendet (Fluten)"
#define LANG_NBK_FLOOD_ACTUATOR_REDUCE_REJECTED "KMK-Aktor-Absenkung bei Fluten nicht angenommen."
// BK.h
#define LANG_BK_WORK_POWER_APPLIED "MK-Arbeitsleistung angewendet."
#define LANG_BK_PROGRAMS_DONE_CONTINUE "Programme beendet, Abnahme wird fortgesetzt"
#define LANG_BK_LUA_LINE_SCRIPT_NOT_STARTED "Lua-Fehler: Zeilenskript nicht gestartet"
#define LANG_BK_PROGRAM_L_NEEDS_LUA "Programmfehler: Typ L erfordert USE_LUA"
#define LANG_BK_GOTO_PROGRAM_LINE "Wechsel zu Programmzeile #"
#define LANG_BK_DEPHLEGMATOR_WATER_MANUAL "Dephlegmatorwasser: manuelle Steuerung"
#define LANG_BK_PUMP_CONTROL_UNSUPPORTED "Pumpensteuerung wird von Ihrer Hardware nicht unterstützt"
#define LANG_BK_MODE_NAME "MK"
#define LANG_BK_SENSOR_BOILER "Kessel"
#define LANG_BK_SENSOR_VAPOR "Dampf"
#define LANG_BK_START_NO_TANK_SENSOR "MK nicht gestartet: Kesselsensor nicht zugewiesen oder antwortet nicht"
#define LANG_BK_START_NEEDS_STEAM_SENSOR "MK nicht gestartet: Programm erfordert Dampfsensor"
#define LANG_BK_START_LOG_FILE_ERROR "Fehler beim Erstellen der Logdatei. MK-Start abgebrochen."
#define LANG_BK_START_SESSION_BUSY "Sitzungsbeschreibung belegt. MK-Start abgebrochen."
#define LANG_BK_HEATING_ON "Heizung der Maischekolonne eingeschaltet"
#define LANG_BK_WAIT_WORK_POWER "Warten auf MK-Arbeitsleistung."
#define LANG_BK_LUA_TIMEOUT "Lua hat den Vorgang nicht vor Zeitablauf beendet"
#define LANG_BK_LUA_FAILED "Lua mit Fehler beendet"
#define LANG_BK_RUN_FINISHED_DOT "MK-Arbeit beendet."
#define LANG_BK_RUN_FINISHED "Arbeit der Maischekolonne beendet"
// distiller.h
#define LANG_DIST_NO_ALCOHOL_LEFT "Kein Alkohol mehr im Kessel"
#define LANG_DIST_ABV_UNAVAILABLE "Alkoholgehalt nicht verfügbar: Prozentzeile läuft weiter"
#define LANG_DIST_MODE_NAME "Destillation"
#define LANG_DIST_SENSOR_BOILER "Kessel"
#define LANG_DIST_START_NO_TANK_SENSOR "Destillation nicht gestartet: Kesselsensor nicht zugewiesen oder antwortet nicht. Einstellungen öffnen und Zuordnung des Kesselsensors prüfen."
#define LANG_DIST_START_LOG_FILE_ERROR "Fehler beim Erstellen der Logdatei. Destillationsstart abgebrochen."
#define LANG_DIST_START_SESSION_BUSY "Sitzungsbeschreibung belegt. Destillationsstart abgebrochen."
#define LANG_DIST_HEATING_ON "Heizung der Destillationsanlage eingeschaltet"
#define LANG_DIST_LUA_TIMEOUT "Lua hat den Vorgang nicht vor Zeitablauf beendet"
#define LANG_DIST_LUA_FAILED "Lua mit Fehler beendet"
#define LANG_DIST_FINISHED "Destillation beendet."
#define LANG_DIST_TOTAL_TIME " Gesamtzeit: "
#define LANG_DIST_UNIT_MIN " min."
#define LANG_DIST_PROGRAMS_DONE_CONTINUE "Programme beendet, Abnahme wird fortgesetzt"
#define LANG_DIST_LUA_LINE_SCRIPT_NOT_STARTED "Lua-Fehler: Zeilenskript nicht gestartet"
#define LANG_DIST_PROGRAM_L_NEEDS_LUA "Programmfehler: Typ L erfordert USE_LUA"
#define LANG_DIST_GOTO_PROGRAM_LINE "Wechsel zu Programmzeile #"

// logic.h
#define LANG_LOGIC_PRG_NUM "Zeile #"
#define LANG_LOGIC_PROG_LINE_START "Programm: Start von Zeile  #"
#define LANG_LOGIC_PROG_LINE_START_LUA "Programm: Start von Zeile #"
#define LANG_LOGIC_TAKEOFF_TO_CONTAINER ", Abnahme in Behälter "
#define LANG_LOGIC_I2C_PUMP_CMD_HEAD "I2C-Pumpe über ZP: Befehl «"
#define LANG_LOGIC_I2C_PUMP_CMD_TAIL "» nach 10 Versuchen nicht bestätigt."
#define LANG_LOGIC_LUA_OP_DONE "Lua-Operation abgeschlossen"
#define LANG_LOGIC_LUA_OP_NOT_DONE "Lua-Operation nicht abgeschlossen"
#define LANG_LOGIC_LUA_TIMEOUT "Lua hat den Vorgang nicht vor Zeitablauf beendet"
#define LANG_LOGIC_LUA_OP_FAILED "Lua-Operation fehlgeschlagen"
#define LANG_LOGIC_LUA_ERROR "Lua mit Fehler beendet"
#define LANG_LOGIC_AUTOPAUSE_BUSY_SKIP "Typ der Autopause belegt. Abnahmeprüfung übersprungen."
#define LANG_LOGIC_PAUSE_SET_FAIL_HEAD "Pause konnte nicht gesetzt werden bei "
#define LANG_LOGIC_PAUSE_TYPE_BUSY_TAIL ": Pausentyp belegt."
#define LANG_LOGIC_AUTOPAUSE_TAIL "Automatische Abnahmepause"
#define LANG_LOGIC_PAUSE_BY "Pause bei "
#define LANG_LOGIC_RESUME_AFTER_AUTOPAUSE "Abnahme nach automatischer Pause wird fortgesetzt"
#define LANG_LOGIC_TAKEOFF_RESUMED "Abnahme fortgesetzt"
#define LANG_LOGIC_LABEL_T_STEAM "T Dampf"
#define LANG_LOGIC_LABEL_T_PIPE "T Kolonne"
#define LANG_LOGIC_DETECTOR_RESUME "Detektor: Abnahme nach Pause wird fortgesetzt"
#define LANG_LOGIC_PUMP_CAL_BAD_STEPS "Pumpenkalibrierungsfehler: ungültige Schrittzahl"
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_HEAD "Pumpenkalibrierung nicht gespeichert: "
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_TAIL ". Ergebnis verloren, Kalibrierung wiederholen."
#define LANG_LOGIC_ACTION_PAUSE "Pause"
#define LANG_LOGIC_ACTION_RESUME "Fortsetzen"
#define LANG_LOGIC_MANUAL_PAUSE_TAKEOFF "Manuelle Abnahmepause"
#define LANG_LOGIC_MANUAL_PAUSE_MASH "Manuelle Maischepause"
#define LANG_LOGIC_MASH_PAUSE_NEXT_STEP "Pause wird beim nächsten Maischeschritt angewendet."
#define LANG_LOGIC_MASH_PAUSED "Maischen pausiert."
#define LANG_LOGIC_AUTOPAUSE_RESET_FAIL "Typ der Autopause konnte nicht zurückgesetzt werden."
#define LANG_LOGIC_MASH_RESUMED_TAIL "Maischen fortgesetzt"
#define LANG_LOGIC_MASH_RESUMED_MSG "Maischen fortgesetzt."
#define LANG_LOGIC_DIST_MODE_SEP "; Destillationsmodus"
#define LANG_LOGIC_DIST_PROGRAMS_DONE "Programme erledigt, Abnahme bis Kessel-T "
#define LANG_LOGIC_DIST_MODE_DEG "°; Destillationsmodus"
#define LANG_LOGIC_DIST_ROW_LEFT "; Zeile: noch "
#define LANG_LOGIC_OF_APPROX " von ~"
#define LANG_LOGIC_UNIT_MIN " min"
#define LANG_LOGIC_DIST_ROW_FORECAST_WAIT "; Zeilenprognose: warte auf Daten"
#define LANG_LOGIC_DIST_PROCESS_LEFT "; Prozess bis DistTemp, noch:"
#define LANG_LOGIC_DIST_TOTAL "; Gesamt:"
#define LANG_LOGIC_DIST_PROCESS_FORECAST_WAIT "; Prozessprognose: warte auf Kochen/Daten"
#define LANG_LOGIC_BK_MODE "Maischekolonnen-Modus"
#define LANG_LOGIC_NBK_STAGE_H "Aufwärmen"
#define LANG_LOGIC_NBK_STAGE_S "Setup"
#define LANG_LOGIC_NBK_STAGE_O "Optimierung"
#define LANG_LOGIC_NBK_STAGE_W "Arbeit"
#define LANG_LOGIC_BEER_ON_PAUSE "Pausiert; "
#define LANG_LOGIC_BEER_WAIT_SKIP_COOL "Warte auf Bestätigung zum Überspringen der Kühlung; "
#define LANG_LOGIC_BEER_HEAT_TO_MALT "Aufheizen auf Temperatur zum Malzeinfüllen"
#define LANG_LOGIC_CUR_T "; Aktuelle T: "
#define LANG_LOGIC_BEER_WAIT_MALT "Warte auf Malzeinfüllen"
#define LANG_LOGIC_BEER_PAUSE "Pause "
#define LANG_LOGIC_BEER_DEG_HEATING "°; Aufheizen"
#define LANG_LOGIC_BEER_COOL_TO "Kühlen auf "
#define LANG_LOGIC_BEER_WAIT_PRESS_NEXT "Warten. Nächstes Programm drücken; "
#define LANG_LOGIC_BEER_AUTOCAL "Autokalibrierung. Nach Abschluss "
#define LANG_LOGIC_BEER_AUTOCAL_POWER_OFF "wird die Leistung abgeschaltet"
#define LANG_LOGIC_BEER_AUTOCAL_NEXT_LINE "Wechsel zur nächsten Zeile"
#define LANG_LOGIC_BEER_BOIL_HEATING "Kochen - Aufheizen"
#define LANG_LOGIC_BEER_BOIL "Kochen "
#define LANG_LOGIC_BEER_FERM_HOLD "Gärung; Halte T="
#define LANG_LOGIC_CUR_SHORT "; Akt: "
#define LANG_LOGIC_PAREN_HEATING " (Heizen)"
#define LANG_LOGIC_PAREN_THERMOSTAT " (Thermostat)"
#define LANG_LOGIC_BEER_FERM_STOPPED "Gärung (gestoppt)"
#define LANG_LOGIC_RUNNING_LUA_SCRIPT "Lua-Skript läuft"
#define LANG_LOGIC_PROGRESS "; Fortschritt: "
#define LANG_LOGIC_STATUS_OFF "Aus"
#define LANG_LOGIC_PAREN_ERROR "(Fehler)"
#define LANG_LOGIC_AUTOPAUSE_READ_FAIL "Typ der Autopause konnte nicht gelesen werden."
#define LANG_LOGIC_PAUSE_SP " Pause "
#define LANG_LOGIC_RESUME_IN ". Fortsetzung in "
#define LANG_LOGIC_UNIT_SEC " s."
#define LANG_LOGIC_PROGRAM_DONE_STATUS "Programm abgeschlossen"
#define LANG_LOGIC_STATUS_CALIBRATION "Kalibrierung"
#define LANG_LOGIC_STATUS_PAUSE "Pause"
#define LANG_LOGIC_SUVID_HOLD "Sous-vide; Halte T="
#define LANG_LOGIC_DEG_CUR "°; Akt: "
#define LANG_LOGIC_SUVID_HOLD_TIME "; Haltezeit: "
#define LANG_LOGIC_COLUMN_HEATUP "Kolonne heizt auf"
#define LANG_LOGIC_HEATUP_DONE_STAB "Aufheizen beendet. Stabilisierung/Selbstlauf"
#define LANG_LOGIC_STAB_DONE "Stabilisierung beendet/Selbstlauf"
#define LANG_LOGIC_LEFT "; Verbleibend:"
#define LANG_LOGIC_BODY_T_STEAM ";T Mittellauf Dampf:"
#define LANG_LOGIC_BODY_T_PIPE ";T Mittellauf Kolonne:"
#define LANG_LOGIC_PUMP_NOT_CALIBRATED "Pumpe nicht kalibriert (Schritte pro ml = 0). Rektifikationsstart unmöglich."
#define LANG_LOGIC_RECT_PROG_LINE_UNSET "Rektifikationsprogrammfehler: Zeile nicht gesetzt"
#define LANG_LOGIC_RECT_PROG_FIRST_LINE "Programmfehler: Die erste Zeile muss absolute Leistung/Spannung setzen. Rektifikationsstart unmöglich."
#define LANG_LOGIC_PROG_ERR_LINE "Programmfehler: Zeile "
#define LANG_LOGIC_PROG_LINE_NEVER_ENDS " endet nie (Volumen und Temperatur nicht gesetzt)"
#define LANG_LOGIC_ACTION_PROGRAM_END "Programmende"
#define LANG_LOGIC_PROGRAM_FINISHED "Programm beendet"
#define LANG_LOGIC_LOG_BUSY_CLOSE_SKIPPED "Logdatei belegt: Schließen übersprungen"
#define LANG_LOGIC_PROGRAM_DONE_MSG "Programm abgeschlossen."
#define LANG_LOGIC_LUA_LINE_SCRIPT_NOT_STARTED "Lua-Fehler: Zeilenskript nicht gestartet"
#define LANG_LOGIC_NEXT_LINE "Wechsel zur nächsten Zeile"
#define LANG_LOGIC_LUA_OP_STARTED "Lua-Operation gestartet"
#define LANG_LOGIC_PROG_TYPE_L_NEEDS_LUA "Programmfehler: Typ L erfordert USE_LUA"
#define LANG_LOGIC_ACTION_LINE_START "Zeilenstart "
#define LANG_LOGIC_PROG_LINE_SPEED "Programm: Zeilengeschwindigkeit #"
#define LANG_LOGIC_SPEED_OVER_PUMP_LIMIT " l/h) überschreitet das Pumpenlimit, begrenzt auf "
#define LANG_LOGIC_UNIT_LPH_DOT " l/h."
#define LANG_LOGIC_COMMA_PAUSE ", Pause "
#define LANG_LOGIC_PROGRAM_PAUSE "Programmpause"
#define LANG_LOGIC_NEW_BODY_T_STEAM "Neue Mittellauf-T: Dampf = "
#define LANG_LOGIC_COMMA_PIPE_EQ ", Kolonne = "
#define LANG_LOGIC_BODY_T_SET_FAIL "Mittellauf-T kann nicht gesetzt werden."
#define LANG_LOGIC_BOILING_STARTED_ABV "Kochen im Kessel hat begonnen! Alkoholgehalt "
#define LANG_LOGIC_BOILING_STARTED "Kochen im Kessel hat begonnen!"
#define LANG_LOGIC_WETTING_START "Benetzung der Kolonnenfüllung begonnen. Reflux-Pegel beobachten!"
#define LANG_LOGIC_WETTING_OK "Kolonnenfüllung erfolgreich benetzt!"
#define LANG_LOGIC_WETTING_TIMEOUT "Maximale Benetzungszeit überschritten. Benetzung fehlgeschlagen — Prozess manuell stoppen."
#define LANG_LOGIC_WETTING_VOLT_RAMP_START "Allmähliche Spannungssenkung beginnt"
#define LANG_LOGIC_WETTING_VOLT_TO "Spannung wird gesenkt auf "
#define LANG_LOGIC_WETTING_MIN_VOLT "Minimale Spannung erreicht: "
#define LANG_LOGIC_WETTING_WAIT_SENSOR ". Warte auf Auslösen des Sensors."
#define LANG_LOGIC_WETTING_MIN_VOLT_TIMEOUT "Wartezeit bei Minimalspannung überschritten. Benetzung fehlgeschlagen — Prozess manuell stoppen."
#define LANG_LOGIC_WETTING_NO_SENSOR "Reflux-Pegelsensor nicht installiert, Benetzung der Füllung unmöglich"
// alarm.h
#define LANG_ALARM_SENSORS_UNASSIGNED "Sensoren nicht zugewiesen. Einstellungen öffnen und Dampf-, Wasser- und Kesselsensor zuweisen."
#define LANG_ALARM_EMERGENCY_STOP "Notabschaltung!"
#define LANG_ALARM_COOLING_HOLD_3MIN "Die Kühlung läuft noch 3 Minuten und schließt dann."
#define LANG_ALARM_EMERGENCY_STOP_TAIL "Notabschaltung"
#define LANG_ALARM_EMERGENCY_STOP_SP "Notabschaltung! "
#define LANG_ALARM_NO_SENSOR_DATA ": keine Sensordaten "
#define LANG_ALARM_RECT_SENSORS_UNASSIGNED "Notabschaltung! Rektifikation: Sensoren nicht zugewiesen"
#define LANG_ALARM_MODE_RECT "Rektifikation"
#define LANG_ALARM_SENSOR_STEAM "Dampf"
#define LANG_ALARM_SENSOR_TANK "Kessel"
#define LANG_ALARM_FLOOD_SENSOR "Flutsensor ausgelöst!"
#define LANG_ALARM_REDUCING_FROM " senke von "
#define LANG_ALARM_RAISING_TO " erhöhe auf "
#define LANG_ALARM_OVERTEMP_STEAM " Dampf"
#define LANG_ALARM_OVERTEMP_WATER " Wasser"
#define LANG_ALARM_OVERTEMP_ACP " ADR"
#define LANG_ALARM_TANK_LIMIT_FINISHED "Maximaltemperaturgrenze des Kessels. Programm beendet."
#define LANG_ALARM_TANK_LIMIT_FINISH_FAIL "Notabschaltung! Programm konnte nicht regulär nach Kesseltemperatur beendet werden"
#define LANG_ALARM_MAX_TEMP_EXCEEDED "Notabschaltung! Maximaltemperatur überschritten"
#define LANG_ALARM_WATER_CRIT_SUPPLY_ERR "Kritische Wassertemperatur! Fehler der Wasserzufuhr. "
#define LANG_ALARM_HEATUP_DONE_STAB "Aufheizen beendet. Stabilisierung/Selbstlauf."
#define LANG_ALARM_ABV "Alkoholgehalt "
#define LANG_ALARM_STAB_DONE_STABLE "Stabilisierung beendet, die Kolonne läuft stabil."
// mode_switch.h
#define LANG_MSW_I2C_MIXER_STOP "I2C-Rührwerk hat Stopp nicht bestätigt"
#define LANG_MSW_I2C_PUMP_STOP "I2C-Pumpe hat Stopp nicht bestätigt"
#define LANG_MSW_STEPPER_STOP "Schrittmotor hat nicht gestoppt"
#define LANG_MSW_VALVE_CLOSE "Ventil hat nicht geschlossen"
#define LANG_MSW_MIXER_STOP "Rührwerk hat nicht gestoppt"
#define LANG_MSW_COOLING_PUMP_STOP "Kühlpumpe hat nicht gestoppt"
#define LANG_MSW_PUMP_CAL_NOT_DONE "Pumpenkalibrierung nicht abgeschlossen"
#define LANG_MSW_HEATING_NOT_CONFIRMED "Heizung nicht bestätigt"
#define LANG_MSW_ACTUATOR_NOT_CONFIRMED "Aktor nicht bestätigt"
#define LANG_MSW_FORCE_COMPLETED "Moduswechsel erzwungen abgeschlossen: "
#define LANG_MSW_LUA_NOT_CONFIRMED "Lua nicht bestätigt"
#define LANG_MSW_QUEUE_NOT_CONFIRMED "Warteschlange nicht bestätigt"
#define LANG_MSW_PENDING_CMDS_CANCELLED "Ausstehende Steuerbefehle durch Moduswechsel abgebrochen"
#define LANG_MSW_READINESS_NOT_CONFIRMED "Bereitschaft nicht bestätigt"
#define LANG_MSW_LOG_NOT_CONFIRMED "Log nicht bestätigt"
#define LANG_MSW_POWER_TRANSITION_NOT_CONFIRMED "Leistungsübergang nicht bestätigt"
#define LANG_MSW_NBK_TRANSITION_NOT_CONFIRMED "KMK-Übergang nicht bestätigt"
#define LANG_MSW_HEATING_START_NOT_CONFIRMED "Heizungsstart nicht bestätigt"
#define LANG_MSW_SELF_TEST_NOT_CONFIRMED "Selbsttest nicht bestätigt"
#define LANG_MSW_OWNER_NOT_CONFIRMED "Modus-Besitzer nicht bestätigt"
#define LANG_MSW_LUA_NOT_RELOADED "Lua-Skript nicht neu geladen"
#define LANG_MSW_PROFILE_NOT_SAVED "Profil nicht gespeichert"
// mode_common.h
#define LANG_MCOM_SENSOR_WATER "Wasser"
#define LANG_MCOM_SENSOR_ACP "ADR"
#define LANG_MCOM_WATER_SUPPLY_STOPPED "Notabschaltung! Wasserzufuhr gestoppt."
#define LANG_MCOM_OVERTEMP_WATER " Wasser"
#define LANG_MCOM_OVERTEMP_ACP " ADR"
#define LANG_MCOM_MAX_TEMP_EXCEEDED "Notabschaltung! Maximaltemperatur überschritten"
#define LANG_MCOM_WATER_HIGH_HEAD "Hohe Wassertemperatur: "
#define LANG_MCOM_WATER_WARN_THRESHOLD "°C (Warnschwelle "
#define LANG_MCOM_CHECK_COOLING_DOT "°C). Kühlung prüfen."
#define LANG_MCOM_ACP_HIGH_HEAD "Hohe ADR-Temperatur: "
#define LANG_MCOM_ACP_THRESHOLD "°C (Schwelle "
#define LANG_MCOM_CHECK_COOLING_BANG "°C)! Kühlung prüfen."
#define LANG_MCOM_WATER_CRIT_REDUCING "Kritische Wassertemperatur! Senke "
#define LANG_MCOM_FROM " ab "
#define LANG_MCOM_LOG_BUSY_CLOSE_SKIPPED "Logdatei belegt: Schließen übersprungen"
#define LANG_MCOM_HEATING_LATCHED "Heizung durch Notfallschutz gesperrt, Neustart erforderlich"
#define LANG_MCOM_HEATING_OFF_PENDING "Heizungsabschaltung noch nicht beendet. Start abgebrochen."
#define LANG_MCOM_HEATING_NOT_RESUMED "Heizung nicht automatisch fortgesetzt. Erneuter Startbefehl erforderlich."
// mode_registry.h
#define LANG_MREG_NAME_DIST "Destillation"
#define LANG_MREG_NAME_BEER "Bier"
#define LANG_MREG_NAME_BK "MK"
#define LANG_MREG_NAME_NBK "KMK"
#define LANG_MREG_NAME_CHEESE "Käserei"
#define LANG_MREG_UNAVAILABLE_NO_REGULATOR "In diesem Firmware-Build nicht verfügbar: kein Leistungsregler"
#define LANG_MREG_UNAVAILABLE_NO_LUA "In diesem Firmware-Build nicht verfügbar: Lua nicht aktiviert"
#define LANG_MREG_START_REJECTED_SWITCH "Startbefehl abgelehnt: Moduswechsel noch nicht abgeschlossen"
#define LANG_MREG_START_UNAVAILABLE_MODE "Startbefehl im aktuellen Modus nicht verfügbar"
#define LANG_MREG_QUEUE_BUSY_START "Befehlswarteschlange belegt: Start "
#define LANG_MREG_NOT_QUEUED " nicht eingereiht"
#define LANG_MREG_STATUS_MISMATCH "Status gehört nicht zum aktuellen Modus - Takt übersprungen, Modussynchronisation prüfen"

// beer.h
#define LANG_BEER_ADD_HOPS "Hopfen zugeben!"
#define LANG_BEER_ESTOP_COOLING_OPEN "Notabschaltung! Kühlung konnte nicht geöffnet werden"
#define LANG_BEER_ESTOP_COOLING_SAFE "Notabschaltung! Kühlung konnte nicht in sicheren Zustand versetzt werden"
#define LANG_BEER_ESTOP_COOL_PUMP_ON "Notabschaltung! Kühlpumpe konnte nicht eingeschaltet werden"
#define LANG_BEER_ESTOP_COOL_PUMP_OFF "Notabschaltung! Kühlpumpe konnte nicht ausgeschaltet werden"
#define LANG_BEER_ESTOP_COOLING_RESTORE "Notabschaltung! Kühlung konnte nicht in Arbeitszustand versetzt werden"
#define LANG_BEER_ESTOP_COOLING_CLOSE "Notabschaltung! Kühlung konnte nicht geschlossen werden"
#define LANG_BEER_SENSOR_TANK "Kessel"
#define LANG_BEER_SENSOR_WATER "Wasser"
#define LANG_BEER_SENSOR_PIPE "Kolonne"
#define LANG_BEER_SENSOR_STEAM "Dampf"
#define LANG_BEER_SENSOR_ACP "ADR"
#define LANG_BEER_ERR_ROW_NOT_SET "Bier-Programmfehler: Zeile nicht gesetzt"
#define LANG_BEER_ERR_BAD_STAGE_TYPE "Programmfehler: ungültiger Phasentyp in Zeile "
#define LANG_BEER_ERR_PROGRAM_PREFIX "Programmfehler: "
#define LANG_BEER_ERR_PROGRAM "Programmfehler"
#define LANG_BEER_IN_LINE " in Zeile "
#define LANG_BEER_ERR_BAD_TEMP_SENSOR "Programmfehler: ungültiger Temperatursensor in Zeile "
#define LANG_BEER_ERR_I2C_PUMP_LINE "I2C-Pumpe nicht verfügbar in Zeile "
#define LANG_BEER_ERR_I2C_PUMP_RELAY_LINE "I2C-Pumpenrelais nicht verfügbar in Zeile "
#define LANG_BEER_ERR_I2C_MIXER_LINE "I2C-Rührwerk nicht verfügbar in Zeile "
#define LANG_BEER_MODE_NAME "Bier"
#define LANG_BEER_START_HEAT_OFF_PENDING "Heizungsabschaltung noch nicht beendet. Maischestart abgebrochen."
#define LANG_BEER_START_SAFETY_LATCH "Heizungs-Sicherheitssperre aktiv. Maischestart abgebrochen."
#define LANG_BEER_START_LOG_FILE "Fehler beim Erstellen der Logdatei. Maischestart abgebrochen."
#define LANG_BEER_START_SESSION_BUSY "Sitzungsbeschreibung belegt. Maischestart abgebrochen."
#define LANG_BEER_START_POWER_ON_FAILED "Heizungsstrom konnte nicht eingeschaltet werden. Maischestart abgebrochen."
#define LANG_BEER_WAIT_SKIP_COOL_CONFIRM "Warte auf Bestätigung zum Überspringen der Kühlung"
#define LANG_BEER_WORT_NOT_COOLED "Würze noch nicht auf Ziel abgekühlt. Wechsel innerhalb von 10 Sekunden wiederholen, um zu bestätigen."
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_NEXT "Lua-Fehler: Rührwerk vor dem Wechsel nicht ausgeschaltet"
#define LANG_BEER_LUA_STOP_LOCK_BUSY "Lua-Job nicht sofort gestoppt - Sperre belegt. Wechsel in einer Sekunde wiederholen."
#define LANG_BEER_LUA_STOP_REQUEST_FAILED "Lua-Fehler: Job-Stopp konnte nicht angefordert werden"
#define LANG_BEER_ERR_L_NEEDS_USE_LUA "Programmfehler: Typ L erfordert USE_LUA"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_START "Lua-Fehler: Rührwerk vor dem Start nicht ausgeschaltet"
#define LANG_BEER_LUA_JOB_NOT_ACCEPTED "Lua-Fehler: Job nicht zum Start angenommen"
#define LANG_BEER_MOVE_TO_LINE "Wechsel zu Programmzeile #"
#define LANG_BEER_MSG_HEAT_MALT "; Aufheizen auf Temperatur zum Malzeinfüllen: "
#define LANG_BEER_MSG_TEMP_PAUSE "; Temperaturpause: "
#define LANG_BEER_MSG_DEG_TIME "°, Zeit: "
#define LANG_BEER_MIN " min"
#define LANG_BEER_MSG_BOIL_TIME "; Kochen, Zeit: "
#define LANG_BEER_MSG_COOL_TO "; Kühlen auf Temperatur: "
#define LANG_BEER_MSG_FERMENT_HOLD "; Gärung, Temperatur halten: "
#define LANG_BEER_MSG_WAIT_MODE "; Wartemodus"
#define LANG_BEER_NEXT_LINE "Wechsel zur nächsten Zeile"
#define LANG_BEER_LUA_JOB_ACCEPTED_MSG "Lua-Job angenommen"
#define LANG_BEER_FINISH_ACTUATOR_FAILED "Fehler beim Brauende: Aktor nicht ausgeschaltet"
#define LANG_BEER_LUA_JOB_WITHOUT_USE_LUA "Lua-Fehler: Job aktiv ohne USE_LUA"
#define LANG_BEER_BREW_STOPPED_ERROR "Brauen wegen Fehler gestoppt"
#define LANG_BEER_BREW_DONE "Brauen beendet"
#define LANG_BEER_MASH_PROGRAM_DONE "Maischeprogramm beendet"
#define LANG_BEER_ESTOP_WORT_OVERTEMP "Notabschaltung! Maximale Würzetemperatur überschritten"
#define LANG_BEER_HOLD_PAUSE_BELOW_TARGET "Haltepause: Temperatur unter Ziel"
#define LANG_BEER_HOLD_RESUMED "Halten fortgesetzt"
#define LANG_BEER_MANUAL_PAUSE_ACTUATOR_FAILED "Fehler der manuellen Pause: Aktor nicht ausgeschaltet"
#define LANG_BEER_ERR_UNKNOWN_STAGE_TYPE "Programmfehler: unbekannter Phasentyp in Zeile "
#define LANG_BEER_LUA_TIMEOUT "Lua hat den Vorgang nicht vor Zeitablauf beendet"
#define LANG_BEER_LUA_MIXER_OFF_ON_STOP "Lua-Fehler: Rührwerk beim Job-Stopp nicht ausgeschaltet"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_CONFIRM "Lua-Fehler: Rührwerk vor der Job-Bestätigung nicht ausgeschaltet"
#define LANG_BEER_LUA_JOB_CONFIRMED "Lua-Job bestätigt"
#define LANG_BEER_LUA_JOB_NO_START_CONFIRM "Lua-Fehler: Job hat Start nicht bestätigt"
#define LANG_BEER_LUA_JOB_FAILED "Lua-Fehler: Job mit Fehler beendet"
#define LANG_BEER_WAIT_OPERATOR "Warte auf Bedieneraktion"
#define LANG_BEER_AUTOTUNE_QUEUE_BUSY "Befehlswarteschlange belegt: Abschluss der Bier-Autotune wird wiederholt"
#define LANG_BEER_MALT_TEMP_REACHED "Temperatur zum Malzeinfüllen erreicht!"
#define LANG_BEER_WAIT_MALT "Warte auf Malzeinfüllen"
#define LANG_BEER_TEMP_PAUSE_REACHED "Temperaturpause erreicht "
#define LANG_BEER_DEG_WAITING "°. Warte "
#define LANG_BEER_MINUTES_DOT " Minuten."
#define LANG_BEER_COOL_TIMEOUT_24H "Kessel konnte in 24 Stunden nicht auf Zieltemperatur gekühlt werden. Kesselsensor, Kühlwasserzufuhr und Kühlventil prüfen."
#define LANG_BEER_BOIL_STARTED "Kochmodus gestartet"
#define LANG_BEER_BOIL_NOT_DETECTED_120 "Kochbeginn in 120 Minuten nicht erkannt. Kesselsensor, Flüssigkeitsmenge, Deckel und Erreichbarkeit der Kochschwelle (niedriger Druck) prüfen."
#define LANG_BEER_ESTOP_MIXER_RESTORE "Notabschaltung! Rührwerkszustand konnte nicht wiederhergestellt werden"
#define LANG_BEER_PID_AUTOTUNE_NO_MEM "PID-Autotune nicht gestartet: zu wenig Speicher"
#define LANG_BEER_PID_AUTOTUNE_NOT_SAVED "PID-Autotune nicht gespeichert: "
// cheese.h
#define LANG_CHEESE_TEMP_CONFIRM_STARTED "Temperaturbestätigung gestartet"
#define LANG_CHEESE_PH_CONFIRM_STARTED "pH-Bestätigung gestartet"
#define LANG_CHEESE_ESTOP_EQUIPMENT_OFF "Notabschaltung! Käserei-Ausrüstung konnte nicht ausgeschaltet werden"
#define LANG_CHEESE_STAGE_HEAT "Heizen"
#define LANG_CHEESE_STAGE_HOLD "Halten"
#define LANG_CHEESE_STAGE_COOL "Kühlung"
#define LANG_CHEESE_STAGE_MIX "Rühren"
#define LANG_CHEESE_STAGE_DOSE "Dosieren"
#define LANG_CHEESE_STAGE_PH "Warten auf pH"
#define LANG_CHEESE_STAGE_MANUAL "Manuelle Aktion"
#define LANG_CHEESE_STAGE_DRAIN "Ablassen"
#define LANG_CHEESE_STAGE_FLOC "Flockung"
#define LANG_CHEESE_STAGE_UNKNOWN "Unbekannte Operation"
#define LANG_CHEESE_ROW "Zeile "
#define LANG_CHEESE_ERR_ROW_NOT_SET "Käse-Programmfehler: Zeile nicht gesetzt"
#define LANG_CHEESE_ERR_PROGRAM_PREFIX "Programmfehler: "
#define LANG_CHEESE_ERR_PROGRAM "Programmfehler"
#define LANG_CHEESE_IN_LINE " in Zeile "
#define LANG_CHEESE_ERR_TEMP_SENSOR_LINE "Temperatursensorfehler in Zeile "
#define LANG_CHEESE_ERR_I2C_MIXER_LINE "I2C-Rührwerk nicht verfügbar in Zeile "
#define LANG_CHEESE_ERR_LOCAL_DOSER_LINE "Lokaler Dosierer nicht verfügbar in Zeile "
#define LANG_CHEESE_ERR_I2C_PUMP_LINE "I2C-Pumpe nicht verfügbar in Zeile "
#define LANG_CHEESE_ERR_COOLING_NOT_IN_BUILD "Kühlung in diesem Build nicht verfügbar"
#define LANG_CHEESE_ERR_PH_CAL_LINE "Ungültige pH-Kalibrierung in Zeile "
#define LANG_CHEESE_ERR_LUA_NOT_IN_BUILD "Lua in diesem Build nicht verfügbar"
#define LANG_CHEESE_ERR_LUA_FILE_LINE "Lua-Datei nicht gefunden in Zeile "
#define LANG_CHEESE_LUA_JOB_ACCEPTED "Lua-Job angenommen"
#define LANG_CHEESE_NEXT_LINE "Wechsel zur nächsten Zeile"
#define LANG_CHEESE_WAIT_OPERATOR "Warte auf Bedieneraktion"
#define LANG_CHEESE_DOSER_STARTED "Dosierer gestartet"
#define LANG_CHEESE_LUA_OUTPUTS_OFF_FAILED "Lua-Fehler: Ausgänge nicht ausgeschaltet"
#define LANG_CHEESE_ERR_ROW_TRANSITION "Fehler beim Wechsel zur Käseprogrammzeile"
#define LANG_CHEESE_FLOC_RECORDED "|Flock erfasst: "
#define LANG_CHEESE_SEC_UNIT " s"
#define LANG_CHEESE_FLOC_TIMEOUT "Flockungs-Zeitüberschreitung"
#define LANG_CHEESE_CUT_AFTER_TIMEOUT "Berechneter Schnittzeitpunkt liegt nach der Flockungs-Zeitüberschreitung"
#define LANG_CHEESE_FLOC_NO_SESSION "Flockungssitzung nicht erstellt"
#define LANG_CHEESE_LUA_TIMEOUT "Lua hat den Vorgang nicht vor Zeitablauf beendet"
#define LANG_CHEESE_LUA_JOB_DONE "Lua-Job beendet"
#define LANG_CHEESE_ERR_AFTER_LUA "Fehler beim Wechsel nach Lua"
#define LANG_CHEESE_LUA_NO_NEXT_LINE "Lua endete ohne Wechsel zur nächsten Zeile"
#define LANG_CHEESE_LUA_FAILED "Lua mit Fehler beendet"
#define LANG_CHEESE_ERR_UNKNOWN_OPERATION "Programmfehler: unbekannte Operation"
#define LANG_CHEESE_MODE_NAME "Käse"
#define LANG_CHEESE_ERR_TEMP_SENSOR "Temperatursensorfehler"
#define LANG_CHEESE_ERR_MIXER "Rührwerkfehler"
#define LANG_CHEESE_OPERATION_TIMEOUT "Zeitüberschreitung der Käseprogramm-Operation"
#define LANG_CHEESE_TEMP_CONFIRMED "Temperatur bestätigt"
#define LANG_CHEESE_HOLD_RESUMED "Halten fortgesetzt"
#define LANG_CHEESE_HOLD_PAUSED_OUT_OF_BAND "Halten pausiert: Temperatur außerhalb des Bands"
#define LANG_CHEESE_HOLD_TIMEOUT "Halte-Zeitüberschreitung"
#define LANG_CHEESE_ERR_COOLING "Kühlungsfehler"
#define LANG_CHEESE_COOLING_OFF_FAILED "Kühlung konnte nicht ausgeschaltet werden"
#define LANG_CHEESE_DOSING_DONE "Dosieren beendet"
#define LANG_CHEESE_I2C_DOSING_ABORTED "Dosieren per I2C-Pumpe abgebrochen"
#define LANG_CHEESE_PH_INVALID_10S "pH 10 Sekunden unzuverlässig"
#define LANG_CHEESE_PH_CONFIRMED "pH bestätigt"
#define LANG_CHEESE_FINISH_OUTPUTS_NOT_OFF "Fehler beim Käsereiende: Ausgänge nicht ausgeschaltet"
#define LANG_CHEESE_STOPPED_ERROR "Käserei wegen Fehler gestoppt"
#define LANG_CHEESE_DONE "Käserei beendet"
#define LANG_CHEESE_PROGRAM_DONE "Käsereiprogramm beendet"
#define LANG_CHEESE_START_NO_ADS1115 "ADS1115 nicht gefunden. Käsereistart abgebrochen."
#define LANG_CHEESE_START_HEAT_UNAVAILABLE "Heizung nicht verfügbar. Käsereistart abgebrochen."
#define LANG_CHEESE_START_LOG_FILE "Fehler beim Erstellen der Logdatei. Käsereistart abgebrochen."
#define LANG_CHEESE_START_SESSION_BUSY "Sitzungsbeschreibung belegt. Käsereistart abgebrochen."
#define LANG_CHEESE_START_POWER_ON_FAILED "Heizungsstrom konnte nicht eingeschaltet werden. Käsereistart abgebrochen."
#define LANG_CHEESE_STATUS_WAITING "Warten"
#define LANG_CHEESE_STATUS_LINE "; Zeile "
// suvid.h
#define LANG_SUVID_MODE_NAME "Sous-vide"
#define LANG_SUVID_SENSOR_WATER "Wasser"
#define LANG_SUVID_SENSOR_ACP "ADR"
#define LANG_SUVID_SENSOR_TANK "Kessel"
#define LANG_SUVID_FINISHED "Sous-vide beendet"
#define LANG_SUVID_HOLD_PAUSED_OUT_OF_BAND "Halten pausiert: Temperatur außerhalb des Bands"
#define LANG_SUVID_DEVIATION_WARNING "Sous-vide: Temperatur weicht seit 60 s um mehr als 2° vom Sollwert ab."
#define LANG_SUVID_HOLD_RESUMED "Halten fortgesetzt"
#define LANG_SUVID_REACH_TIMEOUT "Sous-vide: Arbeitstemperatur in 120 Minuten nicht erreicht, Heizung wird ausgeschaltet. Heizelement, Kesselsensor und Füllmenge prüfen."
#define LANG_SUVID_HOLD_DONE "Sous-vide: Halten beendet, Heizung aus."
#define LANG_SUVID_HOLD_DONE_QUEUE_BUSY "Sous-vide: Halten beendet, reguläres Ausschalten nicht eingereiht: Befehlswarteschlange belegt."
// program_io.h
#define LANG_PROG_ERR_PROGRAM "Programmfehler"
#define LANG_PROG_LINE_OPEN " (Zeile "
#define LANG_PROG_LUA_TEXT_BAD "Lua-Text ist leer oder zu lang"
#define LANG_PROG_LUA_FILE_REQUIRED "Lua-Datei angeben; ein leeres Argument wird als «» geschrieben"
#define LANG_PROG_BEER_DEVICE_MASK "Gerät muss 0^0^0^0^0 sein oder Maske 1..3 mit Zeitplan ungleich null"
#define LANG_PROG_BEER_TYPE_MC "bei Typ M/C Temp größer 0 und Time=0"
#define LANG_PROG_BEER_TYPE_F "bei Typ F Temp größer 0"
#define LANG_PROG_BEER_TYPE_P "bei Typ P müssen Temp und Time größer 0 sein"
#define LANG_PROG_BEER_TYPE_B "bei Typ B Temp=0 und Time größer 0"
#define LANG_PROG_BEER_TYPE_W "bei Typ W Temp=0 und Time=0"
#define LANG_PROG_BEER_TYPE_L "bei Typ L Zeitlimit und Nullparameter nötig"
#define LANG_PROG_L_NEEDS_USE_LUA "Typ L erfordert USE_LUA"
#define LANG_PROG_BEER_TYPE_A "bei Typ A Temp größer 0, Time=0 und Gerät=0^0^0^0^0"
#define LANG_PROG_BEER_UNKNOWN_TYPE "unbekannter Beer-Typ"
#define LANG_PROG_L_TIMEOUT_RANGE "L braucht Zeitlimit 1..65535 Sekunden und Nullfelder"
#define LANG_PROG_SPEED_SR "bei Typ S/R muss Speed im Bereich (0,1) liegen"
#define LANG_PROG_SPEED_AP "bei Typ A/P muss Speed im Bereich [0,100) liegen"
#define LANG_PROG_SPEED_T "bei Typ T muss Speed im Bereich (0,150] liegen"
#define LANG_PROG_STEAM_TEMP_RANGE "T Dampf: 0 oder 30..100"
#define LANG_PROG_BEER_BAD_DEVICE "ungültige Beer-Gerätevorlage"
#define LANG_PROG_CHEESE_MIXER_FORM "Rührwerk muss 0^0^0^0, Relais 1^0, I2C 2 mit RPM ungleich null oder I2C mit Reversieren 3 mit RPM, ON und OFF sein"
#define LANG_PROG_CHEESE_H "H braucht Temp, Time, Heizrate und Sensor"
#define LANG_PROG_CHEESE_P "P braucht Sensor und Param nicht kleiner als Time"
#define LANG_PROG_CHEESE_C "C braucht Temp, Time, Sensor und Param=0"
#define LANG_PROG_CHEESE_M "M braucht Time, Rührwerk und Nullwerte Temp/Param/Sensor"
#define LANG_PROG_CHEESE_D "D braucht Time, Methode und Parameter für manuelles, Mengen- oder Schrittdosieren"
#define LANG_PROG_CHEESE_N "N braucht Temp, Time, pH 0..14 und Sensor"
#define LANG_PROG_CHEESE_F "F braucht Temp, Time, Faktor nicht kleiner 1 und Sensor"
#define LANG_PROG_CHEESE_W "W braucht Time, Aktionscode 1..8 und TempSensor=0"
#define LANG_PROG_CHEESE_S "S braucht sichere Ausgänge, Time und Nullfelder"
#define LANG_PROG_CHEESE_L "L braucht sichere Ausgänge, Time und Nullfelder"
#define LANG_PROG_CHEESE_UNKNOWN_TYPE "unbekannter Cheese-Typ"
#define LANG_PROG_CHEESE_F_MULT "F-Faktor nicht darstellbar als m=round(MULTIPLIER*1000)"
#define LANG_PROG_CHEESE_BAD_DEVICE "ungültige Cheese-Gerätevorlage"
#define LANG_PROG_EMPTY_USE_CLEAR "Leeres Programm: explizites Löschen verwenden"
#define LANG_PROG_RECT_LINE_TOO_LONG "Zeile zu lang (rect)"
#define LANG_PROG_RECT_BAD_FORMAT "ungültiges Zeilenformat rect"
#define LANG_PROG_RECT_TOO_MANY "zu viele rect-Zeilen"
#define LANG_PROG_DIST_LINE_TOO_LONG "Zeile zu lang (dist)"
#define LANG_PROG_DIST_BAD_FORMAT "ungültiges Zeilenformat dist"
#define LANG_PROG_DIST_TOO_MANY "zu viele dist-Zeilen"
#define LANG_PROG_BK_LINE_TOO_LONG "Zeile zu lang (bk)"
#define LANG_PROG_BK_BAD_FORMAT "ungültiges Zeilenformat bk"
#define LANG_PROG_BK_TOO_MANY "zu viele bk-Zeilen"
#define LANG_PROG_BEER_LINE_TOO_LONG "Zeile zu lang (beer)"
#define LANG_PROG_BEER_BAD_FORMAT "ungültiges Zeilenformat beer"
#define LANG_PROG_BEER_TOO_MANY "zu viele beer-Zeilen"
#define LANG_PROG_NBK_LINE_TOO_LONG "Zeile zu lang (nbk)"
#define LANG_PROG_NBK_BAD_FORMAT "ungültiges Zeilenformat nbk"
#define LANG_PROG_NBK_TOO_MANY "zu viele nbk-Zeilen"
#define LANG_PROG_CHEESE_LINE_TOO_LONG "Zeile zu lang (cheese)"
#define LANG_PROG_CHEESE_BAD_FORMAT "ungültiges Zeilenformat cheese"
#define LANG_PROG_CHEESE_TOO_MANY "zu viele cheese-Zeilen"
#define LANG_PROG_NBK_FOUR_ROWS "KMK muss 4 Zeilen H/S/O/W enthalten"
#define LANG_PROG_UNSUPPORTED_MODE "nicht unterstützter Modus"
#define LANG_PROG_FIRST_ROW_ABSOLUTE "die erste Zeile muss absolute Leistung/Spannung setzen (sonst bleibt die Kolonne auf voller Aufheizleistung)"
#define LANG_PROG_FIRST_NONZERO_ABSOLUTE "die erste Zeile mit Spannung/Leistung ungleich null muss einen Absolutwert setzen, keine Korrektur (sonst kann die Heizung beim Aufheizen unbemerkt ausgehen)"

// Samovar.ino
// Заголовок уровня V26/push: в любом языке, кроме русского, - только знак ⛔/⚠ (PIN_SPEC.md §6).
#define LANG_MAIN_V26_ALARM_HEADER "⛔ "
#define LANG_MAIN_V26_WARNING_HEADER "⚠ "
#define LANG_MAIN_ASSERT_BLYNK_TIMEOUT "BLYNK_TIMEOUT_MS aus Samovar.h wirkungslos: BlynkConfig.h wird früher eingebunden"
#define LANG_MAIN_ASSERT_BLYNK_SENDBYTES "BLYNK_MAX_SENDBYTES aus Samovar.h wirkungslos: BlynkConfig.h wird früher eingebunden"
#define LANG_MAIN_ASSERT_BLYNK_MSG_LIMIT "BLYNK_MSG_LIMIT aus Samovar.h wirkungslos: BlynkConfig.h wird früher eingebunden"
#define LANG_MAIN_ERR_SENSOR_STEAM "Fehler des Dampftemperatursensors!"
#define LANG_MAIN_ERR_SENSOR_PIPE "Fehler des Kolonnentemperatursensors!"
#define LANG_MAIN_ERR_SENSOR_WATER "Fehler des Wassertemperatursensors!"
#define LANG_MAIN_ERR_SENSOR_TANK "Fehler des Kesseltemperatursensors!"
#define LANG_MAIN_ERR_SENSOR_ACP "Fehler des ADR-Temperatursensors!"
#define LANG_MAIN_PROG_UNCHANGED_ALL_DONE "Programm nicht geändert: alle Zeilen sind bereits erledigt."
#define LANG_MAIN_PROG_UNCHANGED_LINE "Programm nicht geändert: Zeile "
#define LANG_MAIN_PROG_LINE_LOCKED " kann nicht mehr geändert werden: sie läuft oder ist erledigt."
#define LANG_MAIN_PROFILE_OP_CANCELLED_BUSY "Profiloperation abgebrochen: Laufzeitzustand belegt."
#define LANG_MAIN_NBK_PROG_NOT_SAVED "KMK-Programm nicht gespeichert: "
#define LANG_MAIN_MODE_SWITCHED_NOT_SAVED "Modus gewechselt, aber nicht gespeichert, nach Neustart gilt der alte: "
#define LANG_MAIN_SETTINGS_NOT_SAVED "Einstellungen nicht gespeichert: "
#define LANG_MAIN_PROFILE_OP_TERMINAL_NOT_PUBLISHED "Profiloperation: Endzustand nicht veröffentlicht; Neustart erforderlich."
#define LANG_MAIN_PROFILE_OP_RECORD_UNAVAILABLE "Profiloperation: Eintrag beim Start nicht verfügbar; Neustart erforderlich."
#define LANG_MAIN_EMERGENCY_BUTTON_TRIGGERED "Notabschaltung! Eingang der Notfalltaste ausgelöst (Taste oder daran angeschlossener Sensor)."
#define LANG_MAIN_ACP_TEMP_LABEL " ADR-Temperatur "
#define LANG_MAIN_PRESSURE_LIMIT_EXCEEDED "Druckgrenze überschritten!"
#define LANG_MAIN_SENSOR_SCAN_REJECTED "Sensorsuche abgelehnt: Prozess aktiv."
#define LANG_MAIN_UNFINISHED_SESSION_MODE "Unfertige Sitzung erkannt, Modus "
#define LANG_MAIN_PROGRAM_NUM ", Programm #"
#define LANG_MAIN_HEATING_NOT_RESUMED_AUTO "; Heizung NICHT automatisch fortgesetzt."
#define LANG_MAIN_NBK_PROG_LEN_BAD_NVS "Ungültige KMK-Programmlänge im NVS"
#define LANG_MAIN_SESSION_INTERRUPTED_LINE "Sitzung durch Neustart unterbrochen: Zeile "
#define LANG_MAIN_PROGRAM_RESTORED ", Programm wiederhergestellt"
#define LANG_MAIN_PROGRAM_NOT_RESTORED ", Programm nicht wiederhergestellt"
#define LANG_MAIN_HEATING_NOT_RESUMED ". Heizung nicht fortgesetzt."
#define LANG_MAIN_SUVID_HOLD_AT_FAILURE " Aufgelaufene Sous-vide-Haltezeit zum Ausfallzeitpunkt: "
#define LANG_MAIN_CHEESE_SNAPSHOT_CLEARED "Käse-Programm aus Abbild nicht wiederhergestellt und gelöscht. Standardprogramm nicht gesetzt."
#define LANG_MAIN_SNAPSHOT_DEFAULT_SET "Programm aus Abbild nicht wiederhergestellt, Standardprogramm gesetzt."
#define LANG_MAIN_REASON_LABEL " Grund: "
#define LANG_MAIN_EMERGENCY_BUTTON_TASK_NOT_STARTED "Notabschaltung! Notfalltasten-Task nicht gestartet"
#define LANG_MAIN_BOOT_WITH_ERRORS "Start mit Fehlern ("
#define LANG_MAIN_BOOT_LIMITED_MODE "). Einige Funktionen nicht verfügbar, eingeschränkter Betrieb."
#define LANG_MAIN_EMERGENCY_LOCKOUT "Notfallsperre: "
#define LANG_MAIN_EMERGENCY_LOCKOUT_NBK_NVS "Notfallsperre: KMK-Programm im NVS beschädigt: "
#define LANG_MAIN_EMERGENCY_REGULATOR_TASK_NOT_STARTED "Notabschaltung! Regler-Task nicht gestartet"
#define LANG_MAIN_EMERGENCY_STACK_LOW "Notabschaltung! Kritisch wenig Stack übrig"
#define LANG_MAIN_STACK_OVERFLOW_REBOOT "Stack übergelaufen. Neustart"
#define LANG_MAIN_EMERGENCY_TASK_STACK_LOW "Notabschaltung! Kritisch wenig Stack übrig für Task "
#define LANG_MAIN_TASK_STACK_LABEL "Stack des Tasks "
#define LANG_MAIN_TASK_STACK_OVERFLOW_REBOOT " übergelaufen. Neustart"
#define LANG_MAIN_EMERGENCY_SYSTICKER_HUNG "Notabschaltung! Überwachungs-Task SysTicker hängt"
#define LANG_MAIN_SYSTICKER_HUNG_REBOOT "Überwachungs-Task SysTicker hängt. Neustart"
#define LANG_MAIN_OP_EXPIRED_FORCED "Abgelaufene Operation zwangsweise beendet (reaper)"
#define LANG_MAIN_MIXER_CMD_FAILED "Rührwerkbefehl fehlgeschlagen: Aktor hat Zustand nicht bestätigt"
#define LANG_MAIN_NBK_MANUAL_UNAVAILABLE "Manuelle Steuerung in Optimierung und KMK-Arbeit nicht verfügbar."
#define LANG_MAIN_NBK_BUTTON_ONLY_MANUAL_WORK "Taste nur bei manueller Einstellung und in KMK-Arbeit verfügbar."
#define LANG_MAIN_OPTIMAL_VALUES_SET "Optimale Werte gesetzt: "
#define LANG_MAIN_UNIT_LPH " l/h"
#define LANG_MAIN_NBK_CMD_PUMP_UNAVAILABLE "KMK-Befehl abgelehnt: gewählte I2C-Pumpe nicht verfügbar."
#define LANG_MAIN_NBK_CMD_BAD_SPEED_CAL "KMK-Befehl abgelehnt: ungültige Geschwindigkeitskalibrierung."
#define LANG_MAIN_NBK_START_NO_REGULATOR "KMK-Start abgelehnt: Leistungsregler in diesem Build nicht verfügbar."
#define LANG_MAIN_MANUAL_TAKEOFF_PAUSE "Manuelle Abnahmepause"
#define LANG_MAIN_MODE_FROM_SETTINGS_NOT_ACTIVATED "Modus aus Einstellungen nicht aktiviert: "
#define LANG_MAIN_UNAVAILABLE_IN_BUILD "in diesem Firmware-Build nicht verfügbar"
#define LANG_MAIN_CHEESE_FACT_QUEUE_OVERFLOW "F1: Faktenwarteschlange übergelaufen, Käseprogramm gestoppt"
#define LANG_MAIN_CHEESE_FLOCCULATION_SAVE_FAILED "Flockungsfakt konnte nicht gespeichert werden"
// power_regulator.h
#define LANG_PWR_QUEUE_BUSY_RESET_AFTER_OFF "Befehlswarteschlange belegt: Reset nach Heizung aus nicht eingereiht"
#define LANG_PWR_HEAT_REJECTED_TASK_NOT_STARTED "Heizung abgelehnt: Regler-Task nicht gestartet"
#define LANG_PWR_HEAT_BLOCKED_EMERGENCY "Heizung durch Notfallschutz gesperrt, Neustart erforderlich"
#define LANG_PWR_HEAT_REJECTED_OFF_IN_PROGRESS "Heizung abgelehnt: Heizung wird gerade ausgeschaltet, später erneut versuchen"
#define LANG_PWR_HEAT_REJECTED_EXCLUSIVE_OP "Heizung abgelehnt: exklusive Operation aktiv (Selbsttest/Kalibrierung)"
#define LANG_PWR_HEAT_REJECTED_MODE_SWITCH "Heizung abgelehnt: Moduswechsel läuft"
#define LANG_PWR_HEAT_REJECTED_START_PENDING "Heizung abgelehnt: Einschaltbefehl läuft bereits, später erneut versuchen"
#define LANG_PWR_CMD_TIMEOUT_HEAT_OFF "Zeitüberschreitung des Reglerbefehls; Heizung aus"
#define LANG_PWR_START_CMD_FAILED "Reglerstartbefehl fehlgeschlagen"
#define LANG_PWR_START_CMD_TIMEOUT_HEAT_OFF "Zeitüberschreitung des Reglerstartbefehls; Heizung aus"
#define LANG_PWR_START_CMD_SUPERSEDED "Reglerstartbefehl wurde durch neuen Befehl explizit abgebrochen"
#define LANG_PWR_SESSION_ABORTED_REGULATOR_FAILURE "Sitzung abgebrochen: Ausfall des Heizungsreglers. Neustart erforderlich."
#define LANG_PWR_CMD_TIMEOUT_AT_HEAT_OFF "Zeitüberschreitung des Reglerbefehls beim Ausschalten der Heizung"
#define LANG_PWR_OFF_CMD_FAILED "Regler-Ausschaltbefehl fehlgeschlagen"
#define LANG_PWR_OFF_CMD_TIMEOUT "Zeitüberschreitung des Regler-Ausschaltbefehls"
#define LANG_PWR_OFF_CMD_SUPERSEDED "Regler-Ausschaltbefehl wurde durch neuen Befehl explizit abgebrochen"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_OFF "Zeitüberschreitung des Reglerbefehls bei abgeschalteten lokalen Relais"
#define LANG_PWR_NO_REGULATOR_LINK "Keine Verbindung zum Regler!"
#define LANG_PWR_EMERGENCY_NO_REGULATOR_LINK "Notabschaltung! Keine Verbindung zum Heizungsregler."
#define LANG_PWR_EMERGENCY_HEATER_CONTROL "Notabschaltung! Fehler der Heizelement-Steuerung."
#define LANG_PWR_UNKNOWN_REGULATOR_MODE "Unbekannter Reglermodus: "
#define LANG_PWR_START_REJECTED_SAFETY_BARRIER "Reglerstartbefehl von safety-barrier abgelehnt"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_RELEASED "Zeitüberschreitung des Reglerbefehls; lokale Relais aus"
#define LANG_PWR_BG_APPLY_TIMEOUT "Zeitüberschreitung beim Hintergrund-Anwenden des Reglerbefehls"
#define LANG_PWR_BG_APPLY_FAILED "Hintergrund-Anwenden des Reglerbefehls fehlgeschlagen"
// crash_handler.ino
#define LANG_CRASH_RST_UNKNOWN "Unbekannter Neustartgrund (0)"
#define LANG_CRASH_RST_POWERON "Neustart durch Einschalten der Versorgung (1)"
#define LANG_CRASH_RST_EXT "Externer Reset über RESET-Pin (2)"
#define LANG_CRASH_RST_SW "Software-Reset durch esp_restart() (3)"
#define LANG_CRASH_RST_PANIC "Reset wegen Panik oder unbehandelter Ausnahme (4)"
#define LANG_CRASH_RST_INT_WDT "Reset durch internen Watchdog (5)"
#define LANG_CRASH_RST_TASK_WDT "Reset durch Task-Watchdog (6)"
#define LANG_CRASH_RST_WDT "Reset durch einen beliebigen Watchdog (7)"
#define LANG_CRASH_RST_DEEPSLEEP "Reset nach Verlassen des Deep-Sleep (8)"
#define LANG_CRASH_RST_BROWNOUT "Reset wegen Unterspannung (9)"
#define LANG_CRASH_RST_SDIO "Reset wegen SDIO-Fehler (10)"
#define LANG_CRASH_RST_UNKNOWN_CODE "Unbekannter Grundcode: "
#define LANG_CRASH_EMERGENCY_REBOOT "Notfall-Neustart"
// WebServer.ino
#define LANG_WEB_STALE_SETTINGS "Einstellungen wurden am Gerät selbst geändert. Seite aktualisieren und wiederholen."
#define LANG_WEB_ADS1115_PH_BLOCKED "ADS1115 nicht verfügbar: pH-Kalibrierung gesperrt"
#define LANG_WEB_MODE_UNAVAILABLE_IN_BUILD "Modus in diesem Firmware-Build nicht verfügbar"
#define LANG_WEB_INVALID_REQUEST_PARAM "Ungültiger Anfrageparameter"
#define LANG_WEB_PARAMS_MUST_BE_UNIQUE "Numerische und Textparameter müssen eindeutig sein"
#define LANG_WEB_WPROGRAM_MUST_BE_TEXT "WProgram muss ein Textparameter sein"
#define LANG_WEB_CLEAR_REQUIRES_CLEAR1 "Programm löschen erfordert genau clear=1"
#define LANG_WEB_CLEAR_MUST_BE_SEPARATE "Programm löschen muss eine separate Aktion sein"
#define LANG_WEB_DESCR_INVALID "Beschreibung ungültig"
#define LANG_WEB_DESCR_TOO_LONG "Beschreibung länger als 250 Byte"
#define LANG_WEB_UPDATE_CANCELLED_LOW_SPACE "Web-Oberflächen-Update abgebrochen: wenig Speicherplatz"
#define LANG_WEB_UPDATE_INCOMPLETE "Web-Oberflächen-Update nicht abgeschlossen, Version unverändert"
// Blynk.ino
// Подписи V21 без цифр: приложения берут первое число строки (PIN_SPEC.md §2).
#define LANG_BLYNK_V21_CURRENT "Ist:"
#define LANG_BLYNK_V21_TARGET " Soll:"
#define LANG_BLYNK_QUEUE_BUSY_V12 "Befehlswarteschlange belegt: Blynk-V12-Befehl nicht eingereiht"
#define LANG_BLYNK_QUEUE_BUSY_RESET "Befehlswarteschlange belegt: Reset aus Blynk nicht eingereiht"
#define LANG_BLYNK_QUEUE_BUSY_V4 "Befehlswarteschlange belegt: Blynk-V4-Befehl nicht eingereiht"
#define LANG_BLYNK_V34_LINE_BEGIN "V34: Logzeile ("
#define LANG_BLYNK_V34_BYTES_NO_FIT " Byte) passt nicht in den Puffer ("
#define LANG_BLYNK_V34_NOT_SENT "), nicht gesendet"
#define LANG_BLYNK_V35_TRUNCATED_FROM "V35: Sitzungsbeschreibung gekürzt von "
#define LANG_BLYNK_V35_TO " auf "
#define LANG_BLYNK_V35_BYTES_BUFFER " Byte (Puffer "
// lua.h
#define LANG_LUA_CHUNK_TIMEOUT "Lua: Ausführung des Chunks per Zeitlimit abgebrochen"
#define LANG_LUA_SENSOR_WATER "Wasser"
#define LANG_LUA_SENSOR_ACP "ADR"
#define LANG_LUA_SENSOR_TANK "Kessel"
#define LANG_LUA_SCRIPT1_STOPPED_AFTER "script.lua gestoppt nach "
#define LANG_LUA_ERRORS_IN_ROW_SEE_ERR " Fehlern in Folge, siehe vorherige ERR"
#define LANG_LUA_SCRIPT1_DISABLED "Gemeinsames Skript script.lua nach wiederholten Fehlern deaktiviert"
#define LANG_LUA_MODE_SCRIPT_BEGIN "Modusskript ("
#define LANG_LUA_MODE_SCRIPT_STOPPED_AFTER ") gestoppt nach "
// Menu.ino
#define LANG_MENU_SETTINGS_NOT_SAVED "Menü-Einstellungen nicht gespeichert: "
#define LANG_MENU_QUEUE_BUSY_START "Befehlswarteschlange belegt: Start aus Menü nicht eingereiht"
#define LANG_MENU_LOG_CREATE_FAILED "Fehler beim Erstellen der Logdatei. Rektifikationsstart abgebrochen."
#define LANG_MENU_DESCR_BUSY "Sitzungsbeschreibung belegt. Rektifikationsstart abgebrochen."
#define LANG_MENU_LAST_LINE_FINISH "Abschluss der letzten Zeile"
#define LANG_MENU_PROGRAM_DONE_SELF_RUN "Programm beendet. Selbstlauf ("
#define LANG_MENU_MIN_TO_AUTO_OFF " min bis zur automatischen Abschaltung)."
#define LANG_MENU_STOPPED_BY_USER "Vom Benutzer gestoppt"
#define LANG_MENU_LUA_STOP_FAILED "Lua konnte nicht gestoppt werden: Laufzeitsperre belegt."
#define LANG_MENU_RESET_STOP_UNCONFIRMED "Prozess durch Reset gestoppt: Abschluss nicht bestätigt"
// impurity_detector.h
#define LANG_DET_LINE_NUM "Zeile #"
#define LANG_DET_STOP_PAUSES_RATE_CUT " Stopp-Pausen in Folge. Basis-Abnahmerate gesenkt auf "
#define LANG_DET_UNIT_LPH_DOT " l/h."
#define LANG_DET_PAUSE_TYPE_BUSY "Detektor: Typ der Autopause belegt. Prüfung übersprungen."
#define LANG_DET_PAUSE_TYPE_SET_FAILED "Detektor: Pausentyp konnte nicht gesetzt werden."
#define LANG_DET_PAUSE_CRITICAL_TREND "Abnahmepause: kritischer Trend"
#define LANG_DET_CRITICAL_TREND_PAUSE "Detektor: Kritischer Trend! Abnahmepause. (Trend: "
#define LANG_DET_NEW_BODY_T "Detektor: Neue Mittellauf-T wird gesetzt (erstes Mittellaufprogramm, Trend "
#define LANG_DET_RATE_REDUCTION "Detektor: Ratensenkung (Trend "
#define LANG_DET_THRESHOLD ", Schwelle: "
// FS.ino
#define LANG_FS_MOUNT_FAILED_FORMATTING "Dateisystem nicht eingebunden, wird formatiert..."
#define LANG_FS_FORMAT_FAILED "Dateisystem konnte nicht formatiert werden, Oberfläche über Arduino hochladen"
#define LANG_FS_ERROR_UPLOAD "Dateisystemfehler! Über Arduino hochladen"
#define LANG_FS_LOW_MEMORY_TOTAL "Speicher wird knapp! Gesamt: "
#define LANG_FS_USED ", belegt: "
// Samovar.h
#define LANG_SAMH_ASSERT_WPROGRAM_SIZE "WProgram: unerwartete Strukturgröße - Feldreihenfolge und Ausrichtung prüfen"
#define LANG_SAMH_PWR_MSG_POWER "Leistung"
#define LANG_SAMH_PWR_SIGN_W "W"
#define LANG_SAMH_PWR_MSG_VOLTAGE "Spannung"
#define LANG_SAMH_PWR_SIGN_V "V"
// runtime_helpers.h
#define LANG_RT_WAIT_STEAM "(Dampf)"
#define LANG_RT_WAIT_PIPE "(Kolonne)"
#define LANG_RT_WAIT_DETECTOR "(Detektor)"
#define LANG_RT_EVENT_RING_REINIT "Ereignisprotokoll nach Beschädigung neu initialisiert"
// valve_buzzer.h
#define LANG_VALVE_OPEN_WATER_SUPPLY "Wasserzufuhr öffnen!"
#define LANG_VALVE_COOLING_OPENED "Kühlwasserventil geöffnet!"
#define LANG_VALVE_CLOSE_WATER_SUPPLY "Wasserzufuhr schließen!"
#define LANG_VALVE_COOLING_CLOSED "Kühlwasserventil geschlossen!"
// selftest.h
#define LANG_SELF_FINISHED "Selbsttest beendet."
#define LANG_SELF_REJECTED "Selbsttest abgelehnt: Prozess oder Moduswechsel aktiv"
#define LANG_SELF_STARTING "Selbsttest wird gestartet."
// sensorinit.h
#define LANG_SENS_UNSUPPORTED_DEFAULT_MODE "nicht unterstützter Modus des Standardprogramms"
#define LANG_SENS_LUA_STATUS_RESET_FAILED "Lua_status konnte nicht zurückgesetzt werden: Laufzeitsperre belegt."
#define LANG_SENS_LOG_BUSY_CLOSE_SKIPPED "Logdatei belegt: Schließen übersprungen"
// I2CStepper.h
#define LANG_I2C_LINK_LOST "Verbindung zum I2C-Stepper verloren, Adresse "
#define LANG_I2C_LOCAL_STOP "Lokaler Stopp des I2C-Steppers, Adresse "
// SPIFFSEditor.h
#define LANG_EDIT_JSON_ESCAPE_TRUNCATED "spiffsEditorJsonEscape: Zeichenkette gekürzt, zu wenig Speicher"
// string_utils.h
#define LANG_STR_JSON_STRING_TRUNCATED "toJsonString: Zeichenkette gekürzt, zu wenig Speicher"
