#pragma once
// Китайский перевод прошивки. Правила (проверяет tools/smoke_i18n_firmware.py):
//  - по одной строке #define LANG_<KEY> "text" на каждый ключ TR(KEY, "...") из кода;
//    полнота: нет ключа - ошибка компиляции, лишних ключей быть не должно;
//  - в переводе нет кириллицы;
//  - набор printf-спецификаторов (%d %s %.1f ...) совпадает с русским по порядку;
//  - длина перевода в байтах UTF-8 не больше русской (буферы рассчитаны на русский);
//  - секции ключей идут по файлам с комментарием // <имя файла>.
#define SAMOVAR_LANG_NAME "中文"

// nbk.h
#define LANG_NBK_WASH_PROCESSED "已处理醪液 "
#define LANG_NBK_UNIT_L_SP " l "
#define LANG_NBK_CFG_COLUMN_INERTIA "塔惯性 In"
#define LANG_NBK_CFG_DELTA_T "dT 修正"
#define LANG_NBK_CFG_TANK_TEMP "釜温度 Tn"
#define LANG_NBK_CFG_FLOOD_PRESSURE "液泛压力 PS"
#define LANG_NBK_CFG_POWER_STEP "功率步长 dM"
#define LANG_NBK_CFG_FEED_STEP "进料步长 dP"
#define LANG_NBK_CFG_STEAM_LIMIT "蒸汽温度上限 Tp"
#define LANG_NBK_CFG_MAINS_INPUT_INVALID "电网电压(输入无法识别)"
#define LANG_NBK_CFG_HEATER_INPUT_INVALID "加热器电阻(输入无法识别)"
#define LANG_NBK_CFG_MAINS_RANGE "电网电压超出范围"
#define LANG_NBK_CFG_HEATER_RANGE "加热器电阻超出范围"
#define LANG_NBK_CEILING_LOWERED_TO "压力上限已降至 "
#define LANG_NBK_MM_FLOODING_AT " mm(液泛压力 "
#define LANG_NBK_MM_CLOSE " mm)"
#define LANG_NBK_SRC_FLOOD_SENSOR "FS"
#define LANG_NBK_SRC_NO_PRESSURE_DATA "无 PS 数据"
#define LANG_NBK_SRC_PRESSURE_SENSOR "PS"
#define LANG_NBK_HEATUP_ACTUATORS_NOT_CONFIRMED "连续醪塔升温未确认执行器指令."
#define LANG_NBK_SAFE_WAIT "连续醪塔安全等待."
#define LANG_NBK_ACTUATOR_CONFIRM_TIMEOUT "连续醪塔执行器确认超时. 安全等待."
#define LANG_NBK_ACTUATOR_CMD_HEATING_OFF "加热关闭时连续醪塔执行器指令被拒绝."
#define LANG_NBK_REGULATOR_NOT_CONFIRMED "调压器未确认连续醪塔指令. 安全等待."
#define LANG_NBK_PUMP_NOT_CONFIRMED "连续醪塔泵未确认指令. 加热已关闭."
#define LANG_NBK_WORK_RESUMED "连续醪塔工作已恢复."
#define LANG_NBK_WARMUP_POWER_FEED_SET "连续醪塔预热功率和进料已设置."
#define LANG_NBK_MODE_NAME "CBC"
#define LANG_NBK_SENSOR_VAPOR "蒸汽"
#define LANG_NBK_SENSOR_BOILER "釜"
#define LANG_NBK_RESTART_IMPOSSIBLE "连续醪塔无法重启: "
#define LANG_NBK_HEATING_NOT_OFF_YET "加热尚未关闭"
#define LANG_NBK_PUMP_STOP_NOT_CONFIRMED "泵未确认停止"
#define LANG_NBK_SESSION_CONFIG_NOT_CAPTURED "连续醪塔会话配置未保存."
#define LANG_NBK_PROGRAM_LINE_OUT_OF_RANGE "连续醪塔程序错误: 行号超出范围"
#define LANG_NBK_PROGRAM_LINE_NOT_SET "连续醪塔程序错误: 未设置程序行"
#define LANG_NBK_WARMUP_TOO_HIGH_PREFIX "预热阶段设置值过大: "
#define LANG_NBK_AND_OR_FEED_PROGRAM_STOP " 和/或进料! 程序已停止."
#define LANG_NBK_AFTER_FLOOD_REDUCE_REJECTED "液泛后连续醪塔执行器降低未被接受."
#define LANG_NBK_FLOODING_BY "液泛来源: "
#define LANG_NBK_FEED_THIRD_POWER_HALF ". 进料降至 1/3, 功率降至 1/2."
#define LANG_NBK_BEFORE_OPT_SETUP_PREFIX "优化开始前, 设置阶段给定的 "
#define LANG_NBK_AND_FEED_TOO_HIGH_STOP " 和进料过大. 已停止."
#define LANG_NBK_MANUAL_WORK_WAIT_PREFIX "等待手动转入工作阶段时, 给定的 "
#define LANG_NBK_OPT_INITIAL_REJECTED "连续醪塔优化初始参数未被接受."
#define LANG_NBK_OPT_ACCEPTED_FROM "优化已采用: "
#define LANG_NBK_UNIT_LPH_SP " l/h "
#define LANG_NBK_SET_PARAMS_PREFIX "给定的参数 "
#define LANG_NBK_AND_SPEED_TOO_HIGH_OPT_STOP " 和速度过大, 无法优化. 已停止."
#define LANG_NBK_TN_REFINED_BY_SENSOR "基准 Tn 已按醪渣传感器修正: "
#define LANG_NBK_OPT_NO_FLOOD_SENSOR "无法优化: 缺少液泛传感器. 请在工作阶段程序中手动设置所需参数, 然后按下一程序按钮. 10 min 后流程将转入安全等待(加热和进料关闭)."
#define LANG_NBK_C_IN_SETTINGS " °C(设置中 "
#define LANG_NBK_FEED_LIMIT_REACHED "已达进料上限("
#define LANG_NBK_LPH_RESULT_COLON " l/h). 结果: "
#define LANG_NBK_OPT_TB_GE_TN "优化: Tb >= Tn("
#define LANG_NBK_INCREASING_FEED_ITER "), 增加进料. 迭代 "
#define LANG_NBK_POWER_LIMIT_REACHED "已达功率上限.("
#define LANG_NBK_W_RESULT_COLON " W.). 结果: "
#define LANG_NBK_UNIT_LPH_DOT " l/h."
#define LANG_NBK_OPT_NOT_FOUND_TB_TN "未找到最优值: Tb 未达到 Tn("
#define LANG_NBK_NO_ITERATION_CHECK_TB "), 所有迭代均如此. 请检查 Tb 传感器."
#define LANG_NBK_OPT_TP_LT_TPMIN "优化: Tp < Tp min("
#define LANG_NBK_INCREASING "), 增加 "
#define LANG_NBK_ITERATION_SP ". 迭代 "
#define LANG_NBK_OPT_TB_LT_TN "优化: Tb < Tn("
#define LANG_NBK_OPT_CORRECTION_REJECTED "连续醪塔优化修正未被接受."
#define LANG_NBK_ITER_LIMIT_RESULT "已达迭代上限. 结果: "
#define LANG_NBK_UNIT_LPH " l/h"
#define LANG_NBK_TEMP_REDUCE_FEED_HEATING "临时降低进料和加热."
#define LANG_NBK_WORK_WASH_SPILL "工作: 醪液溢出(Tb "
#define LANG_NBK_FEED_REDUCED_BY "), 进料降低 "
#define LANG_NBK_TO_COLON ", 至: "
#define LANG_NBK_WORK_TB_LT_TN_DT "工作: Tb < Tn-dT("
#define LANG_NBK_REDUCING_FEED_BY "), 降低进料 "
#define LANG_NBK_WORK_TP_BELOW_LIMIT "工作: Tp 低于下限("
#define LANG_NBK_WORK_PRESSURE "工作: 压力 "
#define LANG_NBK_GE_CEILING " ≥ 上限 "
#define LANG_NBK_MM_REDUCING_FEED_BY " mm, 降低进料 "
#define LANG_NBK_WORK_TB_GT_TN_DT "工作: Tb > Tn+dT("
#define LANG_NBK_INCREASING_FEED_BY "), 增加进料 "
#define LANG_NBK_WORK_CORRECTION_REJECTED "连续醪塔工作修正未被接受."
#define LANG_NBK_REPEAT_FLOODING_BY "再次液泛, 来源: "
#define LANG_NBK_DURING_PAUSE_EXTENDED " 发生于暂停期间. 暂停已延长, 功率减半."
#define LANG_NBK_REPEAT_POWER_REDUCE_REJECTED "连续醪塔再次降功率未被接受."
#define LANG_NBK_WORK_RESUME_REJECTED "连续醪塔工作恢复未被接受."
#define LANG_NBK_WORK_RESUME_AFTER_FLOOD "工作: 液泛后恢复, 修正后的参数: "
#define LANG_NBK_WORK_CONTINUE_AFTER_PAUSE "工作: 暂停后继续循环."
#define LANG_NBK_RESUME_IMPOSSIBLE_EMERGENCY "无法恢复连续醪塔工作: 已锁定紧急状态."
#define LANG_NBK_RESUME_IMPOSSIBLE_NO_SNAPSHOT "无法恢复连续醪塔工作: 无会话配置快照."
#define LANG_NBK_RESUME_REJECTED_CMD_BUSY "连续醪塔工作恢复被拒绝: 上一条执行器指令仍在执行."
#define LANG_NBK_WORK_WAITS_HEATING_OFF "连续醪塔工作正在等待加热关闭完成."
#define LANG_NBK_RESUME_UNAVAILABLE_PUMP_STOP "无法恢复连续醪塔工作: 泵停止未被确认."
#define LANG_NBK_HEATING_NOT_ON_RESUME "尝试恢复工作时连续醪塔加热未开启."
#define LANG_NBK_RESUME_PARAMS_REJECTED "连续醪塔工作恢复: 执行器未接受参数."
#define LANG_NBK_WORK_RESUMED_M "连续醪塔工作已恢复: M="
#define LANG_NBK_COMMA_P ", P="
#define LANG_NBK_START_REJECTED_NO_REGULATOR "连续醪塔启动被拒绝: 此版本中调压器不可用."
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_NO_REGULATOR "不可用配置下连续醪塔泵停止未被确认."
#define LANG_NBK_LINE_SWITCH_HEATING_STARTING "连续醪塔换行被拒绝: 加热启动尚未完成"
#define LANG_NBK_PROGRAM_NOT_SET "未设置连续醪塔程序"
#define LANG_NBK_GOTO_WORK_NO_SNAPSHOT "转入连续醪塔工作被拒绝: 无会话配置快照."
#define LANG_NBK_AUTO_WORK_IMPOSSIBLE "无法自动转入连续醪塔工作: 加热已关闭或未找到最优值."
#define LANG_NBK_AUTO_WORK_PARAMS_REJECTED "自动转入工作的参数未被连续醪塔执行器接受."
#define LANG_NBK_OPT_FINISHED "优化已完成"
#define LANG_NBK_BY_PRESSURE " 按压力("
#define LANG_NBK_COLON_MO ": Mo="
#define LANG_NBK_COMMA_PO ", Po="
#define LANG_NBK_LPH_PAUSE " l/h. 暂停 "
#define LANG_NBK_S_THEN_WORK " s, 然后工作."
#define LANG_NBK_AUTO_WORK_FORBIDDEN "禁止自动转入连续醪塔工作. 请设置 W 行的 Power/Speed, 然后按下一程序."
#define LANG_NBK_LINE_W_NEEDS_NONZERO "W 行需要非零的 Power 和 Speed, 或已保存的最优值."
#define LANG_NBK_WORK_UNAVAILABLE_PUMP_STOP "连续醪塔工作不可用: 泵停止未被确认."
#define LANG_NBK_HEATING_NOT_ON_EXPLICIT_WORK "显式转入工作指令后连续醪塔加热未开启."
#define LANG_NBK_HEATING_OFF_WORK_REJECTED "连续醪塔加热已关闭. 转入工作被拒绝."
#define LANG_NBK_LINE_W_PARAMS_REJECTED "W 行参数未被连续醪塔执行器接受."
#define LANG_NBK_EXPLICIT_WORK_ACCEPTED_M "显式转入连续醪塔工作已接受: M="
#define LANG_NBK_W_COMMA_P " W, P="
#define LANG_NBK_SAFE_WAIT_STOPPED_BY_OPERATOR "安全等待已被操作员停止."
#define LANG_NBK_SAFE_WAIT_SESSION_ENDED "连续醪塔安全等待: 会话已按操作员指令结束."
#define LANG_NBK_START_HEATING_OFF_PENDING "加热关闭尚未完成. 连续醪塔启动已取消."
#define LANG_NBK_HEATING_OFF_GOTO_LINE "连续醪塔加热已关闭. 转至第 #"
#define LANG_NBK_CANCELLED_DOT " 已取消."
#define LANG_NBK_START_REJECTED_BAD_SETTING "连续醪塔启动被拒绝: 设置无效 - "
#define LANG_NBK_START_LOG_FILE_ERROR "创建日志文件出错. 连续醪塔启动已取消."
#define LANG_NBK_PROGRAM_STARTED_WARMUP "连续醪塔程序已启动. 预热"
#define LANG_NBK_NO_FLOOD_SENSORS_WARNING "注意: 没有任何液泛传感器(FS 已关闭, PS 无响应). 液泛保护不起作用."
#define LANG_NBK_START_SESSION_BUSY "会话描述被占用. 连续醪塔启动已取消."
#define LANG_NBK_GOTO_LINE "转至第 #"
#define LANG_NBK_TYPE_SP ". 类型: "
#define LANG_NBK_START_HEATING_NOT_ON "连续醪塔加热未开启. 启动已取消."
#define LANG_NBK_HEATUP_TRANSITION_STARTED "连续醪塔升温转换已开始."
#define LANG_NBK_MANUAL_NEEDS_NONZERO "连续醪塔手动设置需要非零的功率和进料."
#define LANG_NBK_MANUAL_PARAMS_REJECTED "连续醪塔手动设置参数未被接受."
#define LANG_NBK_PROGRAM_LINE_EMPTY "连续醪塔程序错误: 程序行为空"
#define LANG_NBK_STEAM_98_WASH_OUT "蒸汽温度超过 98°C 达 60 s. 醪液已耗尽. 连续醪塔程序已结束."
#define LANG_NBK_EMERGENCY_WASH_OUT "紧急关机! 无法正常结束连续醪塔程序(醪液耗尽)"
#define LANG_NBK_TP_ROSE_BY "Tp 上升了 "
#define LANG_NBK_C_RELATIVE_TO_MIN " °C(相对于最小值 "
#define LANG_NBK_C_WASH_ENDING " °C - 醪液即将耗尽. 连续醪塔程序已结束."
#define LANG_NBK_EMERGENCY_TP_RISE "紧急关机! 无法正常结束连续醪塔程序(蒸汽 Tp 上升)"
#define LANG_NBK_STEAM_OVER_LIMIT_MANUAL "手动设置下蒸汽温度超过上限达 60 s. 蒸汽发生器可能干烧. 连续醪塔程序已结束."
#define LANG_NBK_EMERGENCY_STEAM_OVERHEAT_MANUAL "紧急关机! 无法正常结束连续醪塔程序(手动设置下蒸汽过热)"
#define LANG_NBK_INSUFFICIENT_COOLING "冷却不足! 已停止."
#define LANG_NBK_PRESSURE_SENSOR_FAILED "压力传感器故障! 超过 60 s 无读数. 已停止."
#define LANG_NBK_LOG_BUSY_CLOSE_SKIPPED "日志文件被占用: 未执行关闭"
#define LANG_NBK_HEATUP_TRANSITION_ABORTED "连续醪塔升温转换已中断."
#define LANG_NBK_HEATING_START_ABORTED "连续醪塔加热启动已中断: 启动条件被破坏, 流程已停止."
#define LANG_NBK_HEATUP_NEEDS_CONFIRMED_FEED "连续醪塔升温需要经确认的非零进料."
#define LANG_NBK_RUN_FINISHED "连续醪塔运行已结束"
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_ON_FINISH "结束时连续醪塔泵停止未被确认."
#define LANG_NBK_AVG_SESSION_RATE "平均会话速度 "
#define LANG_NBK_AND_AVG_FEED_RATE "平均进料速度 "
#define LANG_NBK_OVER_COLON "共: "
#define LANG_NBK_UNIT_H_DOT " h."
#define LANG_NBK_RUN_FINISHED_DOT "连续醪塔运行已结束."
#define LANG_NBK_RUN_ABORTED_EMERGENCY "连续醪塔运行因紧急状态中止."
#define LANG_NBK_FLOOD_FEED_REDUCE_UNCONFIRMED "液泛时连续醪塔进料降低未被确认."
#define LANG_NBK_EMERGENCY_FLOODING "紧急关机! 无法正常结束连续醪塔程序(液泛)"
#define LANG_NBK_FLOOD_ACTUATOR_REDUCE_REJECTED "液泛时连续醪塔执行器降低未被接受."
// BK.h
#define LANG_BK_WORK_POWER_APPLIED "醪塔工作功率已应用."
#define LANG_BK_PROGRAMS_DONE_CONTINUE "程序已执行完毕, 继续采出"
#define LANG_BK_LUA_LINE_SCRIPT_NOT_STARTED "Lua 错误: 行脚本未启动"
#define LANG_BK_PROGRAM_L_NEEDS_LUA "程序错误: L 类型需要 USE_LUA"
#define LANG_BK_GOTO_PROGRAM_LINE "转至程序行 #"
#define LANG_BK_DEPHLEGMATOR_WATER_MANUAL "分凝器水: 手动控制"
#define LANG_BK_PUMP_CONTROL_UNSUPPORTED "您的设备不支持泵控制"
#define LANG_BK_MODE_NAME "BC"
#define LANG_BK_SENSOR_BOILER "釜"
#define LANG_BK_SENSOR_VAPOR "蒸汽"
#define LANG_BK_START_NO_TANK_SENSOR "醪塔未启动: 釜传感器未分配或无响应"
#define LANG_BK_START_NEEDS_STEAM_SENSOR "醪塔未启动: 程序需要蒸汽传感器"
#define LANG_BK_START_LOG_FILE_ERROR "创建日志文件出错. 醪塔启动已取消."
#define LANG_BK_START_SESSION_BUSY "会话描述被占用. 醪塔启动已取消."
#define LANG_BK_HEATING_ON "醪塔加热已开启"
#define LANG_BK_WAIT_WORK_POWER "等待醪塔工作功率."
#define LANG_BK_LUA_TIMEOUT "Lua 在超时前未完成操作"
#define LANG_BK_LUA_FAILED "Lua 执行出错"
#define LANG_BK_RUN_FINISHED_DOT "醪塔运行已结束."
#define LANG_BK_RUN_FINISHED "醪塔运行已结束"
// distiller.h
#define LANG_DIST_NO_ALCOHOL_LEFT "釜中已无酒精"
#define LANG_DIST_ABV_UNAVAILABLE "酒精度不可用: 百分比行继续"
#define LANG_DIST_MODE_NAME "蒸馏"
#define LANG_DIST_SENSOR_BOILER "釜"
#define LANG_DIST_START_NO_TANK_SENSOR "蒸馏未启动: 釜传感器未分配或无响应. 请打开设置并检查釜传感器绑定."
#define LANG_DIST_START_LOG_FILE_ERROR "创建日志文件出错. 蒸馏启动已取消."
#define LANG_DIST_START_SESSION_BUSY "会话描述被占用. 蒸馏启动已取消."
#define LANG_DIST_HEATING_ON "蒸馏器加热已开启"
#define LANG_DIST_LUA_TIMEOUT "Lua 在超时前未完成操作"
#define LANG_DIST_LUA_FAILED "Lua 执行出错"
#define LANG_DIST_FINISHED "蒸馏已结束."
#define LANG_DIST_TOTAL_TIME " 总用时: "
#define LANG_DIST_UNIT_MIN " min."
#define LANG_DIST_PROGRAMS_DONE_CONTINUE "程序已执行完毕, 继续采出"
#define LANG_DIST_LUA_LINE_SCRIPT_NOT_STARTED "Lua 错误: 行脚本未启动"
#define LANG_DIST_PROGRAM_L_NEEDS_LUA "程序错误: L 类型需要 USE_LUA"
#define LANG_DIST_GOTO_PROGRAM_LINE "转至程序行 #"

// logic.h
#define LANG_LOGIC_PRG_NUM "行 #"
#define LANG_LOGIC_PROG_LINE_START "程序: 行起始 #"
#define LANG_LOGIC_PROG_LINE_START_LUA "程序: 行起始 #"
#define LANG_LOGIC_TAKEOFF_TO_CONTAINER ", 采出到容器 "
#define LANG_LOGIC_I2C_PUMP_CMD_HEAD "PC 上方 I2C 泵: 指令 «"
#define LANG_LOGIC_I2C_PUMP_CMD_TAIL "» 发送 10 次后仍未确认."
#define LANG_LOGIC_LUA_OP_DONE "Lua 操作已完成"
#define LANG_LOGIC_LUA_OP_NOT_DONE "Lua 操作未完成"
#define LANG_LOGIC_LUA_TIMEOUT "Lua 在超时前未完成操作"
#define LANG_LOGIC_LUA_OP_FAILED "Lua 操作失败"
#define LANG_LOGIC_LUA_ERROR "Lua 执行出错"
#define LANG_LOGIC_AUTOPAUSE_BUSY_SKIP "自动暂停类型被占用. 已跳过采出检查."
#define LANG_LOGIC_PAUSE_SET_FAIL_HEAD "无法按以下条件设置暂停: "
#define LANG_LOGIC_PAUSE_TYPE_BUSY_TAIL ": 暂停类型被占用."
#define LANG_LOGIC_AUTOPAUSE_TAIL "采出自动暂停"
#define LANG_LOGIC_PAUSE_BY "暂停原因: "
#define LANG_LOGIC_RESUME_AFTER_AUTOPAUSE "自动暂停后继续采出"
#define LANG_LOGIC_TAKEOFF_RESUMED "采出已恢复"
#define LANG_LOGIC_LABEL_T_STEAM "T 蒸汽"
#define LANG_LOGIC_LABEL_T_PIPE "T 塔"
#define LANG_LOGIC_DETECTOR_RESUME "检测器: 暂停后继续采出"
#define LANG_LOGIC_PUMP_CAL_BAD_STEPS "泵校准错误: 步数无效"
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_HEAD "泵校准未保存: "
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_TAIL ". 结果已丢失, 请重新校准."
#define LANG_LOGIC_ACTION_PAUSE "暂停"
#define LANG_LOGIC_ACTION_RESUME "继续"
#define LANG_LOGIC_MANUAL_PAUSE_TAKEOFF "手动采出暂停"
#define LANG_LOGIC_MANUAL_PAUSE_MASH "手动糖化暂停"
#define LANG_LOGIC_MASH_PAUSE_NEXT_STEP "暂停将在下一个糖化步骤生效."
#define LANG_LOGIC_MASH_PAUSED "糖化已暂停."
#define LANG_LOGIC_AUTOPAUSE_RESET_FAIL "无法重置自动暂停类型."
#define LANG_LOGIC_MASH_RESUMED_TAIL "糖化已继续"
#define LANG_LOGIC_MASH_RESUMED_MSG "糖化已继续."
#define LANG_LOGIC_DIST_MODE_SEP "; 蒸馏模式"
#define LANG_LOGIC_DIST_PROGRAMS_DONE "程序已完成, 采出至釜 T "
#define LANG_LOGIC_DIST_MODE_DEG "°; 蒸馏模式"
#define LANG_LOGIC_DIST_ROW_LEFT "; 本行: 剩余 "
#define LANG_LOGIC_OF_APPROX " / ~"
#define LANG_LOGIC_UNIT_MIN " min"
#define LANG_LOGIC_DIST_ROW_FORECAST_WAIT "; 本行预测: 等待数据"
#define LANG_LOGIC_DIST_PROCESS_LEFT "; 流程至 DistTemp, 剩余:"
#define LANG_LOGIC_DIST_TOTAL "; 总计:"
#define LANG_LOGIC_DIST_PROCESS_FORECAST_WAIT "; 流程预测: 等待沸腾/数据"
#define LANG_LOGIC_BK_MODE "醪塔模式"
#define LANG_LOGIC_NBK_STAGE_H "预热"
#define LANG_LOGIC_NBK_STAGE_S "设置"
#define LANG_LOGIC_NBK_STAGE_O "优化"
#define LANG_LOGIC_NBK_STAGE_W "工作"
#define LANG_LOGIC_BEER_ON_PAUSE "已暂停; "
#define LANG_LOGIC_BEER_WAIT_SKIP_COOL "等待确认跳过冷却; "
#define LANG_LOGIC_BEER_HEAT_TO_MALT "升温至投入麦芽温度"
#define LANG_LOGIC_CUR_T "; 当前 T: "
#define LANG_LOGIC_BEER_WAIT_MALT "等待投入麦芽"
#define LANG_LOGIC_BEER_PAUSE "暂停 "
#define LANG_LOGIC_BEER_DEG_HEATING "°; 升温"
#define LANG_LOGIC_BEER_COOL_TO "冷却至 "
#define LANG_LOGIC_BEER_WAIT_PRESS_NEXT "等待. 请按下一程序; "
#define LANG_LOGIC_BEER_AUTOCAL "自动校准. 完成后 "
#define LANG_LOGIC_BEER_AUTOCAL_POWER_OFF "电源将关闭"
#define LANG_LOGIC_BEER_AUTOCAL_NEXT_LINE "转至下一行"
#define LANG_LOGIC_BEER_BOIL_HEATING "煮沸 - 加热"
#define LANG_LOGIC_BEER_BOIL "煮沸 "
#define LANG_LOGIC_BEER_FERM_HOLD "发酵; 保持 T="
#define LANG_LOGIC_CUR_SHORT "; 当前: "
#define LANG_LOGIC_PAREN_HEATING " (加热)"
#define LANG_LOGIC_PAREN_THERMOSTAT " (恒温)"
#define LANG_LOGIC_BEER_FERM_STOPPED "发酵 (已停止)"
#define LANG_LOGIC_RUNNING_LUA_SCRIPT "正在运行 Lua 脚本"
#define LANG_LOGIC_PROGRESS "; 进度: "
#define LANG_LOGIC_STATUS_OFF "已关闭"
#define LANG_LOGIC_PAREN_ERROR "(错误)"
#define LANG_LOGIC_AUTOPAUSE_READ_FAIL "无法读取自动暂停类型."
#define LANG_LOGIC_PAUSE_SP " 暂停 "
#define LANG_LOGIC_RESUME_IN ". 继续倒计时 "
#define LANG_LOGIC_UNIT_SEC " s."
#define LANG_LOGIC_PROGRAM_DONE_STATUS "程序执行完毕"
#define LANG_LOGIC_STATUS_CALIBRATION "校准"
#define LANG_LOGIC_STATUS_PAUSE "暂停"
#define LANG_LOGIC_SUVID_HOLD "低温慢煮; 保持 T="
#define LANG_LOGIC_DEG_CUR "°; 当前: "
#define LANG_LOGIC_SUVID_HOLD_TIME "; 保温: "
#define LANG_LOGIC_COLUMN_HEATUP "塔升温"
#define LANG_LOGIC_HEATUP_DONE_STAB "升温完成. 稳定/全回流"
#define LANG_LOGIC_STAB_DONE "稳定完成/全回流"
#define LANG_LOGIC_LEFT "; 剩余:"
#define LANG_LOGIC_BODY_T_STEAM ";酒心 T 蒸汽:"
#define LANG_LOGIC_BODY_T_PIPE ";酒心 T 塔:"
#define LANG_LOGIC_PUMP_NOT_CALIBRATED "泵未校准(每 ml 步数 = 0). 无法启动精馏."
#define LANG_LOGIC_RECT_PROG_LINE_UNSET "精馏程序错误: 未设置程序行"
#define LANG_LOGIC_RECT_PROG_FIRST_LINE "程序错误: 第一行必须设置绝对功率/电压. 无法启动精馏."
#define LANG_LOGIC_PROG_ERR_LINE "程序错误: 行 "
#define LANG_LOGIC_PROG_LINE_NEVER_ENDS " 永远不会结束(未设置体积和温度)"
#define LANG_LOGIC_ACTION_PROGRAM_END "程序结束"
#define LANG_LOGIC_PROGRAM_FINISHED "程序已结束"
#define LANG_LOGIC_LOG_BUSY_CLOSE_SKIPPED "日志文件被占用: 已跳过关闭"
#define LANG_LOGIC_PROGRAM_DONE_MSG "程序执行完毕."
#define LANG_LOGIC_LUA_LINE_SCRIPT_NOT_STARTED "Lua 错误: 行脚本未启动"
#define LANG_LOGIC_NEXT_LINE "转至下一行"
#define LANG_LOGIC_LUA_OP_STARTED "Lua 操作已开始"
#define LANG_LOGIC_PROG_TYPE_L_NEEDS_LUA "程序错误: L 类型需要 USE_LUA"
#define LANG_LOGIC_ACTION_LINE_START "行起始 "
#define LANG_LOGIC_PROG_LINE_SPEED "程序: 行速度 #"
#define LANG_LOGIC_SPEED_OVER_PUMP_LIMIT " l/h) 超过泵上限, 已限制为 "
#define LANG_LOGIC_UNIT_LPH_DOT " l/h."
#define LANG_LOGIC_COMMA_PAUSE ", 暂停 "
#define LANG_LOGIC_PROGRAM_PAUSE "程序暂停"
#define LANG_LOGIC_NEW_BODY_T_STEAM "新的酒心 T: 蒸汽 = "
#define LANG_LOGIC_COMMA_PIPE_EQ ", 塔 = "
#define LANG_LOGIC_BODY_T_SET_FAIL "无法设置酒心 T."
#define LANG_LOGIC_BOILING_STARTED_ABV "釜中开始沸腾! 酒精度 "
#define LANG_LOGIC_BOILING_STARTED "釜中开始沸腾!"
#define LANG_LOGIC_WETTING_START "开始润湿塔填料. 请注意回流液位!"
#define LANG_LOGIC_WETTING_OK "塔填料润湿成功!"
#define LANG_LOGIC_WETTING_TIMEOUT "超过最大润湿时间. 润湿失败, 请手动停止流程."
#define LANG_LOGIC_WETTING_VOLT_RAMP_START "开始逐步降低电压"
#define LANG_LOGIC_WETTING_VOLT_TO "电压降至 "
#define LANG_LOGIC_WETTING_MIN_VOLT "已达最低电压: "
#define LANG_LOGIC_WETTING_WAIT_SENSOR ". 等待传感器触发."
#define LANG_LOGIC_WETTING_MIN_VOLT_TIMEOUT "最低电压下等待超时. 润湿失败, 请手动停止流程."
#define LANG_LOGIC_WETTING_NO_SENSOR "未安装回流液位传感器, 无法润湿填料"
// alarm.h
#define LANG_ALARM_SENSORS_UNASSIGNED "传感器未分配. 请打开设置并绑定蒸汽, 水和釜传感器."
#define LANG_ALARM_EMERGENCY_STOP "紧急关机!"
#define LANG_ALARM_COOLING_HOLD_3MIN "冷却将再运行 3 min 后关闭."
#define LANG_ALARM_EMERGENCY_STOP_TAIL "紧急关机"
#define LANG_ALARM_EMERGENCY_STOP_SP "紧急关机! "
#define LANG_ALARM_NO_SENSOR_DATA ": 无传感器数据 "
#define LANG_ALARM_RECT_SENSORS_UNASSIGNED "紧急关机! 精馏: 传感器未分配"
#define LANG_ALARM_MODE_RECT "精馏"
#define LANG_ALARM_SENSOR_STEAM "蒸汽"
#define LANG_ALARM_SENSOR_TANK "釜"
#define LANG_ALARM_FLOOD_SENSOR "液泛传感器触发!"
#define LANG_ALARM_REDUCING_FROM " 降低自 "
#define LANG_ALARM_RAISING_TO " 升高至 "
#define LANG_ALARM_OVERTEMP_STEAM " 蒸汽"
#define LANG_ALARM_OVERTEMP_WATER " 水"
#define LANG_ALARM_OVERTEMP_ACP " ACP"
#define LANG_ALARM_TANK_LIMIT_FINISHED "达到釜最高温度上限. 程序已结束."
#define LANG_ALARM_TANK_LIMIT_FINISH_FAIL "紧急关机! 无法按釜温度正常结束程序"
#define LANG_ALARM_MAX_TEMP_EXCEEDED "紧急关机! 超过最高温度:"
#define LANG_ALARM_WATER_CRIT_SUPPLY_ERR "水温临界! 供水错误. "
#define LANG_ALARM_HEATUP_DONE_STAB "升温完成. 稳定/全回流."
#define LANG_ALARM_ABV "酒精度 "
#define LANG_ALARM_STAB_DONE_STABLE "稳定完成, 塔运行稳定."
// mode_switch.h
#define LANG_MSW_I2C_MIXER_STOP "I2C 搅拌器未确认停止"
#define LANG_MSW_I2C_PUMP_STOP "I2C 泵未确认停止"
#define LANG_MSW_STEPPER_STOP "步进电机未停止"
#define LANG_MSW_VALVE_CLOSE "阀未关闭"
#define LANG_MSW_MIXER_STOP "搅拌器未停止"
#define LANG_MSW_COOLING_PUMP_STOP "冷却泵未停止"
#define LANG_MSW_PUMP_CAL_NOT_DONE "泵校准未完成"
#define LANG_MSW_HEATING_NOT_CONFIRMED "加热未确认"
#define LANG_MSW_ACTUATOR_NOT_CONFIRMED "执行器未确认"
#define LANG_MSW_FORCE_COMPLETED "模式切换已强制完成: "
#define LANG_MSW_LUA_NOT_CONFIRMED "Lua 未确认"
#define LANG_MSW_QUEUE_NOT_CONFIRMED "队列未确认"
#define LANG_MSW_PENDING_CMDS_CANCELLED "待执行的控制指令已因模式切换取消"
#define LANG_MSW_READINESS_NOT_CONFIRMED "就绪状态未确认"
#define LANG_MSW_LOG_NOT_CONFIRMED "日志未确认"
#define LANG_MSW_POWER_TRANSITION_NOT_CONFIRMED "功率转换未确认"
#define LANG_MSW_NBK_TRANSITION_NOT_CONFIRMED "连续醪塔转换未确认"
#define LANG_MSW_HEATING_START_NOT_CONFIRMED "加热启动未确认"
#define LANG_MSW_SELF_TEST_NOT_CONFIRMED "自检未确认"
#define LANG_MSW_OWNER_NOT_CONFIRMED "模式所有者未确认"
#define LANG_MSW_LUA_NOT_RELOADED "Lua 脚本未重新加载"
#define LANG_MSW_PROFILE_NOT_SAVED "配置未保存"
// mode_common.h
#define LANG_MCOM_SENSOR_WATER "水"
#define LANG_MCOM_SENSOR_ACP "ACP"
#define LANG_MCOM_WATER_SUPPLY_STOPPED "紧急关机! 供水已中断."
#define LANG_MCOM_OVERTEMP_WATER " 水"
#define LANG_MCOM_OVERTEMP_ACP " ACP"
#define LANG_MCOM_MAX_TEMP_EXCEEDED "紧急关机! 超过最高温度:"
#define LANG_MCOM_WATER_HIGH_HEAD "水温过高: "
#define LANG_MCOM_WATER_WARN_THRESHOLD "°C(警告阈值 "
#define LANG_MCOM_CHECK_COOLING_DOT "°C). 请检查冷却."
#define LANG_MCOM_ACP_HIGH_HEAD "通气管温度过高: "
#define LANG_MCOM_ACP_THRESHOLD "°C(阈值 "
#define LANG_MCOM_CHECK_COOLING_BANG "°C)! 请检查冷却."
#define LANG_MCOM_WATER_CRIT_REDUCING "水温临界! 降低 "
#define LANG_MCOM_FROM ": "
#define LANG_MCOM_LOG_BUSY_CLOSE_SKIPPED "日志文件被占用: 已跳过关闭"
#define LANG_MCOM_HEATING_LATCHED "加热已被紧急保护锁定, 需要重启"
#define LANG_MCOM_HEATING_OFF_PENDING "加热关闭尚未完成. 启动已取消."
#define LANG_MCOM_HEATING_NOT_RESUMED "加热未自动恢复. 需要再次发出启动指令."
// mode_registry.h
#define LANG_MREG_NAME_DIST "蒸馏"
#define LANG_MREG_NAME_BEER "啤酒"
#define LANG_MREG_NAME_BK "BC"
#define LANG_MREG_NAME_NBK "CBC"
#define LANG_MREG_NAME_CHEESE "奶酪制作"
#define LANG_MREG_UNAVAILABLE_NO_REGULATOR "此固件版本不可用: 无调压器"
#define LANG_MREG_UNAVAILABLE_NO_LUA "此固件版本不可用: 未启用 Lua"
#define LANG_MREG_START_REJECTED_SWITCH "启动指令被拒绝: 模式切换尚未完成"
#define LANG_MREG_START_UNAVAILABLE_MODE "当前模式下启动指令不可用"
#define LANG_MREG_QUEUE_BUSY_START "指令队列繁忙: 启动 "
#define LANG_MREG_NOT_QUEUED " 未入队"
#define LANG_MREG_STATUS_MISMATCH "状态不属于当前模式 - 已跳过周期, 请检查模式同步"

// beer.h
#define LANG_BEER_ADD_HOPS "请投入啤酒花!"
#define LANG_BEER_ESTOP_COOLING_OPEN "紧急关机! 无法开启冷却"
#define LANG_BEER_ESTOP_COOLING_SAFE "紧急关机! 无法使冷却恢复安全状态"
#define LANG_BEER_ESTOP_COOL_PUMP_ON "紧急关机! 无法开启冷却泵"
#define LANG_BEER_ESTOP_COOL_PUMP_OFF "紧急关机! 无法关闭冷却泵"
#define LANG_BEER_ESTOP_COOLING_RESTORE "紧急关机! 无法使冷却恢复工作状态"
#define LANG_BEER_ESTOP_COOLING_CLOSE "紧急关机! 无法关闭冷却"
#define LANG_BEER_SENSOR_TANK "釜"
#define LANG_BEER_SENSOR_WATER "水"
#define LANG_BEER_SENSOR_PIPE "塔"
#define LANG_BEER_SENSOR_STEAM "蒸汽"
#define LANG_BEER_SENSOR_ACP "ACP"
#define LANG_BEER_ERR_ROW_NOT_SET "啤酒程序错误: 未设置程序行"
#define LANG_BEER_ERR_BAD_STAGE_TYPE "程序错误: 行中阶段类型无效 "
#define LANG_BEER_ERR_PROGRAM_PREFIX "程序错误: "
#define LANG_BEER_ERR_PROGRAM "程序错误"
#define LANG_BEER_IN_LINE " 位于行 "
#define LANG_BEER_ERR_BAD_TEMP_SENSOR "程序错误: 行中温度传感器无效 "
#define LANG_BEER_ERR_I2C_PUMP_LINE "I2C 泵在行中不可用 "
#define LANG_BEER_ERR_I2C_PUMP_RELAY_LINE "I2C 泵继电器在行中不可用 "
#define LANG_BEER_ERR_I2C_MIXER_LINE "I2C 搅拌器在行中不可用 "
#define LANG_BEER_MODE_NAME "啤酒"
#define LANG_BEER_START_HEAT_OFF_PENDING "加热关闭尚未完成. 糖化启动已取消."
#define LANG_BEER_START_SAFETY_LATCH "加热安全锁已激活. 糖化启动已取消."
#define LANG_BEER_START_LOG_FILE "创建日志文件出错. 糖化启动已取消."
#define LANG_BEER_START_SESSION_BUSY "会话描述被占用. 糖化启动已取消."
#define LANG_BEER_START_POWER_ON_FAILED "无法开启加热电源. 糖化启动已取消."
#define LANG_BEER_WAIT_SKIP_COOL_CONFIRM "等待确认跳过冷却"
#define LANG_BEER_WORT_NOT_COOLED "麦汁尚未冷却到目标温度. 请在 10 s 内重复切换以确认."
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_NEXT "Lua 错误: 切换前无法关闭搅拌器"
#define LANG_BEER_LUA_STOP_LOCK_BUSY "无法立即停止 Lua job - 锁被占用. 请一秒后重复切换."
#define LANG_BEER_LUA_STOP_REQUEST_FAILED "Lua 错误: 无法请求停止 job"
#define LANG_BEER_ERR_L_NEEDS_USE_LUA "程序错误: L 类型需要 USE_LUA"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_START "Lua 错误: 启动前无法关闭搅拌器"
#define LANG_BEER_LUA_JOB_NOT_ACCEPTED "Lua 错误: job 未被接受启动"
#define LANG_BEER_MOVE_TO_LINE "转至程序行 #"
#define LANG_BEER_MSG_HEAT_MALT "; 升温至投入麦芽温度: "
#define LANG_BEER_MSG_TEMP_PAUSE "; 温度暂停: "
#define LANG_BEER_MSG_DEG_TIME "°, 时间: "
#define LANG_BEER_MIN " min"
#define LANG_BEER_MSG_BOIL_TIME "; 煮沸, 时间: "
#define LANG_BEER_MSG_COOL_TO "; 冷却至温度: "
#define LANG_BEER_MSG_FERMENT_HOLD "; 发酵, 保持温度: "
#define LANG_BEER_MSG_WAIT_MODE "; 等待模式"
#define LANG_BEER_NEXT_LINE "转至下一行"
#define LANG_BEER_LUA_JOB_ACCEPTED_MSG "Lua 任务已接受"
#define LANG_BEER_FINISH_ACTUATOR_FAILED "酿造结束错误: 无法关闭执行器"
#define LANG_BEER_LUA_JOB_WITHOUT_USE_LUA "Lua 错误: 无 USE_LUA 但 job 活动"
#define LANG_BEER_BREW_STOPPED_ERROR "酿造因错误而停止"
#define LANG_BEER_BREW_DONE "酿造已结束"
#define LANG_BEER_MASH_PROGRAM_DONE "糖化程序已结束"
#define LANG_BEER_ESTOP_WORT_OVERTEMP "紧急关机! 超过最高麦汁温度"
#define LANG_BEER_HOLD_PAUSE_BELOW_TARGET "保温暂停: 温度低于目标"
#define LANG_BEER_HOLD_RESUMED "保温已继续"
#define LANG_BEER_MANUAL_PAUSE_ACTUATOR_FAILED "手动暂停错误: 无法关闭执行器"
#define LANG_BEER_ERR_UNKNOWN_STAGE_TYPE "程序错误: 行中阶段类型未知 "
#define LANG_BEER_LUA_TIMEOUT "Lua 在超时前未完成操作"
#define LANG_BEER_LUA_MIXER_OFF_ON_STOP "Lua 错误: 停止 job 时无法关闭搅拌器"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_CONFIRM "Lua 错误: 确认 job 前无法关闭搅拌器"
#define LANG_BEER_LUA_JOB_CONFIRMED "Lua 任务已确认"
#define LANG_BEER_LUA_JOB_NO_START_CONFIRM "Lua 错误: job 未确认启动"
#define LANG_BEER_LUA_JOB_FAILED "Lua 错误: job 执行出错"
#define LANG_BEER_WAIT_OPERATOR "等待操作员操作"
#define LANG_BEER_AUTOTUNE_QUEUE_BUSY "指令队列繁忙: 将重试结束啤酒自整定"
#define LANG_BEER_MALT_TEMP_REACHED "已达投入麦芽温度!"
#define LANG_BEER_WAIT_MALT "等待投入麦芽"
#define LANG_BEER_TEMP_PAUSE_REACHED "已达温度暂停 "
#define LANG_BEER_DEG_WAITING "°. 等待 "
#define LANG_BEER_MINUTES_DOT " min."
#define LANG_BEER_COOL_TIMEOUT_24H "24 h 内无法将釜冷却到目标温度. 请检查釜传感器, 冷却水供应和冷却阀."
#define LANG_BEER_BOIL_STARTED "煮沸模式已开始"
#define LANG_BEER_BOIL_NOT_DETECTED_120 "120 min 内未能检测到沸腾开始. 请检查釜传感器, 液体体积, 盖子, 以及沸腾阈值是否可达(低气压)."
#define LANG_BEER_ESTOP_MIXER_RESTORE "紧急关机! 无法恢复搅拌器状态"
#define LANG_BEER_PID_AUTOTUNE_NO_MEM "PID 自整定未启动: 内存不足"
#define LANG_BEER_PID_AUTOTUNE_NOT_SAVED "PID 自整定未保存: "
// cheese.h
#define LANG_CHEESE_TEMP_CONFIRM_STARTED "温度确认已开始"
#define LANG_CHEESE_PH_CONFIRM_STARTED "pH 确认已开始"
#define LANG_CHEESE_ESTOP_EQUIPMENT_OFF "紧急关机! 无法关闭奶酪制作设备"
#define LANG_CHEESE_STAGE_HEAT "加热"
#define LANG_CHEESE_STAGE_HOLD "保温"
#define LANG_CHEESE_STAGE_COOL "冷却"
#define LANG_CHEESE_STAGE_MIX "搅拌"
#define LANG_CHEESE_STAGE_DOSE "加料"
#define LANG_CHEESE_STAGE_PH "等待 pH"
#define LANG_CHEESE_STAGE_MANUAL "手动操作"
#define LANG_CHEESE_STAGE_DRAIN "排放"
#define LANG_CHEESE_STAGE_FLOC "絮凝"
#define LANG_CHEESE_STAGE_UNKNOWN "未知操作"
#define LANG_CHEESE_ROW "行 "
#define LANG_CHEESE_ERR_ROW_NOT_SET "奶酪程序错误: 未设置程序行"
#define LANG_CHEESE_ERR_PROGRAM_PREFIX "程序错误: "
#define LANG_CHEESE_ERR_PROGRAM "程序错误"
#define LANG_CHEESE_IN_LINE " 位于行 "
#define LANG_CHEESE_ERR_TEMP_SENSOR_LINE "行中温度传感器错误 "
#define LANG_CHEESE_ERR_I2C_MIXER_LINE "I2C 搅拌器在行中不可用 "
#define LANG_CHEESE_ERR_LOCAL_DOSER_LINE "本地加料器在行中不可用 "
#define LANG_CHEESE_ERR_I2C_PUMP_LINE "I2C 泵在行中不可用 "
#define LANG_CHEESE_ERR_COOLING_NOT_IN_BUILD "此版本中冷却不可用"
#define LANG_CHEESE_ERR_PH_CAL_LINE "行中 pH 校准无效 "
#define LANG_CHEESE_ERR_LUA_NOT_IN_BUILD "此版本中 Lua 不可用"
#define LANG_CHEESE_ERR_LUA_FILE_LINE "行中未找到 Lua 文件 "
#define LANG_CHEESE_LUA_JOB_ACCEPTED "Lua 任务已接受"
#define LANG_CHEESE_NEXT_LINE "转至下一行"
#define LANG_CHEESE_WAIT_OPERATOR "等待操作员操作"
#define LANG_CHEESE_DOSER_STARTED "加料器已启动"
#define LANG_CHEESE_LUA_OUTPUTS_OFF_FAILED "Lua 错误: 无法关闭输出"
#define LANG_CHEESE_ERR_ROW_TRANSITION "转至奶酪程序行出错"
#define LANG_CHEESE_FLOC_RECORDED "|絮凝已记录: "
#define LANG_CHEESE_SEC_UNIT " s"
#define LANG_CHEESE_FLOC_TIMEOUT "絮凝超时"
#define LANG_CHEESE_CUT_AFTER_TIMEOUT "计算的切割时间晚于絮凝超时"
#define LANG_CHEESE_FLOC_NO_SESSION "未创建絮凝会话"
#define LANG_CHEESE_LUA_TIMEOUT "Lua 在超时前未完成操作"
#define LANG_CHEESE_LUA_JOB_DONE "Lua 任务已完成"
#define LANG_CHEESE_ERR_AFTER_LUA "Lua 之后转换出错"
#define LANG_CHEESE_LUA_NO_NEXT_LINE "Lua 结束但未转至下一行"
#define LANG_CHEESE_LUA_FAILED "Lua 执行出错"
#define LANG_CHEESE_ERR_UNKNOWN_OPERATION "程序错误: 未知操作"
#define LANG_CHEESE_MODE_NAME "奶酪"
#define LANG_CHEESE_ERR_TEMP_SENSOR "温度传感器错误"
#define LANG_CHEESE_ERR_MIXER "搅拌器错误"
#define LANG_CHEESE_OPERATION_TIMEOUT "奶酪程序操作超时"
#define LANG_CHEESE_TEMP_CONFIRMED "温度已确认"
#define LANG_CHEESE_HOLD_RESUMED "保温已继续"
#define LANG_CHEESE_HOLD_PAUSED_OUT_OF_BAND "保温暂停: 温度超出范围"
#define LANG_CHEESE_HOLD_TIMEOUT "保温超时"
#define LANG_CHEESE_ERR_COOLING "冷却错误"
#define LANG_CHEESE_COOLING_OFF_FAILED "无法关闭冷却"
#define LANG_CHEESE_DOSING_DONE "加料已完成"
#define LANG_CHEESE_I2C_DOSING_ABORTED "I2C 泵加料已中止"
#define LANG_CHEESE_PH_INVALID_10S "pH 无效已持续 10 s"
#define LANG_CHEESE_PH_CONFIRMED "pH 已确认"
#define LANG_CHEESE_FINISH_OUTPUTS_NOT_OFF "奶酪制作结束错误: 输出未关闭"
#define LANG_CHEESE_STOPPED_ERROR "奶酪制作因错误而停止"
#define LANG_CHEESE_DONE "奶酪制作已结束"
#define LANG_CHEESE_PROGRAM_DONE "奶酪制作程序已结束"
#define LANG_CHEESE_START_NO_ADS1115 "未找到 ADS1115. 奶酪制作启动已取消."
#define LANG_CHEESE_START_HEAT_UNAVAILABLE "加热不可用. 奶酪制作启动已取消."
#define LANG_CHEESE_START_LOG_FILE "创建日志文件出错. 奶酪制作启动已取消."
#define LANG_CHEESE_START_SESSION_BUSY "会话描述被占用. 奶酪制作启动已取消."
#define LANG_CHEESE_START_POWER_ON_FAILED "无法开启加热电源. 奶酪制作启动已取消."
#define LANG_CHEESE_STATUS_WAITING "等待"
#define LANG_CHEESE_STATUS_LINE "; 行 "
// suvid.h
#define LANG_SUVID_MODE_NAME "低温煮"
#define LANG_SUVID_SENSOR_WATER "水"
#define LANG_SUVID_SENSOR_ACP "ACP"
#define LANG_SUVID_SENSOR_TANK "釜"
#define LANG_SUVID_FINISHED "低温慢煮已结束"
#define LANG_SUVID_HOLD_PAUSED_OUT_OF_BAND "保温暂停: 温度超出范围"
#define LANG_SUVID_DEVIATION_WARNING "低温慢煮: 温度偏离设定值超过 2° 已达 60 s."
#define LANG_SUVID_HOLD_RESUMED "保温已继续"
#define LANG_SUVID_REACH_TIMEOUT "低温慢煮: 120 min 内未达到工作温度, 加热关闭. 请检查加热器, 釜传感器和装载量."
#define LANG_SUVID_HOLD_DONE "低温慢煮: 保温结束, 加热已关闭."
#define LANG_SUVID_HOLD_DONE_QUEUE_BUSY "低温慢煮: 保温结束, 但正常关机未入队: 指令队列繁忙."
// program_io.h
#define LANG_PROG_ERR_PROGRAM "程序错误"
#define LANG_PROG_LINE_OPEN " (行 "
#define LANG_PROG_LUA_TEXT_BAD "Lua 文本为空或过长"
#define LANG_PROG_LUA_FILE_REQUIRED "请指定 .lua 文件; 空参数写作 «»"
#define LANG_PROG_BEER_DEVICE_MASK "设备必须为 0^0^0^0^0 或 1..3 的掩码且排程非零"
#define LANG_PROG_BEER_TYPE_MC "M/C 类型要求 Temp 大于 0 且 Time=0"
#define LANG_PROG_BEER_TYPE_F "F 类型要求 Temp 大于 0"
#define LANG_PROG_BEER_TYPE_P "P 类型要求 Temp 和 Time 大于 0"
#define LANG_PROG_BEER_TYPE_B "B 类型要求 Temp=0 且 Time 大于 0"
#define LANG_PROG_BEER_TYPE_W "W 类型要求 Temp=0 且 Time=0"
#define LANG_PROG_BEER_TYPE_L "L 类型需要超时和零参数"
#define LANG_PROG_L_NEEDS_USE_LUA "L 类型需要 USE_LUA"
#define LANG_PROG_BEER_TYPE_A "A 类型要求 Temp 大于 0, Time=0 且设备=0^0^0^0^0"
#define LANG_PROG_BEER_UNKNOWN_TYPE "未知的 beer 类型"
#define LANG_PROG_L_TIMEOUT_RANGE "L 需要 1..65535 s 的超时和零数值字段"
#define LANG_PROG_SPEED_SR "S/R 类型要求 Speed 在范围 (0,1) 内"
#define LANG_PROG_SPEED_AP "A/P 类型要求 Speed 在范围 [0,100) 内"
#define LANG_PROG_SPEED_T "T 类型要求 Speed 在范围 (0,150] 内"
#define LANG_PROG_STEAM_TEMP_RANGE "T 蒸汽: 0 或 30..100"
#define LANG_PROG_BEER_BAD_DEVICE "beer 设备模板无效"
#define LANG_PROG_CHEESE_MIXER_FORM "搅拌器必须为 0^0^0^0, 继电器 1^0, 非零 RPM 的 I2C 2, 或带反转的 I2C 3(含 RPM, ON 和 OFF)"
#define LANG_PROG_CHEESE_H "H 需要 Temp, Time, 升温速率和传感器"
#define LANG_PROG_CHEESE_P "P 需要传感器且 Param 不小于 Time"
#define LANG_PROG_CHEESE_C "C 需要 Temp, Time, 传感器且 Param=0"
#define LANG_PROG_CHEESE_M "M 需要 Time, 搅拌器且 Temp/Param/传感器为零"
#define LANG_PROG_CHEESE_D "D 需要 Time, 方式以及手动, 体积或步进加料的参数"
#define LANG_PROG_CHEESE_N "N 需要 Temp, Time, pH 0..14 和传感器"
#define LANG_PROG_CHEESE_F "F 需要 Temp, Time, 不小于 1 的倍数和传感器"
#define LANG_PROG_CHEESE_W "W 需要 Time, 动作代码 1..8 且 TempSensor=0"
#define LANG_PROG_CHEESE_S "S 需要安全输出, Time 和零字段"
#define LANG_PROG_CHEESE_L "L 需要安全输出, Time 和零字段"
#define LANG_PROG_CHEESE_UNKNOWN_TYPE "未知的 cheese 类型"
#define LANG_PROG_CHEESE_F_MULT "F 倍数无法表示为 m=round(MULTIPLIER*1000)"
#define LANG_PROG_CHEESE_BAD_DEVICE "cheese 设备模板无效"
#define LANG_PROG_EMPTY_USE_CLEAR "空程序: 请使用显式清除"
#define LANG_PROG_RECT_LINE_TOO_LONG "行过长 (rect)"
#define LANG_PROG_RECT_BAD_FORMAT "rect 行格式无效"
#define LANG_PROG_RECT_TOO_MANY "rect 行过多"
#define LANG_PROG_DIST_LINE_TOO_LONG "行过长 (dist)"
#define LANG_PROG_DIST_BAD_FORMAT "dist 行格式无效"
#define LANG_PROG_DIST_TOO_MANY "dist 行过多"
#define LANG_PROG_BK_LINE_TOO_LONG "行过长 (bk)"
#define LANG_PROG_BK_BAD_FORMAT "bk 行格式无效"
#define LANG_PROG_BK_TOO_MANY "bk 行过多"
#define LANG_PROG_BEER_LINE_TOO_LONG "行过长 (beer)"
#define LANG_PROG_BEER_BAD_FORMAT "beer 行格式无效"
#define LANG_PROG_BEER_TOO_MANY "beer 行过多"
#define LANG_PROG_NBK_LINE_TOO_LONG "行过长 (nbk)"
#define LANG_PROG_NBK_BAD_FORMAT "nbk 行格式无效"
#define LANG_PROG_NBK_TOO_MANY "nbk 行过多"
#define LANG_PROG_CHEESE_LINE_TOO_LONG "行过长 (cheese)"
#define LANG_PROG_CHEESE_BAD_FORMAT "cheese 行格式无效"
#define LANG_PROG_CHEESE_TOO_MANY "cheese 行过多"
#define LANG_PROG_NBK_FOUR_ROWS "连续醪塔必须包含 4 行 H/S/O/W"
#define LANG_PROG_UNSUPPORTED_MODE "不支持的模式"
#define LANG_PROG_FIRST_ROW_ABSOLUTE "第一行必须设置绝对功率/电压(否则塔将保持升温的全功率)"
#define LANG_PROG_FIRST_NONZERO_ABSOLUTE "第一行的非零电压/功率必须设置绝对值而非修正值(否则升温阶段加热可能悄然关闭)"

// Samovar.ino
// Заголовок уровня V26/push: в любом языке, кроме русского, - только знак ⛔/⚠ (PIN_SPEC.md §6).
#define LANG_MAIN_V26_ALARM_HEADER "⛔ "
#define LANG_MAIN_V26_WARNING_HEADER "⚠ "
#define LANG_MAIN_ASSERT_BLYNK_TIMEOUT "Samovar.h 中的 BLYNK_TIMEOUT_MS 未生效: BlynkConfig.h 已提前包含"
#define LANG_MAIN_ASSERT_BLYNK_SENDBYTES "Samovar.h 中的 BLYNK_MAX_SENDBYTES 未生效: BlynkConfig.h 已提前包含"
#define LANG_MAIN_ASSERT_BLYNK_MSG_LIMIT "Samovar.h 中的 BLYNK_MSG_LIMIT 未生效: BlynkConfig.h 已提前包含"
#define LANG_MAIN_ERR_SENSOR_STEAM "蒸汽温度传感器错误!"
#define LANG_MAIN_ERR_SENSOR_PIPE "塔温度传感器错误!"
#define LANG_MAIN_ERR_SENSOR_WATER "水温传感器错误!"
#define LANG_MAIN_ERR_SENSOR_TANK "釜温度传感器错误!"
#define LANG_MAIN_ERR_SENSOR_ACP "ACP 温度传感器错误!"
#define LANG_MAIN_PROG_UNCHANGED_ALL_DONE "程序未更改: 所有行均已执行."
#define LANG_MAIN_PROG_UNCHANGED_LINE "程序未更改: 行 "
#define LANG_MAIN_PROG_LINE_LOCKED " 不能再修改: 正在执行或已执行."
#define LANG_MAIN_PROFILE_OP_CANCELLED_BUSY "配置操作已取消: runtime state 被占用."
#define LANG_MAIN_NBK_PROG_NOT_SAVED "连续醪塔程序未保存: "
#define LANG_MAIN_MODE_SWITCHED_NOT_SAVED "模式已切换但未保存, 重启将恢复原模式: "
#define LANG_MAIN_SETTINGS_NOT_SAVED "设置未保存: "
#define LANG_MAIN_PROFILE_OP_TERMINAL_NOT_PUBLISHED "配置操作: terminal state 未发布; 需要重启."
#define LANG_MAIN_PROFILE_OP_RECORD_UNAVAILABLE "配置操作: 启动时 record 不可用; 需要重启."
#define LANG_MAIN_EMERGENCY_BUTTON_TRIGGERED "紧急关机! 紧急按钮输入被触发(按钮或与其相连的传感器)."
#define LANG_MAIN_ACP_TEMP_LABEL " ACP 温度 "
#define LANG_MAIN_PRESSURE_LIMIT_EXCEEDED "超过压力上限!"
#define LANG_MAIN_SENSOR_SCAN_REJECTED "传感器扫描被拒绝: 流程正在运行."
#define LANG_MAIN_UNFINISHED_SESSION_MODE "检测到未结束的会话, 模式 "
#define LANG_MAIN_PROGRAM_NUM ", 程序 #"
#define LANG_MAIN_HEATING_NOT_RESUMED_AUTO "; 加热未自动恢复."
#define LANG_MAIN_NBK_PROG_LEN_BAD_NVS "NVS 中连续醪塔程序长度无效"
#define LANG_MAIN_SESSION_INTERRUPTED_LINE "会话被重启中断: 行 "
#define LANG_MAIN_PROGRAM_RESTORED ", 程序已恢复"
#define LANG_MAIN_PROGRAM_NOT_RESTORED ", 程序未恢复"
#define LANG_MAIN_HEATING_NOT_RESUMED ". 加热未恢复."
#define LANG_MAIN_SUVID_HOLD_AT_FAILURE " 故障时低温慢煮累计保温: "
#define LANG_MAIN_CHEESE_SNAPSHOT_CLEARED "快照中的奶酪程序未恢复并已清除. 未设置默认程序."
#define LANG_MAIN_SNAPSHOT_DEFAULT_SET "快照中的程序未恢复, 已设置默认程序."
#define LANG_MAIN_REASON_LABEL " 原因: "
#define LANG_MAIN_EMERGENCY_BUTTON_TASK_NOT_STARTED "紧急关机! 紧急按钮任务未启动"
#define LANG_MAIN_BOOT_WITH_ERRORS "启动时有错误("
#define LANG_MAIN_BOOT_LIMITED_MODE "). 部分功能不可用, 以受限模式运行."
#define LANG_MAIN_EMERGENCY_LOCKOUT "紧急锁定: "
#define LANG_MAIN_EMERGENCY_LOCKOUT_NBK_NVS "紧急锁定: NVS 中的连续醪塔程序已损坏: "
#define LANG_MAIN_EMERGENCY_REGULATOR_TASK_NOT_STARTED "紧急关机! 调压器任务未启动"
#define LANG_MAIN_EMERGENCY_STACK_LOW "紧急关机! 栈剩余空间严重不足"
#define LANG_MAIN_STACK_OVERFLOW_REBOOT "栈溢出. 正在重启"
#define LANG_MAIN_EMERGENCY_TASK_STACK_LOW "紧急关机! 任务栈剩余空间严重不足 "
#define LANG_MAIN_TASK_STACK_LABEL "任务栈 "
#define LANG_MAIN_TASK_STACK_OVERFLOW_REBOOT " 溢出. 正在重启"
#define LANG_MAIN_EMERGENCY_SYSTICKER_HUNG "紧急关机! SysTicker 监督任务卡死"
#define LANG_MAIN_SYSTICKER_HUNG_REBOOT "SysTicker 监督任务卡死. 正在重启"
#define LANG_MAIN_OP_EXPIRED_FORCED "过期操作已被强制结束(reaper)"
#define LANG_MAIN_MIXER_CMD_FAILED "搅拌器指令失败: 执行器未确认状态"
#define LANG_MAIN_NBK_MANUAL_UNAVAILABLE "优化阶段和连续醪塔工作阶段不可手动控制."
#define LANG_MAIN_NBK_BUTTON_ONLY_MANUAL_WORK "该按钮仅在手动设置和连续醪塔工作阶段可用."
#define LANG_MAIN_OPTIMAL_VALUES_SET "已设置最优值: "
#define LANG_MAIN_UNIT_LPH " l/h"
#define LANG_MAIN_NBK_CMD_PUMP_UNAVAILABLE "连续醪塔指令被拒绝: 所选 I2C 泵不可用."
#define LANG_MAIN_NBK_CMD_BAD_SPEED_CAL "连续醪塔指令被拒绝: 速度校准无效."
#define LANG_MAIN_NBK_START_NO_REGULATOR "连续醪塔启动被拒绝: 此版本中调压器不可用."
#define LANG_MAIN_MANUAL_TAKEOFF_PAUSE "手动采出暂停"
#define LANG_MAIN_MODE_FROM_SETTINGS_NOT_ACTIVATED "设置中的模式未激活: "
#define LANG_MAIN_UNAVAILABLE_IN_BUILD "在此固件版本中不可用"
#define LANG_MAIN_CHEESE_FACT_QUEUE_OVERFLOW "F1: 事实队列溢出, 奶酪程序已停止"
#define LANG_MAIN_CHEESE_FLOCCULATION_SAVE_FAILED "无法保存絮凝数据"
// power_regulator.h
#define LANG_PWR_QUEUE_BUSY_RESET_AFTER_OFF "指令队列繁忙: 加热关闭后的 reset 未入队"
#define LANG_PWR_HEAT_REJECTED_TASK_NOT_STARTED "加热被拒绝: 调压器任务未启动"
#define LANG_PWR_HEAT_BLOCKED_EMERGENCY "加热已被紧急保护锁定, 需要重启"
#define LANG_PWR_HEAT_REJECTED_OFF_IN_PROGRESS "加热被拒绝: 正在关闭加热, 请稍后重试"
#define LANG_PWR_HEAT_REJECTED_EXCLUSIVE_OP "加热被拒绝: 独占操作进行中(自检/校准)"
#define LANG_PWR_HEAT_REJECTED_MODE_SWITCH "加热被拒绝: 正在切换模式"
#define LANG_PWR_HEAT_REJECTED_START_PENDING "加热被拒绝: 开启指令已在执行, 请稍后重试"
#define LANG_PWR_CMD_TIMEOUT_HEAT_OFF "调压器指令超时; 加热已关闭"
#define LANG_PWR_START_CMD_FAILED "调压器启动指令失败"
#define LANG_PWR_START_CMD_TIMEOUT_HEAT_OFF "调压器启动指令超时; 加热已关闭"
#define LANG_PWR_START_CMD_SUPERSEDED "调压器启动指令已被新指令明确取消"
#define LANG_PWR_SESSION_ABORTED_REGULATOR_FAILURE "会话已中止: 加热调压器故障. 需要重新启动."
#define LANG_PWR_CMD_TIMEOUT_AT_HEAT_OFF "关闭加热时调压器指令超时"
#define LANG_PWR_OFF_CMD_FAILED "调压器关闭指令失败"
#define LANG_PWR_OFF_CMD_TIMEOUT "调压器关闭指令超时"
#define LANG_PWR_OFF_CMD_SUPERSEDED "调压器关闭指令已被新指令明确取消"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_OFF "本地继电器断开时调压器指令超时"
#define LANG_PWR_NO_REGULATOR_LINK "与调压器失去连接!"
#define LANG_PWR_EMERGENCY_NO_REGULATOR_LINK "紧急关机! 与加热调压器失去连接."
#define LANG_PWR_EMERGENCY_HEATER_CONTROL "紧急关机! 加热器控制错误."
#define LANG_PWR_UNKNOWN_REGULATOR_MODE "未知的调压器模式: "
#define LANG_PWR_START_REJECTED_SAFETY_BARRIER "调压器开启指令被 safety-barrier 拒绝"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_RELEASED "调压器指令超时; 本地继电器已断开"
#define LANG_PWR_BG_APPLY_TIMEOUT "调压器指令后台应用超时"
#define LANG_PWR_BG_APPLY_FAILED "调压器指令后台应用失败"
// crash_handler.ino
#define LANG_CRASH_RST_UNKNOWN "未知的重启原因 (0)"
#define LANG_CRASH_RST_POWERON "上电重启 (1)"
#define LANG_CRASH_RST_EXT "通过 RESET 引脚外部复位 (2)"
#define LANG_CRASH_RST_SW "由 esp_restart() 触发的软件复位 (3)"
#define LANG_CRASH_RST_PANIC "因崩溃或未处理的异常复位 (4)"
#define LANG_CRASH_RST_INT_WDT "因内部看门狗复位 (5)"
#define LANG_CRASH_RST_TASK_WDT "因任务看门狗复位 (6)"
#define LANG_CRASH_RST_WDT "因任一看门狗复位 (7)"
#define LANG_CRASH_RST_DEEPSLEEP "从深度睡眠唤醒后复位 (8)"
#define LANG_CRASH_RST_BROWNOUT "因电压过低复位 (9)"
#define LANG_CRASH_RST_SDIO "因 SDIO 错误复位 (10)"
#define LANG_CRASH_RST_UNKNOWN_CODE "未知原因代码: "
#define LANG_CRASH_EMERGENCY_REBOOT "紧急重启"
// WebServer.ino
#define LANG_WEB_STALE_SETTINGS "设备上的设置已更改. 请刷新页面后重试."
#define LANG_WEB_ADS1115_PH_BLOCKED "ADS1115 不可用: pH 校准已被阻止"
#define LANG_WEB_MODE_UNAVAILABLE_IN_BUILD "此固件版本中该模式不可用"
#define LANG_WEB_INVALID_REQUEST_PARAM "请求参数无效"
#define LANG_WEB_PARAMS_MUST_BE_UNIQUE "数值和文本参数必须唯一"
#define LANG_WEB_WPROGRAM_MUST_BE_TEXT "WProgram 必须是文本参数"
#define LANG_WEB_CLEAR_REQUIRES_CLEAR1 "清除程序要求恰好为 clear=1"
#define LANG_WEB_CLEAR_MUST_BE_SEPARATE "清除程序必须是单独的操作"
#define LANG_WEB_DESCR_INVALID "描述无效"
#define LANG_WEB_DESCR_TOO_LONG "描述超过 250 字节"
#define LANG_WEB_UPDATE_CANCELLED_LOW_SPACE "网页界面更新已取消: 磁盘空间不足"
#define LANG_WEB_UPDATE_INCOMPLETE "网页界面更新未完成, 版本未变"
// Blynk.ino
// Подписи V21 без цифр: приложения берут первое число строки (PIN_SPEC.md §2).
#define LANG_BLYNK_V21_CURRENT "当前:"
#define LANG_BLYNK_V21_TARGET " 目标:"
#define LANG_BLYNK_QUEUE_BUSY_V12 "指令队列繁忙: Blynk V12 指令未入队"
#define LANG_BLYNK_QUEUE_BUSY_RESET "指令队列繁忙: 来自 Blynk 的 reset 未入队"
#define LANG_BLYNK_QUEUE_BUSY_V4 "指令队列繁忙: Blynk V4 指令未入队"
#define LANG_BLYNK_V34_LINE_BEGIN "V34: 日志行("
#define LANG_BLYNK_V34_BYTES_NO_FIT " 字节)无法放入缓冲区("
#define LANG_BLYNK_V34_NOT_SENT "), 未发送"
#define LANG_BLYNK_V35_TRUNCATED_FROM "V35: 会话描述已截断, 从 "
#define LANG_BLYNK_V35_TO " 到 "
#define LANG_BLYNK_V35_BYTES_BUFFER " 字节(缓冲区 "
// lua.h
#define LANG_LUA_CHUNK_TIMEOUT "Lua: 代码块执行因超时而中止"
#define LANG_LUA_SENSOR_WATER "水"
#define LANG_LUA_SENSOR_ACP "ACP"
#define LANG_LUA_SENSOR_TANK "釜"
#define LANG_LUA_SCRIPT1_STOPPED_AFTER "script.lua 已停止, 在 "
#define LANG_LUA_ERRORS_IN_ROW_SEE_ERR " 次连续错误后, 见之前的 ERR"
#define LANG_LUA_SCRIPT1_DISABLED "通用脚本 script.lua 因反复出错已禁用"
#define LANG_LUA_MODE_SCRIPT_BEGIN "模式脚本("
#define LANG_LUA_MODE_SCRIPT_STOPPED_AFTER ") 已停止, 在 "
// Menu.ino
#define LANG_MENU_SETTINGS_NOT_SAVED "菜单设置未保存: "
#define LANG_MENU_QUEUE_BUSY_START "指令队列繁忙: 菜单启动未入队"
#define LANG_MENU_LOG_CREATE_FAILED "创建日志文件出错. 精馏启动已取消."
#define LANG_MENU_DESCR_BUSY "会话描述被占用. 精馏启动已取消."
#define LANG_MENU_LAST_LINE_FINISH "结束最后一行"
#define LANG_MENU_PROGRAM_DONE_SELF_RUN "程序已结束. 全回流("
#define LANG_MENU_MIN_TO_AUTO_OFF " min 后自动断电)."
#define LANG_MENU_STOPPED_BY_USER "已被用户停止"
#define LANG_MENU_LUA_STOP_FAILED "无法停止 Lua: runtime lock 被占用."
#define LANG_MENU_RESET_STOP_UNCONFIRMED "流程已被复位停止: 结束未确认"
// impurity_detector.h
#define LANG_DET_LINE_NUM "行 #"
#define LANG_DET_STOP_PAUSES_RATE_CUT " 次连续停止暂停. 基础采出速度已降至 "
#define LANG_DET_UNIT_LPH_DOT " l/h."
#define LANG_DET_PAUSE_TYPE_BUSY "检测器: 自动暂停类型被占用. 已跳过检查."
#define LANG_DET_PAUSE_TYPE_SET_FAILED "检测器: 无法设置暂停类型."
#define LANG_DET_PAUSE_CRITICAL_TREND "采出暂停: 临界趋势"
#define LANG_DET_CRITICAL_TREND_PAUSE "检测器: 临界趋势! 采出暂停. (趋势: "
#define LANG_DET_NEW_BODY_T "检测器: 设置新的酒心 T (首个酒心程序, 趋势 "
#define LANG_DET_RATE_REDUCTION "检测器: 降低速度 (趋势 "
#define LANG_DET_THRESHOLD ", 阈值: "
// FS.ino
#define LANG_FS_MOUNT_FAILED_FORMATTING "无法挂载文件系统, 正在格式化..."
#define LANG_FS_FORMAT_FAILED "无法格式化文件系统, 请通过 Arduino 上传界面"
#define LANG_FS_ERROR_UPLOAD "文件系统错误! 请通过 Arduino 上传"
#define LANG_FS_LOW_MEMORY_TOTAL "内存即将耗尽! 总计: "
#define LANG_FS_USED ", 已用: "
// Samovar.h
#define LANG_SAMH_ASSERT_WPROGRAM_SIZE "WProgram: 结构体大小异常 - 请检查字段顺序和对齐"
#define LANG_SAMH_PWR_MSG_POWER "功率"
#define LANG_SAMH_PWR_SIGN_W "W"
#define LANG_SAMH_PWR_MSG_VOLTAGE "电压"
#define LANG_SAMH_PWR_SIGN_V "V"
// runtime_helpers.h
#define LANG_RT_WAIT_STEAM "(蒸汽)"
#define LANG_RT_WAIT_PIPE "(塔)"
#define LANG_RT_WAIT_DETECTOR "(检测器)"
#define LANG_RT_EVENT_RING_REINIT "事件日志因损坏已重新初始化"
// valve_buzzer.h
#define LANG_VALVE_OPEN_WATER_SUPPLY "请打开供水!"
#define LANG_VALVE_COOLING_OPENED "冷却水阀已打开!"
#define LANG_VALVE_CLOSE_WATER_SUPPLY "请关闭供水!"
#define LANG_VALVE_COOLING_CLOSED "冷却水阀已关闭!"
// selftest.h
#define LANG_SELF_FINISHED "自检已完成."
#define LANG_SELF_REJECTED "自检被拒绝: 有流程或模式切换正在进行"
#define LANG_SELF_STARTING "正在启动自检."
// sensorinit.h
#define LANG_SENS_UNSUPPORTED_DEFAULT_MODE "默认程序的模式不受支持"
#define LANG_SENS_LUA_STATUS_RESET_FAILED "无法重置 Lua_status: runtime lock 被占用."
#define LANG_SENS_LOG_BUSY_CLOSE_SKIPPED "日志文件被占用: 已跳过关闭"
// I2CStepper.h
#define LANG_I2C_LINK_LOST "与 I2C 步进器失去连接, 地址 "
#define LANG_I2C_LOCAL_STOP "I2C 步进器本地停止, 地址 "
// SPIFFSEditor.h
#define LANG_EDIT_JSON_ESCAPE_TRUNCATED "spiffsEditorJsonEscape: 字符串已截断, 内存不足"
// string_utils.h
#define LANG_STR_JSON_STRING_TRUNCATED "toJsonString: 字符串已截断, 内存不足"
