#pragma once
// Английский перевод прошивки. Правила (проверяет tools/smoke_i18n_firmware.py):
//  - по одной строке #define LANG_<KEY> "text" на каждый ключ TR(KEY, "...") из кода;
//    полнота: нет ключа - ошибка компиляции, лишних ключей быть не должно;
//  - в переводе нет кириллицы;
//  - набор printf-спецификаторов (%d %s %.1f ...) совпадает с русским по порядку;
//  - длина перевода в байтах UTF-8 не больше русской (буферы рассчитаны на русский);
//  - секции ключей идут по файлам с комментарием // <имя файла>.
#define SAMOVAR_LANG_NAME "English"

// nbk.h
#define LANG_NBK_WASH_PROCESSED "Wash processed "
#define LANG_NBK_UNIT_L_SP " l "
#define LANG_NBK_CFG_COLUMN_INERTIA "column inertia In"
#define LANG_NBK_CFG_DELTA_T "dT correction"
#define LANG_NBK_CFG_TANK_TEMP "boiler temperature Tn"
#define LANG_NBK_CFG_FLOOD_PRESSURE "flooding pressure PS"
#define LANG_NBK_CFG_POWER_STEP "power step dM"
#define LANG_NBK_CFG_FEED_STEP "feed step dP"
#define LANG_NBK_CFG_STEAM_LIMIT "vapor temperature limit Tp"
#define LANG_NBK_CFG_MAINS_INPUT_INVALID "mains voltage (input not recognized)"
#define LANG_NBK_CFG_HEATER_INPUT_INVALID "heater resistance (input not recognized)"
#define LANG_NBK_CFG_MAINS_RANGE "mains voltage out of range"
#define LANG_NBK_CFG_HEATER_RANGE "heater resistance out of range"
#define LANG_NBK_CEILING_LOWERED_TO "Pressure ceiling lowered to "
#define LANG_NBK_MM_FLOODING_AT " mm (flooding at "
#define LANG_NBK_MM_CLOSE " mm)"
#define LANG_NBK_SRC_FLOOD_SENSOR "FS"
#define LANG_NBK_SRC_NO_PRESSURE_DATA "no PS data"
#define LANG_NBK_SRC_PRESSURE_SENSOR "PS"
#define LANG_NBK_HEATUP_ACTUATORS_NOT_CONFIRMED "CBC heat-up did not confirm actuator commands."
#define LANG_NBK_SAFE_WAIT "CBC safe wait."
#define LANG_NBK_ACTUATOR_CONFIRM_TIMEOUT "CBC actuator confirmation timeout. Safe wait."
#define LANG_NBK_ACTUATOR_CMD_HEATING_OFF "CBC actuator command rejected while heating is off."
#define LANG_NBK_REGULATOR_NOT_CONFIRMED "Regulator did not confirm CBC command. Safe wait."
#define LANG_NBK_PUMP_NOT_CONFIRMED "CBC pump did not confirm command. Heating off."
#define LANG_NBK_WORK_RESUMED "CBC Work resumed."
#define LANG_NBK_WARMUP_POWER_FEED_SET "CBC warm-up power and feed set."
#define LANG_NBK_MODE_NAME "CBC"
#define LANG_NBK_SENSOR_VAPOR "vapor"
#define LANG_NBK_SENSOR_BOILER "boiler"
#define LANG_NBK_RESTART_IMPOSSIBLE "CBC restart impossible: "
#define LANG_NBK_HEATING_NOT_OFF_YET "heating is not off yet"
#define LANG_NBK_PUMP_STOP_NOT_CONFIRMED "pump did not confirm stop"
#define LANG_NBK_SESSION_CONFIG_NOT_CAPTURED "CBC session configuration not captured."
#define LANG_NBK_PROGRAM_LINE_OUT_OF_RANGE "CBC program error: line number out of range"
#define LANG_NBK_PROGRAM_LINE_NOT_SET "CBC program error: line not set"
#define LANG_NBK_WARMUP_TOO_HIGH_PREFIX "Warm-up values too high: "
#define LANG_NBK_AND_OR_FEED_PROGRAM_STOP " and/or feed! Program stopped."
#define LANG_NBK_AFTER_FLOOD_REDUCE_REJECTED "CBC actuator reduction after flooding not accepted."
#define LANG_NBK_FLOODING_BY "Flooding by "
#define LANG_NBK_FEED_THIRD_POWER_HALF ". Feed 1/3, power 1/2."
#define LANG_NBK_BEFORE_OPT_SETUP_PREFIX "Even before Optimization starts, the Setup values of "
#define LANG_NBK_AND_FEED_TOO_HIGH_STOP " and feed are too high. Stopped."
#define LANG_NBK_MANUAL_WORK_WAIT_PREFIX "While waiting for manual switch to Work, the values of "
#define LANG_NBK_OPT_INITIAL_REJECTED "CBC Optimization initial parameters not accepted."
#define LANG_NBK_OPT_ACCEPTED_FROM "Optimization accepted from: "
#define LANG_NBK_UNIT_LPH_SP " l/h "
#define LANG_NBK_SET_PARAMS_PREFIX "The values of "
#define LANG_NBK_AND_SPEED_TOO_HIGH_OPT_STOP " and Speed are too high - optimization impossible. Stopped."
#define LANG_NBK_TN_REFINED_BY_SENSOR "Reference Tn refined by stillage sensor: "
#define LANG_NBK_OPT_NO_FLOOD_SENSOR "Optimization impossible - no flooding sensor. Set the needed parameters manually in the Work stage program and press the Next program button. After 10 minutes the process will switch to safe wait (heating and feed off)."
#define LANG_NBK_C_IN_SETTINGS " °C (in settings "
#define LANG_NBK_FEED_LIMIT_REACHED "Feed limit reached ("
#define LANG_NBK_LPH_RESULT_COLON " l/h). Result: "
#define LANG_NBK_OPT_TB_GE_TN "Optimization: Tb >= Tn ("
#define LANG_NBK_INCREASING_FEED_ITER "), increasing feed. Iteration "
#define LANG_NBK_POWER_LIMIT_REACHED "Power limit reached. ("
#define LANG_NBK_W_RESULT_COLON " W.). Result: "
#define LANG_NBK_UNIT_LPH_DOT " l/h."
#define LANG_NBK_OPT_NOT_FOUND_TB_TN "Optimum not found: Tb did not reach Tn ("
#define LANG_NBK_NO_ITERATION_CHECK_TB ") on any iteration. Check the Tb sensor."
#define LANG_NBK_OPT_TP_LT_TPMIN "Optimization: Tp < Tp min("
#define LANG_NBK_INCREASING "), increasing "
#define LANG_NBK_ITERATION_SP ". Iteration "
#define LANG_NBK_OPT_TB_LT_TN "Optimization: Tb < Tn("
#define LANG_NBK_OPT_CORRECTION_REJECTED "CBC Optimization correction not accepted."
#define LANG_NBK_ITER_LIMIT_RESULT "Iteration limit reached. Result: "
#define LANG_NBK_UNIT_LPH " l/h"
#define LANG_NBK_TEMP_REDUCE_FEED_HEATING "Temporary feed and heating reduction."
#define LANG_NBK_WORK_WASH_SPILL "Work: wash spill (Tb "
#define LANG_NBK_FEED_REDUCED_BY "), feed reduced by "
#define LANG_NBK_TO_COLON ", to: "
#define LANG_NBK_WORK_TB_LT_TN_DT "Work: Tb < Tn-dT ("
#define LANG_NBK_REDUCING_FEED_BY "), reducing feed by "
#define LANG_NBK_WORK_TP_BELOW_LIMIT "Work: Tp below limit ("
#define LANG_NBK_WORK_PRESSURE "Work: pressure "
#define LANG_NBK_GE_CEILING " >= ceiling "
#define LANG_NBK_MM_REDUCING_FEED_BY " mm, reducing feed by "
#define LANG_NBK_WORK_TB_GT_TN_DT "Work: Tb > Tn+dT ("
#define LANG_NBK_INCREASING_FEED_BY "), increasing feed by "
#define LANG_NBK_WORK_CORRECTION_REJECTED "CBC Work correction not accepted."
#define LANG_NBK_REPEAT_FLOODING_BY "Repeated flooding by "
#define LANG_NBK_DURING_PAUSE_EXTENDED " during pause. Pause extended, power halved."
#define LANG_NBK_REPEAT_POWER_REDUCE_REJECTED "CBC repeated power reduction not accepted."
#define LANG_NBK_WORK_RESUME_REJECTED "CBC Work resume not accepted."
#define LANG_NBK_WORK_RESUME_AFTER_FLOOD "Work: resuming after flooding, corrected parameters: "
#define LANG_NBK_WORK_CONTINUE_AFTER_PAUSE "Work: continuing the cycle after pause."
#define LANG_NBK_RESUME_IMPOSSIBLE_EMERGENCY "CBC Work resume impossible: emergency latched."
#define LANG_NBK_RESUME_IMPOSSIBLE_NO_SNAPSHOT "CBC Work resume impossible: no session configuration snapshot."
#define LANG_NBK_RESUME_REJECTED_CMD_BUSY "CBC Work resume rejected: previous actuator command is still running."
#define LANG_NBK_WORK_WAITS_HEATING_OFF "CBC Work is waiting for heating to switch off."
#define LANG_NBK_RESUME_UNAVAILABLE_PUMP_STOP "CBC Work resume unavailable: pump stop was not confirmed."
#define LANG_NBK_HEATING_NOT_ON_RESUME "CBC heating not on when trying to resume Work."
#define LANG_NBK_RESUME_PARAMS_REJECTED "CBC Work resume: parameters not accepted by actuators."
#define LANG_NBK_WORK_RESUMED_M "CBC Work resumed: M="
#define LANG_NBK_COMMA_P ", P="
#define LANG_NBK_START_REJECTED_NO_REGULATOR "CBC start rejected: power regulator unavailable in this build."
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_NO_REGULATOR "CBC pump stop in the unavailable configuration not confirmed."
#define LANG_NBK_LINE_SWITCH_HEATING_STARTING "CBC line switch rejected: heating start not finished yet"
#define LANG_NBK_PROGRAM_NOT_SET "CBC program not set"
#define LANG_NBK_GOTO_WORK_NO_SNAPSHOT "CBC switch to Work rejected: no session configuration snapshot."
#define LANG_NBK_AUTO_WORK_IMPOSSIBLE "CBC auto-entry to Work impossible: heating is off or optimum not found."
#define LANG_NBK_AUTO_WORK_PARAMS_REJECTED "Auto-entry to Work parameters not accepted by CBC actuators."
#define LANG_NBK_OPT_FINISHED "Optimization finished"
#define LANG_NBK_BY_PRESSURE " by pressure ("
#define LANG_NBK_COLON_MO ": Mo="
#define LANG_NBK_COMMA_PO ", Po="
#define LANG_NBK_LPH_PAUSE " l/h. Pause "
#define LANG_NBK_S_THEN_WORK " s, then Work."
#define LANG_NBK_AUTO_WORK_FORBIDDEN "Automatic switch to CBC Work is forbidden. Set Power/Speed of line W and press 'Next program'."
#define LANG_NBK_LINE_W_NEEDS_NONZERO "Line W requires non-zero Power and Speed, or saved optimal values."
#define LANG_NBK_WORK_UNAVAILABLE_PUMP_STOP "CBC Work unavailable: pump stop was not confirmed."
#define LANG_NBK_HEATING_NOT_ON_EXPLICIT_WORK "CBC heating not on after explicit switch to Work command."
#define LANG_NBK_HEATING_OFF_WORK_REJECTED "CBC heating is off. Switch to Work rejected."
#define LANG_NBK_LINE_W_PARAMS_REJECTED "Line W parameters not accepted by CBC actuators."
#define LANG_NBK_EXPLICIT_WORK_ACCEPTED_M "Explicit switch to CBC Work accepted: M="
#define LANG_NBK_W_COMMA_P " W, P="
#define LANG_NBK_SAFE_WAIT_STOPPED_BY_OPERATOR "Safe wait stopped by operator."
#define LANG_NBK_SAFE_WAIT_SESSION_ENDED "CBC safe wait: session ended by operator command."
#define LANG_NBK_START_HEATING_OFF_PENDING "Heating shutdown not finished yet. CBC start canceled."
#define LANG_NBK_HEATING_OFF_GOTO_LINE "CBC heating is off. Moving to line #"
#define LANG_NBK_CANCELLED_DOT " canceled."
#define LANG_NBK_START_REJECTED_BAD_SETTING "CBC start rejected: invalid setting - "
#define LANG_NBK_START_LOG_FILE_ERROR "Log file creation error. CBC start canceled."
#define LANG_NBK_PROGRAM_STARTED_WARMUP "CBC program started. Warm-up"
#define LANG_NBK_NO_FLOOD_SENSORS_WARNING "Attention: no flooding sensors (FS off, PS not responding). Flooding protection is not working."
#define LANG_NBK_START_SESSION_BUSY "Session description is busy. CBC start canceled."
#define LANG_NBK_GOTO_LINE "Moving to line #"
#define LANG_NBK_TYPE_SP ". Type: "
#define LANG_NBK_START_HEATING_NOT_ON "CBC heating not on. Start canceled."
#define LANG_NBK_HEATUP_TRANSITION_STARTED "CBC heat-up transition started."
#define LANG_NBK_MANUAL_NEEDS_NONZERO "CBC Manual setup requires non-zero power and feed."
#define LANG_NBK_MANUAL_PARAMS_REJECTED "CBC Manual setup parameters not accepted."
#define LANG_NBK_PROGRAM_LINE_EMPTY "CBC program error: empty program line"
#define LANG_NBK_STEAM_98_WASH_OUT "Vapor temperature above 98°C for 60 seconds. The wash has run out. CBC program finished."
#define LANG_NBK_EMERGENCY_WASH_OUT "Emergency shutdown! Failed to finish the CBC program normally (wash ran out)"
#define LANG_NBK_TP_ROSE_BY "Tp rose by "
#define LANG_NBK_C_RELATIVE_TO_MIN " °C relative to the minimum "
#define LANG_NBK_C_WASH_ENDING " °C - wash is running out. CBC program finished."
#define LANG_NBK_EMERGENCY_TP_RISE "Emergency shutdown! Failed to finish the CBC program normally (vapor Tp rise)"
#define LANG_NBK_STEAM_OVER_LIMIT_MANUAL "T vapor above the limit for 60 seconds on Manual setup. Steam generator may be running dry. CBC program finished."
#define LANG_NBK_EMERGENCY_STEAM_OVERHEAT_MANUAL "Emergency shutdown! Failed to finish the CBC program normally (vapor overheat on Manual setup)"
#define LANG_NBK_INSUFFICIENT_COOLING "Insufficient cooling! Stopped."
#define LANG_NBK_PRESSURE_SENSOR_FAILED "Pressure sensor failure! No readings for over 60 seconds. Stopped."
#define LANG_NBK_LOG_BUSY_CLOSE_SKIPPED "Log file is busy: close not done"
#define LANG_NBK_HEATUP_TRANSITION_ABORTED "CBC heat-up transition aborted."
#define LANG_NBK_HEATING_START_ABORTED "CBC heating start aborted: start condition violated, process stopped."
#define LANG_NBK_HEATUP_NEEDS_CONFIRMED_FEED "CBC heat-up requires a confirmed non-zero feed."
#define LANG_NBK_RUN_FINISHED "CBC run finished"
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_ON_FINISH "CBC pump stop not confirmed at finish."
#define LANG_NBK_AVG_SESSION_RATE "at an average session rate of "
#define LANG_NBK_AND_AVG_FEED_RATE "and an average feed rate of "
#define LANG_NBK_OVER_COLON "over: "
#define LANG_NBK_UNIT_H_DOT " h."
#define LANG_NBK_RUN_FINISHED_DOT "CBC run finished."
#define LANG_NBK_RUN_ABORTED_EMERGENCY "CBC run aborted by emergency."
#define LANG_NBK_FLOOD_FEED_REDUCE_UNCONFIRMED "CBC feed reduction on flooding not confirmed."
#define LANG_NBK_EMERGENCY_FLOODING "Emergency shutdown! Failed to finish the CBC program normally (flooding)"
#define LANG_NBK_FLOOD_ACTUATOR_REDUCE_REJECTED "CBC actuator reduction on flooding not accepted."
// BK.h
#define LANG_BK_WORK_POWER_APPLIED "BC working power applied."
#define LANG_BK_PROGRAMS_DONE_CONTINUE "Programs finished, take-off continues"
#define LANG_BK_LUA_LINE_SCRIPT_NOT_STARTED "Lua error: line script not started"
#define LANG_BK_PROGRAM_L_NEEDS_LUA "Program error: type L requires USE_LUA"
#define LANG_BK_GOTO_PROGRAM_LINE "Moving to program line #"
#define LANG_BK_DEPHLEGMATOR_WATER_MANUAL "Dephlegmator water: manual control"
#define LANG_BK_PUMP_CONTROL_UNSUPPORTED "Pump control is not supported by your hardware"
#define LANG_BK_MODE_NAME "BC"
#define LANG_BK_SENSOR_BOILER "boiler"
#define LANG_BK_SENSOR_VAPOR "vapor"
#define LANG_BK_START_NO_TANK_SENSOR "BC not started: boiler sensor not assigned or not responding"
#define LANG_BK_START_NEEDS_STEAM_SENSOR "BC not started: program requires a vapor sensor"
#define LANG_BK_START_LOG_FILE_ERROR "Log file creation error. BC start canceled."
#define LANG_BK_START_SESSION_BUSY "Session description is busy. BC start canceled."
#define LANG_BK_HEATING_ON "BC heating on"
#define LANG_BK_WAIT_WORK_POWER "Waiting for BC working power."
#define LANG_BK_LUA_TIMEOUT "Lua did not finish the operation before timeout"
#define LANG_BK_LUA_FAILED "Lua finished with an error"
#define LANG_BK_RUN_FINISHED_DOT "BC run finished."
#define LANG_BK_RUN_FINISHED "BC run finished"
// distiller.h
#define LANG_DIST_NO_ALCOHOL_LEFT "No alcohol left in the boiler"
#define LANG_DIST_ABV_UNAVAILABLE "ABV unavailable: percent line continues"
#define LANG_DIST_MODE_NAME "Distillation"
#define LANG_DIST_SENSOR_BOILER "boiler"
#define LANG_DIST_START_NO_TANK_SENSOR "Distillation not started: boiler sensor not assigned or not responding. Open settings and check the boiler sensor binding."
#define LANG_DIST_START_LOG_FILE_ERROR "Log file creation error. Distillation start canceled."
#define LANG_DIST_START_SESSION_BUSY "Session description is busy. Distillation start canceled."
#define LANG_DIST_HEATING_ON "Distiller heating on"
#define LANG_DIST_LUA_TIMEOUT "Lua did not finish the operation before timeout"
#define LANG_DIST_LUA_FAILED "Lua finished with an error"
#define LANG_DIST_FINISHED "Distillation finished."
#define LANG_DIST_TOTAL_TIME " Total time: "
#define LANG_DIST_UNIT_MIN " min."
#define LANG_DIST_PROGRAMS_DONE_CONTINUE "Programs finished, take-off continues"
#define LANG_DIST_LUA_LINE_SCRIPT_NOT_STARTED "Lua error: line script not started"
#define LANG_DIST_PROGRAM_L_NEEDS_LUA "Program error: type L requires USE_LUA"
#define LANG_DIST_GOTO_PROGRAM_LINE "Moving to program line #"

// logic.h
#define LANG_LOGIC_PRG_NUM "Line #"
#define LANG_LOGIC_PROG_LINE_START "Program: start of line #"
#define LANG_LOGIC_PROG_LINE_START_LUA "Program: start of line #"
#define LANG_LOGIC_TAKEOFF_TO_CONTAINER ", take-off to container "
#define LANG_LOGIC_I2C_PUMP_CMD_HEAD "I2C pump above PC: command '"
#define LANG_LOGIC_I2C_PUMP_CMD_TAIL "' not confirmed after 10 attempts."
#define LANG_LOGIC_LUA_OP_DONE "Lua operation completed"
#define LANG_LOGIC_LUA_OP_NOT_DONE "Lua operation not completed"
#define LANG_LOGIC_LUA_TIMEOUT "Lua did not finish the operation before timeout"
#define LANG_LOGIC_LUA_OP_FAILED "Lua operation failed"
#define LANG_LOGIC_LUA_ERROR "Lua finished with an error"
#define LANG_LOGIC_AUTOPAUSE_BUSY_SKIP "Auto pause type is busy. Take-off check skipped."
#define LANG_LOGIC_PAUSE_SET_FAIL_HEAD "Could not set pause on "
#define LANG_LOGIC_PAUSE_TYPE_BUSY_TAIL ": pause type is busy."
#define LANG_LOGIC_AUTOPAUSE_TAIL "Take-off auto pause"
#define LANG_LOGIC_PAUSE_BY "Pause on "
#define LANG_LOGIC_RESUME_AFTER_AUTOPAUSE "Resuming take-off after auto pause"
#define LANG_LOGIC_TAKEOFF_RESUMED "Take-off resumed"
#define LANG_LOGIC_LABEL_T_STEAM "T vapor"
#define LANG_LOGIC_LABEL_T_PIPE "T column"
#define LANG_LOGIC_DETECTOR_RESUME "Detector: resuming take-off after pause"
#define LANG_LOGIC_PUMP_CAL_BAD_STEPS "Pump calibration error: invalid step count"
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_HEAD "Pump calibration not saved: "
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_TAIL ". Result lost, repeat the calibration."
#define LANG_LOGIC_ACTION_PAUSE "pause"
#define LANG_LOGIC_ACTION_RESUME "resume"
#define LANG_LOGIC_ACTION_SPEED "speed"
#define LANG_LOGIC_I2C_PUMP_SPEED_RANGE "I2C pump: speed outside its limits, previous one kept."
#define LANG_LOGIC_MANUAL_PAUSE_TAKEOFF "Manual take-off pause"
#define LANG_LOGIC_MANUAL_PAUSE_MASH "Manual mashing pause"
#define LANG_LOGIC_MASH_PAUSE_NEXT_STEP "Pause will be applied at the next mashing step."
#define LANG_LOGIC_MASH_PAUSED "Mashing paused."
#define LANG_LOGIC_AUTOPAUSE_RESET_FAIL "Could not reset auto pause type."
#define LANG_LOGIC_MASH_RESUMED_TAIL "Mashing resumed"
#define LANG_LOGIC_MASH_RESUMED_MSG "Mashing resumed."
#define LANG_LOGIC_DIST_MODE_SEP "; Distillation mode"
#define LANG_LOGIC_DIST_PROGRAMS_DONE "Programs done, take-off until boiler T "
#define LANG_LOGIC_DIST_MODE_DEG "°; Distillation mode"
#define LANG_LOGIC_DIST_ROW_LEFT "; Line: remaining "
#define LANG_LOGIC_OF_APPROX " of ~"
#define LANG_LOGIC_UNIT_MIN " min"
#define LANG_LOGIC_DIST_ROW_FORECAST_WAIT "; Line forecast: waiting for data"
#define LANG_LOGIC_DIST_PROCESS_LEFT "; Process to DistTemp, remaining:"
#define LANG_LOGIC_DIST_TOTAL "; Total:"
#define LANG_LOGIC_DIST_PROCESS_FORECAST_WAIT "; Process forecast: waiting for boiling/data"
#define LANG_LOGIC_BK_MODE "BC mode"
#define LANG_LOGIC_NBK_STAGE_H "Warm-up"
#define LANG_LOGIC_NBK_STAGE_S "Setup"
#define LANG_LOGIC_NBK_STAGE_O "Optimization"
#define LANG_LOGIC_NBK_STAGE_W "Work"
#define LANG_LOGIC_BEER_ON_PAUSE "Paused; "
#define LANG_LOGIC_BEER_WAIT_SKIP_COOL "Waiting for cooling skip confirmation; "
#define LANG_LOGIC_BEER_HEAT_TO_MALT "Heating to malt addition temperature"
#define LANG_LOGIC_CUR_T "; Current T: "
#define LANG_LOGIC_BEER_WAIT_MALT "Waiting for malt addition"
#define LANG_LOGIC_BEER_PAUSE "Pause "
#define LANG_LOGIC_BEER_DEG_HEATING "°; Heating"
#define LANG_LOGIC_BEER_COOL_TO "Cooling to "
#define LANG_LOGIC_BEER_WAIT_PRESS_NEXT "Waiting. Press 'Next program'; "
#define LANG_LOGIC_BEER_AUTOCAL "Auto-calibration. After completion "
#define LANG_LOGIC_BEER_AUTOCAL_POWER_OFF "power will be turned off"
#define LANG_LOGIC_BEER_AUTOCAL_NEXT_LINE "moving to the next line"
#define LANG_LOGIC_BEER_BOIL_HEATING "Boil - heating"
#define LANG_LOGIC_BEER_BOIL "Boil "
#define LANG_LOGIC_BEER_FERM_HOLD "Fermentation; Hold T="
#define LANG_LOGIC_CUR_SHORT "; Cur: "
#define LANG_LOGIC_PAREN_HEATING " (Heating)"
#define LANG_LOGIC_PAREN_THERMOSTAT " (Thermostat)"
#define LANG_LOGIC_BEER_FERM_STOPPED "Fermentation (stopped)"
#define LANG_LOGIC_RUNNING_LUA_SCRIPT "Running Lua script"
#define LANG_LOGIC_PROGRESS "; Progress: "
#define LANG_LOGIC_STATUS_OFF "Off"
#define LANG_LOGIC_PAREN_ERROR "(error)"
#define LANG_LOGIC_AUTOPAUSE_READ_FAIL "Could not read auto pause type."
#define LANG_LOGIC_PAUSE_SP " pause "
#define LANG_LOGIC_RESUME_IN ". Continuing in "
#define LANG_LOGIC_UNIT_SEC " s."
#define LANG_LOGIC_PROGRAM_DONE_STATUS "Program execution complete"
#define LANG_LOGIC_STATUS_CALIBRATION "Calibration"
#define LANG_LOGIC_STATUS_PAUSE "Pause"
#define LANG_LOGIC_SUVID_HOLD "Sous-vide; Hold T="
#define LANG_LOGIC_DEG_CUR "°; Cur: "
#define LANG_LOGIC_SUVID_HOLD_TIME "; Hold: "
#define LANG_LOGIC_COLUMN_HEATUP "Column heat-up"
#define LANG_LOGIC_HEATUP_DONE_STAB "Heat-up complete. Stabilization/total reflux"
#define LANG_LOGIC_STAB_DONE "Stabilization complete/total reflux"
#define LANG_LOGIC_LEFT "; Remaining:"
#define LANG_LOGIC_BODY_T_STEAM ";T body vapor:"
#define LANG_LOGIC_BODY_T_PIPE ";T body column:"
#define LANG_LOGIC_PUMP_NOT_CALIBRATED "Pump is not calibrated (steps per ml = 0). Rectification cannot start."
#define LANG_LOGIC_RECT_PROG_LINE_UNSET "Rectification program error: line not set"
#define LANG_LOGIC_RECT_PROG_FIRST_LINE "Program error: the first line must set absolute power/voltage. Rectification cannot start."
#define LANG_LOGIC_PROG_ERR_LINE "Program error: line "
#define LANG_LOGIC_PROG_LINE_NEVER_ENDS " will never finish (volume and temperature not set)"
#define LANG_LOGIC_ACTION_PROGRAM_END "program end"
#define LANG_LOGIC_PROGRAM_FINISHED "Program finished"
#define LANG_LOGIC_LOG_BUSY_CLOSE_SKIPPED "Log file busy: close skipped"
#define LANG_LOGIC_PROGRAM_DONE_MSG "Program execution complete."
#define LANG_LOGIC_LUA_LINE_SCRIPT_NOT_STARTED "Lua error: line script not started"
#define LANG_LOGIC_NEXT_LINE "Moving to the next line"
#define LANG_LOGIC_LUA_OP_STARTED "Lua operation started"
#define LANG_LOGIC_PROG_TYPE_L_NEEDS_LUA "Program error: type L requires USE_LUA"
#define LANG_LOGIC_ACTION_LINE_START "line start "
#define LANG_LOGIC_PROG_LINE_SPEED "Program: line speed #"
#define LANG_LOGIC_SPEED_OVER_PUMP_LIMIT " l/h) exceeds the pump limit, limited to "
#define LANG_LOGIC_UNIT_LPH_DOT " l/h."
#define LANG_LOGIC_COMMA_PAUSE ", pause "
#define LANG_LOGIC_PROGRAM_PAUSE "Program pause"
#define LANG_LOGIC_NEW_BODY_T_STEAM "New body T: vapor = "
#define LANG_LOGIC_COMMA_PIPE_EQ ", column = "
#define LANG_LOGIC_BODY_T_SET_FAIL "Cannot set body T."
#define LANG_LOGIC_BOILING_STARTED_ABV "Boiling started in the boiler! ABV "
#define LANG_LOGIC_BOILING_STARTED "Boiling started in the boiler!"
#define LANG_LOGIC_WETTING_START "Column packing wetting started. Watch the reflux level!"
#define LANG_LOGIC_WETTING_OK "Column packing wetted successfully!"
#define LANG_LOGIC_WETTING_TIMEOUT "Maximum wetting time exceeded. Wetting failed - stop the process manually."
#define LANG_LOGIC_WETTING_VOLT_RAMP_START "Starting gradual voltage reduction"
#define LANG_LOGIC_WETTING_VOLT_TO "Reducing voltage to "
#define LANG_LOGIC_WETTING_MIN_VOLT "Minimum voltage reached: "
#define LANG_LOGIC_WETTING_WAIT_SENSOR ". Waiting for the sensor to trigger."
#define LANG_LOGIC_WETTING_MIN_VOLT_TIMEOUT "Wait time at minimum voltage exceeded. Wetting failed - stop the process manually."
#define LANG_LOGIC_WETTING_NO_SENSOR "Reflux level sensor not installed, packing wetting impossible"
// alarm.h
#define LANG_ALARM_SENSORS_UNASSIGNED "Sensors not assigned. Open settings and assign the vapor, water and boiler sensors."
#define LANG_ALARM_EMERGENCY_STOP "Emergency shutdown!"
#define LANG_ALARM_COOLING_HOLD_3MIN "Cooling will run for 3 more minutes, then close."
#define LANG_ALARM_EMERGENCY_STOP_TAIL "Emergency shutdown"
#define LANG_ALARM_EMERGENCY_STOP_SP "Emergency shutdown! "
#define LANG_ALARM_NO_SENSOR_DATA ": no sensor data: "
#define LANG_ALARM_RECT_SENSORS_UNASSIGNED "Emergency shutdown! Rectification: sensors not assigned"
#define LANG_ALARM_MODE_RECT "Rectification"
#define LANG_ALARM_SENSOR_STEAM "vapor"
#define LANG_ALARM_SENSOR_TANK "boiler"
#define LANG_ALARM_FLOOD_SENSOR "Flooding sensor triggered!"
#define LANG_ALARM_REDUCING_FROM " reducing from "
#define LANG_ALARM_RAISING_TO " raising to "
#define LANG_ALARM_OVERTEMP_STEAM " Vapor"
#define LANG_ALARM_OVERTEMP_WATER " Water"
#define LANG_ALARM_OVERTEMP_ACP " ACP"
#define LANG_ALARM_TANK_LIMIT_FINISHED "Boiler maximum temperature limit. Program finished."
#define LANG_ALARM_TANK_LIMIT_FINISH_FAIL "Emergency shutdown! Could not finish the program normally on boiler temperature"
#define LANG_ALARM_MAX_TEMP_EXCEEDED "Emergency shutdown! Maximum temperature exceeded:"
#define LANG_ALARM_WATER_CRIT_SUPPLY_ERR "Critical water temperature! Water supply error. "
#define LANG_ALARM_HEATUP_DONE_STAB "Heat-up complete. Stabilization/total reflux."
#define LANG_ALARM_ABV "ABV "
#define LANG_ALARM_STAB_DONE_STABLE "Stabilization complete, the column is running stably."
// mode_switch.h
#define LANG_MSW_I2C_MIXER_STOP "I2C mixer did not confirm stop"
#define LANG_MSW_I2C_PUMP_STOP "I2C pump did not confirm stop"
#define LANG_MSW_STEPPER_STOP "stepper did not stop"
#define LANG_MSW_VALVE_CLOSE "valve did not close"
#define LANG_MSW_MIXER_STOP "mixer did not stop"
#define LANG_MSW_COOLING_PUMP_STOP "cooling pump did not stop"
#define LANG_MSW_PUMP_CAL_NOT_DONE "pump calibration not finished"
#define LANG_MSW_HEATING_NOT_CONFIRMED "heating not confirmed"
#define LANG_MSW_ACTUATOR_NOT_CONFIRMED "actuator not confirmed"
#define LANG_MSW_FORCE_COMPLETED "Mode switch force-completed: "
#define LANG_MSW_LUA_NOT_CONFIRMED "Lua not confirmed"
#define LANG_MSW_QUEUE_NOT_CONFIRMED "queue not confirmed"
#define LANG_MSW_PENDING_CMDS_CANCELLED "Pending control commands canceled by mode switch"
#define LANG_MSW_READINESS_NOT_CONFIRMED "readiness not confirmed"
#define LANG_MSW_LOG_NOT_CONFIRMED "log not confirmed"
#define LANG_MSW_POWER_TRANSITION_NOT_CONFIRMED "power transition not confirmed"
#define LANG_MSW_NBK_TRANSITION_NOT_CONFIRMED "CBC transition not confirmed"
#define LANG_MSW_HEATING_START_NOT_CONFIRMED "heating start not confirmed"
#define LANG_MSW_SELF_TEST_NOT_CONFIRMED "self-test not confirmed"
#define LANG_MSW_OWNER_NOT_CONFIRMED "mode owner not confirmed"
#define LANG_MSW_LUA_NOT_RELOADED "Lua script not reloaded"
#define LANG_MSW_PROFILE_NOT_SAVED "profile not saved"
// mode_common.h
#define LANG_MCOM_SENSOR_WATER "water"
#define LANG_MCOM_SENSOR_ACP "ACP"
#define LANG_MCOM_WATER_SUPPLY_STOPPED "Emergency shutdown! Water supply stopped."
#define LANG_MCOM_OVERTEMP_WATER " Water"
#define LANG_MCOM_OVERTEMP_ACP " ACP"
#define LANG_MCOM_MAX_TEMP_EXCEEDED "Emergency shutdown! Maximum temperature exceeded:"
#define LANG_MCOM_WATER_HIGH_HEAD "High water temperature: "
#define LANG_MCOM_WATER_WARN_THRESHOLD "°C (warning threshold "
#define LANG_MCOM_CHECK_COOLING_DOT "°C). Check cooling."
#define LANG_MCOM_ACP_HIGH_HEAD "High ACP temperature: "
#define LANG_MCOM_ACP_THRESHOLD "°C (threshold "
#define LANG_MCOM_CHECK_COOLING_BANG "°C)! Check cooling."
#define LANG_MCOM_WATER_CRIT_REDUCING "Critical water temperature! Reducing "
#define LANG_MCOM_FROM ": "
#define LANG_MCOM_LOG_BUSY_CLOSE_SKIPPED "Log file busy: close skipped"
#define LANG_MCOM_HEATING_LATCHED "Heating is blocked by emergency protection, reboot required"
#define LANG_MCOM_HEATING_OFF_PENDING "Heating shutdown is not finished yet. Start canceled."
#define LANG_MCOM_HEATING_NOT_RESUMED "Heating was not resumed automatically. A repeated start command is required."
// mode_registry.h
#define LANG_MREG_NAME_DIST "distillation"
#define LANG_MREG_NAME_BEER "beer"
#define LANG_MREG_NAME_BK "BC"
#define LANG_MREG_NAME_NBK "CBC"
#define LANG_MREG_NAME_CHEESE "cheesemaking"
#define LANG_MREG_UNAVAILABLE_NO_REGULATOR "Not available in this firmware build: no power regulator"
#define LANG_MREG_UNAVAILABLE_NO_LUA "Not available in this firmware build: Lua is not enabled"
#define LANG_MREG_START_REJECTED_SWITCH "Start command rejected: mode switch not finished yet"
#define LANG_MREG_START_UNAVAILABLE_MODE "Start command unavailable in the current mode"
#define LANG_MREG_QUEUE_BUSY_START "Command queue busy: start "
#define LANG_MREG_NOT_QUEUED " not queued"
#define LANG_MREG_STATUS_MISMATCH "Status does not belong to the current mode - tick skipped, check mode sync"

// beer.h
#define LANG_BEER_ADD_HOPS "Add hops!"
#define LANG_BEER_ESTOP_COOLING_OPEN "Emergency shutdown! Failed to open cooling"
#define LANG_BEER_ESTOP_COOLING_SAFE "Emergency shutdown! Failed to return cooling to safe state"
#define LANG_BEER_ESTOP_COOL_PUMP_ON "Emergency shutdown! Failed to turn on cooling pump"
#define LANG_BEER_ESTOP_COOL_PUMP_OFF "Emergency shutdown! Failed to turn off cooling pump"
#define LANG_BEER_ESTOP_COOLING_RESTORE "Emergency shutdown! Failed to return cooling to working state"
#define LANG_BEER_ESTOP_COOLING_CLOSE "Emergency shutdown! Failed to close cooling"
#define LANG_BEER_SENSOR_TANK "boiler"
#define LANG_BEER_SENSOR_WATER "water"
#define LANG_BEER_SENSOR_PIPE "column"
#define LANG_BEER_SENSOR_STEAM "vapor"
#define LANG_BEER_SENSOR_ACP "ACP"
#define LANG_BEER_ERR_ROW_NOT_SET "Beer program error: line not set"
#define LANG_BEER_ERR_BAD_STAGE_TYPE "Program error: invalid stage type in line "
#define LANG_BEER_ERR_PROGRAM_PREFIX "Program error: "
#define LANG_BEER_ERR_PROGRAM "Program error"
#define LANG_BEER_IN_LINE " in line "
#define LANG_BEER_ERR_BAD_TEMP_SENSOR "Program error: invalid temperature sensor in line "
#define LANG_BEER_ERR_I2C_PUMP_LINE "I2C pump unavailable in line "
#define LANG_BEER_ERR_I2C_PUMP_RELAY_LINE "I2C pump relay unavailable in line "
#define LANG_BEER_ERR_I2C_MIXER_LINE "I2C mixer unavailable in line "
#define LANG_BEER_MODE_NAME "Beer"
#define LANG_BEER_START_HEAT_OFF_PENDING "Heating shutdown not finished yet. Mashing start canceled."
#define LANG_BEER_START_SAFETY_LATCH "Heating safety latch is active. Mashing start canceled."
#define LANG_BEER_START_LOG_FILE "Log file creation error. Mashing start canceled."
#define LANG_BEER_START_SESSION_BUSY "Session description is busy. Mashing start canceled."
#define LANG_BEER_START_POWER_ON_FAILED "Failed to turn on heating power. Mashing start canceled."
#define LANG_BEER_WAIT_SKIP_COOL_CONFIRM "Waiting for cooling skip confirmation"
#define LANG_BEER_WORT_NOT_COOLED "Wort has not cooled to target yet. Repeat the transition within 10 seconds to confirm."
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_NEXT "Lua error: failed to turn off mixer before transition"
#define LANG_BEER_LUA_STOP_LOCK_BUSY "Failed to stop Lua job at once - lock is busy. Repeat the transition in a second."
#define LANG_BEER_LUA_STOP_REQUEST_FAILED "Lua error: failed to request job stop"
#define LANG_BEER_ERR_L_NEEDS_USE_LUA "Program error: type L requires USE_LUA"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_START "Lua error: failed to turn off mixer before start"
#define LANG_BEER_LUA_JOB_NOT_ACCEPTED "Lua error: job was not accepted for start"
#define LANG_BEER_MOVE_TO_LINE "Moving to program line #"
#define LANG_BEER_MSG_HEAT_MALT "; Heating to malt addition temperature: "
#define LANG_BEER_MSG_TEMP_PAUSE "; Temperature pause: "
#define LANG_BEER_MSG_DEG_TIME "°, time: "
#define LANG_BEER_MIN " min"
#define LANG_BEER_MSG_BOIL_TIME "; Boil, time: "
#define LANG_BEER_MSG_COOL_TO "; Cooling to temperature: "
#define LANG_BEER_MSG_FERMENT_HOLD "; Fermentation, holding temperature: "
#define LANG_BEER_MSG_WAIT_MODE "; Waiting mode"
#define LANG_BEER_NEXT_LINE "Moving to the next line"
#define LANG_BEER_LUA_JOB_ACCEPTED_MSG "Lua job accepted"
#define LANG_BEER_FINISH_ACTUATOR_FAILED "Brewing finish error: failed to switch off actuator"
#define LANG_BEER_LUA_JOB_WITHOUT_USE_LUA "Lua error: job active without USE_LUA"
#define LANG_BEER_BREW_STOPPED_ERROR "Brewing stopped due to error"
#define LANG_BEER_BREW_DONE "Brewing finished"
#define LANG_BEER_MASH_PROGRAM_DONE "Mashing program finished"
#define LANG_BEER_ESTOP_WORT_OVERTEMP "Emergency shutdown! Maximum wort temperature exceeded"
#define LANG_BEER_HOLD_PAUSE_BELOW_TARGET "Hold paused: temperature below target"
#define LANG_BEER_HOLD_RESUMED "Hold resumed"
#define LANG_BEER_MANUAL_PAUSE_ACTUATOR_FAILED "Manual pause error: failed to switch off actuator"
#define LANG_BEER_ERR_UNKNOWN_STAGE_TYPE "Program error: unknown stage type in line "
#define LANG_BEER_LUA_TIMEOUT "Lua did not finish the operation before timeout"
#define LANG_BEER_LUA_MIXER_OFF_ON_STOP "Lua error: failed to turn off mixer when stopping job"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_CONFIRM "Lua error: failed to turn off mixer before job confirmation"
#define LANG_BEER_LUA_JOB_CONFIRMED "Lua job confirmed"
#define LANG_BEER_LUA_JOB_NO_START_CONFIRM "Lua error: job did not confirm start"
#define LANG_BEER_LUA_JOB_FAILED "Lua error: job finished with error"
#define LANG_BEER_WAIT_OPERATOR "Waiting for operator action"
#define LANG_BEER_AUTOTUNE_QUEUE_BUSY "Command queue is busy: beer autotune finish will be retried"
#define LANG_BEER_MALT_TEMP_REACHED "Malt addition temperature reached!"
#define LANG_BEER_WAIT_MALT "Waiting for malt addition"
#define LANG_BEER_TEMP_PAUSE_REACHED "Temperature pause reached "
#define LANG_BEER_DEG_WAITING "°. Waiting "
#define LANG_BEER_MINUTES_DOT " minutes."
#define LANG_BEER_COOL_TIMEOUT_24H "Failed to cool the boiler to target temperature in 24 hours. Check the boiler sensor, cooling water supply and cooling valve."
#define LANG_BEER_BOIL_STARTED "Boil mode started"
#define LANG_BEER_BOIL_NOT_DETECTED_120 "Failed to detect boiling start in 120 minutes. Check the boiler sensor, liquid volume, lid and whether the boiling threshold is reachable (low pressure)."
#define LANG_BEER_ESTOP_MIXER_RESTORE "Emergency shutdown! Failed to restore mixer state"
#define LANG_BEER_PID_AUTOTUNE_NO_MEM "PID autotune not started: out of memory"
#define LANG_BEER_PID_AUTOTUNE_NOT_SAVED "PID autotune not saved: "
// cheese.h
#define LANG_CHEESE_TEMP_CONFIRM_STARTED "Temperature confirmation started"
#define LANG_CHEESE_PH_CONFIRM_STARTED "pH confirmation started"
#define LANG_CHEESE_ESTOP_EQUIPMENT_OFF "Emergency shutdown! Failed to switch off cheesemaking equipment"
#define LANG_CHEESE_STAGE_HEAT "Heating"
#define LANG_CHEESE_STAGE_HOLD "Hold"
#define LANG_CHEESE_STAGE_COOL "Cooling"
#define LANG_CHEESE_STAGE_MIX "Stirring"
#define LANG_CHEESE_STAGE_DOSE "Dosing"
#define LANG_CHEESE_STAGE_PH "Waiting for pH"
#define LANG_CHEESE_STAGE_MANUAL "Manual action"
#define LANG_CHEESE_STAGE_DRAIN "Drain"
#define LANG_CHEESE_STAGE_FLOC "Flocculation"
#define LANG_CHEESE_STAGE_UNKNOWN "Unknown operation"
#define LANG_CHEESE_ROW "Line "
#define LANG_CHEESE_ERR_ROW_NOT_SET "Cheese program error: line not set"
#define LANG_CHEESE_ERR_PROGRAM_PREFIX "Program error: "
#define LANG_CHEESE_ERR_PROGRAM "Program error"
#define LANG_CHEESE_IN_LINE " in line "
#define LANG_CHEESE_ERR_TEMP_SENSOR_LINE "Temperature sensor error in line "
#define LANG_CHEESE_ERR_I2C_MIXER_LINE "I2C mixer unavailable in line "
#define LANG_CHEESE_ERR_LOCAL_DOSER_LINE "Local doser unavailable in line "
#define LANG_CHEESE_ERR_I2C_PUMP_LINE "I2C pump unavailable in line "
#define LANG_CHEESE_ERR_COOLING_NOT_IN_BUILD "Cooling is not available in this build"
#define LANG_CHEESE_ERR_PH_CAL_LINE "Invalid pH calibration in line "
#define LANG_CHEESE_ERR_LUA_NOT_IN_BUILD "Lua is not available in this build"
#define LANG_CHEESE_ERR_LUA_FILE_LINE "Lua file not found in line "
#define LANG_CHEESE_LUA_JOB_ACCEPTED "Lua job accepted"
#define LANG_CHEESE_NEXT_LINE "Moving to the next line"
#define LANG_CHEESE_WAIT_OPERATOR "Waiting for operator action"
#define LANG_CHEESE_DOSER_STARTED "Doser started"
#define LANG_CHEESE_LUA_OUTPUTS_OFF_FAILED "Lua error: failed to switch off outputs"
#define LANG_CHEESE_ERR_ROW_TRANSITION "Error moving to cheese program line"
#define LANG_CHEESE_FLOC_RECORDED "|Floc recorded: "
#define LANG_CHEESE_SEC_UNIT " s"
#define LANG_CHEESE_FLOC_TIMEOUT "Flocculation timeout"
#define LANG_CHEESE_CUT_AFTER_TIMEOUT "Calculated cut time is after the flocculation timeout"
#define LANG_CHEESE_FLOC_NO_SESSION "Flocculation session not created"
#define LANG_CHEESE_LUA_TIMEOUT "Lua did not finish the operation before timeout"
#define LANG_CHEESE_LUA_JOB_DONE "Lua job finished"
#define LANG_CHEESE_ERR_AFTER_LUA "Error moving on after Lua"
#define LANG_CHEESE_LUA_NO_NEXT_LINE "Lua finished without moving to the next line"
#define LANG_CHEESE_LUA_FAILED "Lua finished with an error"
#define LANG_CHEESE_ERR_UNKNOWN_OPERATION "Program error: unknown operation"
#define LANG_CHEESE_MODE_NAME "Cheese"
#define LANG_CHEESE_ERR_TEMP_SENSOR "Temperature sensor error"
#define LANG_CHEESE_ERR_MIXER "Mixer error"
#define LANG_CHEESE_OPERATION_TIMEOUT "Cheese program operation timeout"
#define LANG_CHEESE_TEMP_CONFIRMED "Temperature confirmed"
#define LANG_CHEESE_HOLD_RESUMED "Hold resumed"
#define LANG_CHEESE_HOLD_PAUSED_OUT_OF_BAND "Hold paused: temperature out of band"
#define LANG_CHEESE_HOLD_TIMEOUT "Hold timeout"
#define LANG_CHEESE_ERR_COOLING "Cooling error"
#define LANG_CHEESE_COOLING_OFF_FAILED "Failed to switch off cooling"
#define LANG_CHEESE_DOSING_DONE "Dosing finished"
#define LANG_CHEESE_I2C_DOSING_ABORTED "Dosing by I2C pump aborted"
#define LANG_CHEESE_PH_INVALID_10S "pH invalid for 10 seconds"
#define LANG_CHEESE_PH_CONFIRMED "pH confirmed"
#define LANG_CHEESE_FINISH_OUTPUTS_NOT_OFF "Cheesemaking finish error: outputs not switched off"
#define LANG_CHEESE_STOPPED_ERROR "Cheesemaking stopped due to error"
#define LANG_CHEESE_DONE "Cheesemaking finished"
#define LANG_CHEESE_PROGRAM_DONE "Cheesemaking program finished"
#define LANG_CHEESE_START_NO_ADS1115 "ADS1115 not found. Cheesemaking start canceled."
#define LANG_CHEESE_START_HEAT_UNAVAILABLE "Heating unavailable. Cheesemaking start canceled."
#define LANG_CHEESE_START_LOG_FILE "Log file creation error. Cheesemaking start canceled."
#define LANG_CHEESE_START_SESSION_BUSY "Session description is busy. Cheesemaking start canceled."
#define LANG_CHEESE_START_POWER_ON_FAILED "Failed to turn on heating power. Cheesemaking start canceled."
#define LANG_CHEESE_STATUS_WAITING "Waiting"
#define LANG_CHEESE_STATUS_LINE "; line "
// suvid.h
#define LANG_SUVID_MODE_NAME "Sous-vide"
#define LANG_SUVID_SENSOR_WATER "water"
#define LANG_SUVID_SENSOR_ACP "ACP"
#define LANG_SUVID_SENSOR_TANK "boiler"
#define LANG_SUVID_FINISHED "Sous-vide finished"
#define LANG_SUVID_HOLD_PAUSED_OUT_OF_BAND "Hold paused: temperature out of band"
#define LANG_SUVID_DEVIATION_WARNING "Sous-vide: temperature has deviated from setpoint by more than 2° for 60 s."
#define LANG_SUVID_HOLD_RESUMED "Hold resumed"
#define LANG_SUVID_REACH_TIMEOUT "Sous-vide: working temperature not reached in 120 minutes, heating is switched off. Check the heater, the boiler sensor and the load volume."
#define LANG_SUVID_HOLD_DONE "Sous-vide: hold finished, heating is off."
#define LANG_SUVID_HOLD_DONE_QUEUE_BUSY "Sous-vide: hold finished, but normal shutdown was not queued: command queue is busy."
// program_io.h
#define LANG_PROG_ERR_PROGRAM "Program error"
#define LANG_PROG_LINE_OPEN " (line "
#define LANG_PROG_LUA_TEXT_BAD "Lua text is empty or too long"
#define LANG_PROG_LUA_FILE_REQUIRED "specify a .lua file; an empty argument is written as \"\""
#define LANG_PROG_BEER_DEVICE_MASK "device must be 0^0^0^0^0 or a mask 1..3 with a non-zero schedule"
#define LANG_PROG_BEER_TYPE_MC "for type M/C Temp is above 0 and Time=0"
#define LANG_PROG_BEER_TYPE_F "for type F Temp is above 0"
#define LANG_PROG_BEER_TYPE_P "for type P Temp and Time must be above 0"
#define LANG_PROG_BEER_TYPE_B "for type B Temp=0 and Time is above 0"
#define LANG_PROG_BEER_TYPE_W "for type W Temp=0 and Time=0"
#define LANG_PROG_BEER_TYPE_L "for type L a timeout and zero parameters are required"
#define LANG_PROG_L_NEEDS_USE_LUA "type L requires USE_LUA"
#define LANG_PROG_BEER_TYPE_A "for type A Temp is above 0, Time=0 and device=0^0^0^0^0"
#define LANG_PROG_BEER_UNKNOWN_TYPE "unknown beer type"
#define LANG_PROG_L_TIMEOUT_RANGE "L needs a timeout of 1..65535 seconds and zero numeric fields"
#define LANG_PROG_SPEED_SR "for type S/R Speed must be in the range (0,1)"
#define LANG_PROG_SPEED_AP "for type A/P Speed must be in the range [0,100)"
#define LANG_PROG_SPEED_T "for type T Speed must be in the range (0,150]"
#define LANG_PROG_STEAM_TEMP_RANGE "T vapor: 0 or 30..100"
#define LANG_PROG_BEER_BAD_DEVICE "invalid beer device template"
#define LANG_PROG_CHEESE_MIXER_FORM "mixer must be 0^0^0^0, relay 1^0, I2C 2 with non-zero RPM or I2C with reverse 3 with RPM, ON and OFF"
#define LANG_PROG_CHEESE_H "H needs Temp, Time, heating rate and a sensor"
#define LANG_PROG_CHEESE_P "P needs a sensor and Param not less than Time"
#define LANG_PROG_CHEESE_C "C needs Temp, Time, a sensor and Param=0"
#define LANG_PROG_CHEESE_M "M needs Time, a mixer and zero Temp/Param/sensor"
#define LANG_PROG_CHEESE_D "D needs Time, a method and parameters for manual, volume or step dosing"
#define LANG_PROG_CHEESE_N "N needs Temp, Time, pH 0..14 and a sensor"
#define LANG_PROG_CHEESE_F "F needs Temp, Time, a multiplier not less than 1 and a sensor"
#define LANG_PROG_CHEESE_W "W needs Time, an action code 1..8 and TempSensor=0"
#define LANG_PROG_CHEESE_S "S needs safe outputs, Time and zero fields"
#define LANG_PROG_CHEESE_L "L needs safe outputs, Time and zero fields"
#define LANG_PROG_CHEESE_UNKNOWN_TYPE "unknown cheese type"
#define LANG_PROG_CHEESE_F_MULT "F multiplier cannot be represented as m=round(MULTIPLIER*1000)"
#define LANG_PROG_CHEESE_BAD_DEVICE "invalid cheese device template"
#define LANG_PROG_EMPTY_USE_CLEAR "Empty program: use explicit clear"
#define LANG_PROG_RECT_LINE_TOO_LONG "line too long (rect)"
#define LANG_PROG_RECT_BAD_FORMAT "invalid line format rect"
#define LANG_PROG_RECT_TOO_MANY "too many rect lines"
#define LANG_PROG_DIST_LINE_TOO_LONG "line too long (dist)"
#define LANG_PROG_DIST_BAD_FORMAT "invalid line format dist"
#define LANG_PROG_DIST_TOO_MANY "too many dist lines"
#define LANG_PROG_BK_LINE_TOO_LONG "line too long (bk)"
#define LANG_PROG_BK_BAD_FORMAT "invalid line format bk"
#define LANG_PROG_BK_TOO_MANY "too many bk lines"
#define LANG_PROG_BEER_LINE_TOO_LONG "line too long (beer)"
#define LANG_PROG_BEER_BAD_FORMAT "invalid line format beer"
#define LANG_PROG_BEER_TOO_MANY "too many beer lines"
#define LANG_PROG_NBK_LINE_TOO_LONG "line too long (nbk)"
#define LANG_PROG_NBK_BAD_FORMAT "invalid line format nbk"
#define LANG_PROG_NBK_TOO_MANY "too many nbk lines"
#define LANG_PROG_CHEESE_LINE_TOO_LONG "line too long (cheese)"
#define LANG_PROG_CHEESE_BAD_FORMAT "invalid line format cheese"
#define LANG_PROG_CHEESE_TOO_MANY "too many cheese lines"
#define LANG_PROG_NBK_FOUR_ROWS "CBC must contain 4 lines H/S/O/W"
#define LANG_PROG_UNSUPPORTED_MODE "unsupported mode"
#define LANG_PROG_FIRST_ROW_ABSOLUTE "the first line must set an absolute power/voltage (otherwise the column stays at full heat-up power)"
#define LANG_PROG_FIRST_NONZERO_ABSOLUTE "the first line with non-zero voltage/power must set an absolute value, not an adjustment (otherwise heating during heat-up may switch off unnoticed)"

// Samovar.ino
// Заголовок уровня V26/push: в любом языке, кроме русского, - только знак ⛔/⚠ (PIN_SPEC.md §6).
#define LANG_MAIN_V26_ALARM_HEADER "⛔ "
#define LANG_MAIN_V26_WARNING_HEADER "⚠ "
#define LANG_MAIN_ASSERT_BLYNK_TIMEOUT "BLYNK_TIMEOUT_MS from Samovar.h had no effect: BlynkConfig.h is included earlier"
#define LANG_MAIN_ASSERT_BLYNK_SENDBYTES "BLYNK_MAX_SENDBYTES from Samovar.h had no effect: BlynkConfig.h is included earlier"
#define LANG_MAIN_ASSERT_BLYNK_MSG_LIMIT "BLYNK_MSG_LIMIT from Samovar.h had no effect: BlynkConfig.h is included earlier"
#define LANG_MAIN_ERR_SENSOR_STEAM "Vapor temperature sensor error!"
#define LANG_MAIN_ERR_SENSOR_PIPE "Column temperature sensor error!"
#define LANG_MAIN_ERR_SENSOR_WATER "Water temperature sensor error!"
#define LANG_MAIN_ERR_SENSOR_TANK "Boiler temperature sensor error!"
#define LANG_MAIN_ERR_SENSOR_ACP "ACP temperature sensor error!"
#define LANG_MAIN_PROG_UNCHANGED_ALL_DONE "Program not changed: all its lines are already done."
#define LANG_MAIN_PROG_UNCHANGED_LINE "Program not changed: line "
#define LANG_MAIN_PROG_LINE_LOCKED " can no longer be changed: it is running or done."
#define LANG_MAIN_PROFILE_OP_CANCELLED_BUSY "Profile operation canceled: runtime state busy."
#define LANG_MAIN_NBK_PROG_NOT_SAVED "CBC program not saved: "
#define LANG_MAIN_MODE_SWITCHED_NOT_SAVED "Mode switched but not saved, reboot restores previous: "
#define LANG_MAIN_SETTINGS_NOT_SAVED "Settings not saved: "
#define LANG_MAIN_PROFILE_OP_TERMINAL_NOT_PUBLISHED "Profile operation: terminal state not published; reboot required."
#define LANG_MAIN_PROFILE_OP_RECORD_UNAVAILABLE "Profile operation: record unavailable at start; reboot required."
#define LANG_MAIN_EMERGENCY_BUTTON_TRIGGERED "Emergency shutdown! Emergency button input triggered (button or a sensor connected to it)."
#define LANG_MAIN_ACP_TEMP_LABEL " ACP temperature "
#define LANG_MAIN_PRESSURE_LIMIT_EXCEEDED "Pressure limit exceeded!"
#define LANG_MAIN_SENSOR_SCAN_REJECTED "Sensor scan rejected: process is active."
#define LANG_MAIN_UNFINISHED_SESSION_MODE "Unfinished session detected, mode "
#define LANG_MAIN_PROGRAM_NUM ", program #"
#define LANG_MAIN_HEATING_NOT_RESUMED_AUTO "; heating NOT resumed automatically."
#define LANG_MAIN_NBK_PROG_LEN_BAD_NVS "Invalid CBC program length in NVS"
#define LANG_MAIN_SESSION_INTERRUPTED_LINE "Session interrupted by reboot: line "
#define LANG_MAIN_PROGRAM_RESTORED ", program restored"
#define LANG_MAIN_PROGRAM_NOT_RESTORED ", program not restored"
#define LANG_MAIN_HEATING_NOT_RESUMED ". Heating not resumed."
#define LANG_MAIN_SUVID_HOLD_AT_FAILURE " Accumulated Sous-vide hold at failure: "
#define LANG_MAIN_CHEESE_SNAPSHOT_CLEARED "Cheese program from snapshot not restored and cleared. Default program not set."
#define LANG_MAIN_SNAPSHOT_DEFAULT_SET "Program from snapshot not restored, default program set."
#define LANG_MAIN_REASON_LABEL " Reason: "
#define LANG_MAIN_EMERGENCY_BUTTON_TASK_NOT_STARTED "Emergency shutdown! Emergency button task not started"
#define LANG_MAIN_BOOT_WITH_ERRORS "Boot with errors ("
#define LANG_MAIN_BOOT_LIMITED_MODE "). Some functions are unavailable, running in limited mode."
#define LANG_MAIN_EMERGENCY_LOCKOUT "Emergency lockout: "
#define LANG_MAIN_EMERGENCY_LOCKOUT_NBK_NVS "Emergency lockout: CBC program in NVS is corrupted: "
#define LANG_MAIN_EMERGENCY_REGULATOR_TASK_NOT_STARTED "Emergency shutdown! Regulator task not started"
#define LANG_MAIN_EMERGENCY_STACK_LOW "Emergency shutdown! Critically low stack space left"
#define LANG_MAIN_STACK_OVERFLOW_REBOOT "Stack overflow. Rebooting"
#define LANG_MAIN_EMERGENCY_TASK_STACK_LOW "Emergency shutdown! Critically low stack left for task "
#define LANG_MAIN_TASK_STACK_LABEL "Task stack "
#define LANG_MAIN_TASK_STACK_OVERFLOW_REBOOT " overflowed. Rebooting"
#define LANG_MAIN_EMERGENCY_SYSTICKER_HUNG "Emergency shutdown! SysTicker watchdog task hung"
#define LANG_MAIN_SYSTICKER_HUNG_REBOOT "SysTicker watchdog task hung. Rebooting"
#define LANG_MAIN_OP_EXPIRED_FORCED "Expired operation was forcibly completed (reaper)"
#define LANG_MAIN_MIXER_CMD_FAILED "Mixer command failed: executor did not confirm the state"
#define LANG_MAIN_NBK_MANUAL_UNAVAILABLE "Manual control unavailable during Optimization and CBC Work."
#define LANG_MAIN_NBK_BUTTON_ONLY_MANUAL_WORK "Button available only in Manual setup and CBC Work."
#define LANG_MAIN_OPTIMAL_VALUES_SET "Optimal values set: "
#define LANG_MAIN_UNIT_LPH " l/h"
#define LANG_MAIN_NBK_CMD_PUMP_UNAVAILABLE "CBC command rejected: selected I2C pump unavailable."
#define LANG_MAIN_NBK_CMD_BAD_SPEED_CAL "CBC command rejected: invalid speed calibration."
#define LANG_MAIN_NBK_START_NO_REGULATOR "CBC start rejected: power regulator unavailable in this build."
#define LANG_MAIN_MANUAL_TAKEOFF_PAUSE "Manual take-off pause"
#define LANG_MAIN_MODE_FROM_SETTINGS_NOT_ACTIVATED "Mode from settings not activated: "
#define LANG_MAIN_UNAVAILABLE_IN_BUILD "unavailable in this firmware build"
#define LANG_MAIN_CHEESE_FACT_QUEUE_OVERFLOW "F1: fact queue overflow, cheese program stopped"
#define LANG_MAIN_CHEESE_FLOCCULATION_SAVE_FAILED "Failed to save flocculation fact"
// power_regulator.h
#define LANG_PWR_QUEUE_BUSY_RESET_AFTER_OFF "Command queue busy: reset after heating off not queued"
#define LANG_PWR_HEAT_REJECTED_TASK_NOT_STARTED "Heating rejected: regulator task not started"
#define LANG_PWR_HEAT_BLOCKED_EMERGENCY "Heating is blocked by emergency protection, reboot required"
#define LANG_PWR_HEAT_REJECTED_OFF_IN_PROGRESS "Heating rejected: heating is being switched off, try again later"
#define LANG_PWR_HEAT_REJECTED_EXCLUSIVE_OP "Heating rejected: exclusive operation active (self-test/calibration)"
#define LANG_PWR_HEAT_REJECTED_MODE_SWITCH "Heating rejected: mode switch in progress"
#define LANG_PWR_HEAT_REJECTED_START_PENDING "Heating rejected: start command already running, try again later"
#define LANG_PWR_CMD_TIMEOUT_HEAT_OFF "Regulator command timeout; heating off"
#define LANG_PWR_START_CMD_FAILED "Regulator start command failed"
#define LANG_PWR_START_CMD_TIMEOUT_HEAT_OFF "Regulator start command timeout; heating off"
#define LANG_PWR_START_CMD_SUPERSEDED "Regulator start command was explicitly canceled by a new command"
#define LANG_PWR_SESSION_ABORTED_REGULATOR_FAILURE "Session aborted: heating regulator failure. Restart required."
#define LANG_PWR_CMD_TIMEOUT_AT_HEAT_OFF "Regulator command timeout while turning heating off"
#define LANG_PWR_OFF_CMD_FAILED "Regulator off command failed"
#define LANG_PWR_OFF_CMD_TIMEOUT "Regulator off command timeout"
#define LANG_PWR_OFF_CMD_SUPERSEDED "Regulator off command was explicitly canceled by a new command"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_OFF "Regulator command timeout with local relays off"
#define LANG_PWR_NO_REGULATOR_LINK "No connection to the regulator!"
#define LANG_PWR_EMERGENCY_NO_REGULATOR_LINK "Emergency shutdown! No connection to the heating regulator."
#define LANG_PWR_EMERGENCY_HEATER_CONTROL "Emergency shutdown! Heater control error."
#define LANG_PWR_UNKNOWN_REGULATOR_MODE "Unknown regulator mode: "
#define LANG_PWR_START_REJECTED_SAFETY_BARRIER "Regulator start command rejected by safety-barrier"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_RELEASED "Regulator command timeout; local relays off"
#define LANG_PWR_BG_APPLY_TIMEOUT "Regulator command background apply timeout"
#define LANG_PWR_BG_APPLY_FAILED "Regulator command background apply failed"
// crash_handler.ino
#define LANG_CRASH_RST_UNKNOWN "Unknown reset reason (0)"
#define LANG_CRASH_RST_POWERON "Reset due to power-on (1)"
#define LANG_CRASH_RST_EXT "External reset via RESET pin (2)"
#define LANG_CRASH_RST_SW "Software reset via esp_restart() (3)"
#define LANG_CRASH_RST_PANIC "Reset due to panic or unhandled exception (4)"
#define LANG_CRASH_RST_INT_WDT "Reset due to internal watchdog (5)"
#define LANG_CRASH_RST_TASK_WDT "Reset due to task watchdog (6)"
#define LANG_CRASH_RST_WDT "Reset due to any watchdog (7)"
#define LANG_CRASH_RST_DEEPSLEEP "Reset after exiting deep sleep (8)"
#define LANG_CRASH_RST_BROWNOUT "Reset due to brownout (9)"
#define LANG_CRASH_RST_SDIO "Reset due to SDIO error (10)"
#define LANG_CRASH_RST_UNKNOWN_CODE "Unknown reason code: "
#define LANG_CRASH_EMERGENCY_REBOOT "Emergency reboot"
// WebServer.ino
#define LANG_WEB_STALE_SETTINGS "Settings changed on the device itself. Refresh the page and try again."
#define LANG_WEB_ADS1115_PH_BLOCKED "ADS1115 unavailable: pH calibration blocked"
#define LANG_WEB_MODE_UNAVAILABLE_IN_BUILD "Mode unavailable in this firmware build"
#define LANG_WEB_INVALID_REQUEST_PARAM "Invalid request parameter"
#define LANG_WEB_PARAMS_MUST_BE_UNIQUE "Numeric and text parameters must be unique"
#define LANG_WEB_WPROGRAM_MUST_BE_TEXT "WProgram must be a text parameter"
#define LANG_WEB_CLEAR_REQUIRES_CLEAR1 "Clearing the program requires exactly clear=1"
#define LANG_WEB_CLEAR_MUST_BE_SEPARATE "Clearing the program must be a separate action"
#define LANG_WEB_DESCR_INVALID "Description is invalid"
#define LANG_WEB_DESCR_TOO_LONG "Description is longer than 250 bytes"
#define LANG_WEB_UPDATE_CANCELLED_LOW_SPACE "Web interface update canceled: low disk space"
#define LANG_WEB_UPDATE_INCOMPLETE "Web interface update not completed, version unchanged"
// Blynk.ino
// Подписи V21 без цифр: приложения берут первое число строки (PIN_SPEC.md §2).
#define LANG_BLYNK_V21_CURRENT "Cur:"
#define LANG_BLYNK_V21_TARGET " Set:"
#define LANG_BLYNK_QUEUE_BUSY_V12 "Command queue busy: Blynk V12 command not queued"
#define LANG_BLYNK_QUEUE_BUSY_RESET "Command queue busy: reset from Blynk not queued"
#define LANG_BLYNK_QUEUE_BUSY_V4 "Command queue busy: Blynk V4 command not queued"
#define LANG_BLYNK_V34_LINE_BEGIN "V34: log line ("
#define LANG_BLYNK_V34_BYTES_NO_FIT " bytes) does not fit in buffer ("
#define LANG_BLYNK_V34_NOT_SENT "), not sent"
#define LANG_BLYNK_V35_TRUNCATED_FROM "V35: session description truncated from "
#define LANG_BLYNK_V35_TO " to "
#define LANG_BLYNK_V35_BYTES_BUFFER " bytes (buffer "
// lua.h
#define LANG_LUA_CHUNK_TIMEOUT "Lua: chunk execution aborted by timeout"
#define LANG_LUA_SENSOR_WATER "water"
#define LANG_LUA_SENSOR_ACP "ACP"
#define LANG_LUA_SENSOR_TANK "boiler"
#define LANG_LUA_SCRIPT1_STOPPED_AFTER "script.lua stopped after "
#define LANG_LUA_ERRORS_IN_ROW_SEE_ERR " consecutive errors, see previous ERR"
#define LANG_LUA_SCRIPT1_DISABLED "Common script script.lua disabled after repeated errors"
#define LANG_LUA_MODE_SCRIPT_BEGIN "mode script ("
#define LANG_LUA_MODE_SCRIPT_STOPPED_AFTER ") stopped after "
// Menu.ino
#define LANG_MENU_SETTINGS_NOT_SAVED "Menu settings not saved: "
#define LANG_MENU_QUEUE_BUSY_START "Command queue busy: start from menu not queued"
#define LANG_MENU_LOG_CREATE_FAILED "Log file creation error. Rectification start canceled."
#define LANG_MENU_DESCR_BUSY "Session description is busy. Rectification start canceled."
#define LANG_MENU_LAST_LINE_FINISH "finishing the last line"
#define LANG_MENU_PROGRAM_DONE_SELF_RUN "Program finished. Total reflux ("
#define LANG_MENU_MIN_TO_AUTO_OFF " min until auto power-off)."
#define LANG_MENU_STOPPED_BY_USER "Stopped by user"
#define LANG_MENU_LUA_STOP_FAILED "Failed to stop Lua: runtime lock busy."
#define LANG_MENU_RESET_STOP_UNCONFIRMED "Process stopped by reset: completion not confirmed"
// impurity_detector.h
#define LANG_DET_LINE_NUM "Line #"
#define LANG_DET_STOP_PAUSES_RATE_CUT " stop pauses in a row. Base take-off rate reduced to "
#define LANG_DET_UNIT_LPH_DOT " l/h."
#define LANG_DET_PAUSE_TYPE_BUSY "Detector: auto pause type busy. Check skipped."
#define LANG_DET_PAUSE_TYPE_SET_FAILED "Detector: failed to set pause type."
#define LANG_DET_PAUSE_CRITICAL_TREND "Take-off pause: critical trend"
#define LANG_DET_CRITICAL_TREND_PAUSE "Detector: Critical trend! Take-off pause. (trend: "
#define LANG_DET_NEW_BODY_T "Detector: Setting new body T (first body program, trend "
#define LANG_DET_RATE_REDUCTION "Detector: Rate reduction (trend "
#define LANG_DET_THRESHOLD ", threshold: "
// FS.ino
#define LANG_FS_MOUNT_FAILED_FORMATTING "Failed to mount the file system, formatting..."
#define LANG_FS_FORMAT_FAILED "Failed to format the file system, upload the interface via Arduino"
#define LANG_FS_ERROR_UPLOAD "File system error! Upload via Arduino"
#define LANG_FS_LOW_MEMORY_TOTAL "Running out of memory! Total: "
#define LANG_FS_USED ", used: "
// Samovar.h
#define LANG_SAMH_ASSERT_WPROGRAM_SIZE "WProgram: unexpected struct size - check field order and alignment"
#define LANG_SAMH_PWR_MSG_POWER "Power"
#define LANG_SAMH_PWR_SIGN_W "W"
#define LANG_SAMH_PWR_MSG_VOLTAGE "Voltage"
#define LANG_SAMH_PWR_SIGN_V "V"
// runtime_helpers.h
#define LANG_RT_WAIT_STEAM "(vapor)"
#define LANG_RT_WAIT_PIPE "(column)"
#define LANG_RT_WAIT_DETECTOR "(Detector)"
#define LANG_RT_EVENT_RING_REINIT "Event log reinitialized after corruption"
// valve_buzzer.h
#define LANG_VALVE_OPEN_WATER_SUPPLY "Open the water supply!"
#define LANG_VALVE_COOLING_OPENED "Cooling water valve opened!"
#define LANG_VALVE_CLOSE_WATER_SUPPLY "Close the water supply!"
#define LANG_VALVE_COOLING_CLOSED "Cooling water valve closed!"
// selftest.h
#define LANG_SELF_FINISHED "Self-test finished."
#define LANG_SELF_REJECTED "Self-test rejected: a process or mode switch is active"
#define LANG_SELF_STARTING "Starting self-test."
// sensorinit.h
#define LANG_SENS_UNSUPPORTED_DEFAULT_MODE "unsupported mode of default program"
#define LANG_SENS_LUA_STATUS_RESET_FAILED "Failed to reset Lua_status: runtime lock busy."
#define LANG_SENS_LOG_BUSY_CLOSE_SKIPPED "Log file busy: close skipped"
// I2CStepper.h
#define LANG_I2C_LINK_LOST "Lost connection to I2C stepper, address "
#define LANG_I2C_LOCAL_STOP "Local stop of I2C stepper, address "
// SPIFFSEditor.h
#define LANG_EDIT_JSON_ESCAPE_TRUNCATED "spiffsEditorJsonEscape: string truncated, out of memory"
// string_utils.h
#define LANG_STR_JSON_STRING_TRUNCATED "toJsonString: string truncated, out of memory"
