#pragma once
// Испанский перевод прошивки. Правила (проверяет tools/smoke_i18n_firmware.py):
//  - по одной строке #define LANG_<KEY> "text" на каждый ключ TR(KEY, "...") из кода;
//    полнота: нет ключа - ошибка компиляции, лишних ключей быть не должно;
//  - в переводе нет кириллицы;
//  - набор printf-спецификаторов (%d %s %.1f ...) совпадает с русским по порядку;
//  - длина перевода в байтах UTF-8 не больше русской (буферы рассчитаны на русский);
//  - секции ключей идут по файлам с комментарием // <имя файла>.
#define SAMOVAR_LANG_NAME "Español"

// nbk.h
#define LANG_NBK_WASH_PROCESSED "Mosto procesado "
#define LANG_NBK_UNIT_L_SP " l "
#define LANG_NBK_CFG_COLUMN_INERTIA "inercia de columna In"
#define LANG_NBK_CFG_DELTA_T "corrección dT"
#define LANG_NBK_CFG_TANK_TEMP "temperatura calderín Tn"
#define LANG_NBK_CFG_FLOOD_PRESSURE "presión de inundación PS"
#define LANG_NBK_CFG_POWER_STEP "paso de potencia dM"
#define LANG_NBK_CFG_FEED_STEP "paso de aporte dP"
#define LANG_NBK_CFG_STEAM_LIMIT "límite temp. vapor Tp"
#define LANG_NBK_CFG_MAINS_INPUT_INVALID "tensión de red (entrada no reconocida)"
#define LANG_NBK_CFG_HEATER_INPUT_INVALID "resistencia del TEN (entrada no reconocida)"
#define LANG_NBK_CFG_MAINS_RANGE "tensión de red fuera de rango"
#define LANG_NBK_CFG_HEATER_RANGE "resistencia del TEN fuera de rango"
#define LANG_NBK_CEILING_LOWERED_TO "Techo de presión bajado a "
#define LANG_NBK_MM_FLOODING_AT " mm (inundación a "
#define LANG_NBK_MM_CLOSE " mm)"
#define LANG_NBK_SRC_FLOOD_SENSOR "FS"
#define LANG_NBK_SRC_NO_PRESSURE_DATA "sin datos PS"
#define LANG_NBK_SRC_PRESSURE_SENSOR "PS"
#define LANG_NBK_HEATUP_ACTUATORS_NOT_CONFIRMED "El arranque de CMC no confirmó los comandos de actuadores."
#define LANG_NBK_SAFE_WAIT "Espera segura de CMC."
#define LANG_NBK_ACTUATOR_CONFIRM_TIMEOUT "Tiempo de confirmación de actuadores CMC agotado. Espera segura."
#define LANG_NBK_ACTUATOR_CMD_HEATING_OFF "Comando de actuadores CMC rechazado con calentamiento apagado."
#define LANG_NBK_REGULATOR_NOT_CONFIRMED "El regulador no confirmó el comando CMC. Espera segura."
#define LANG_NBK_PUMP_NOT_CONFIRMED "La bomba CMC no confirmó el comando. Calentamiento apagado."
#define LANG_NBK_WORK_RESUMED "Trabajo de CMC reanudado."
#define LANG_NBK_WARMUP_POWER_FEED_SET "Potencia y aporte de precalentamiento CMC establecidos."
#define LANG_NBK_MODE_NAME "CMC"
#define LANG_NBK_SENSOR_VAPOR "vapor"
#define LANG_NBK_SENSOR_BOILER "calder."
#define LANG_NBK_RESTART_IMPOSSIBLE "Reinicio de CMC imposible: "
#define LANG_NBK_HEATING_NOT_OFF_YET "el calentamiento aún no está apagado"
#define LANG_NBK_PUMP_STOP_NOT_CONFIRMED "la bomba no confirmó la parada"
#define LANG_NBK_SESSION_CONFIG_NOT_CAPTURED "Configuración de sesión CMC no registrada."
#define LANG_NBK_PROGRAM_LINE_OUT_OF_RANGE "Error de programa CMC: número de línea fuera de rango"
#define LANG_NBK_PROGRAM_LINE_NOT_SET "Error de programa CMC: línea no definida"
#define LANG_NBK_WARMUP_TOO_HIGH_PREFIX "En precalentamiento hay valores demasiado altos de "
#define LANG_NBK_AND_OR_FEED_PROGRAM_STOP " y/o aporte. Programa detenido."
#define LANG_NBK_AFTER_FLOOD_REDUCE_REJECTED "Reducción de actuadores CMC tras inundación no aceptada."
#define LANG_NBK_FLOODING_BY "Inundación por "
#define LANG_NBK_FEED_THIRD_POWER_HALF ". Aporte 1/3, potencia 1/2."
#define LANG_NBK_BEFORE_OPT_SETUP_PREFIX "Antes de iniciar la Optimización, los valores de Ajuste de "
#define LANG_NBK_AND_FEED_TOO_HIGH_STOP " y aporte son demasiado altos. Parada."
#define LANG_NBK_MANUAL_WORK_WAIT_PREFIX "Esperando el paso manual a Trabajo, los valores de "
#define LANG_NBK_OPT_INITIAL_REJECTED "Parámetros iniciales de Optimización CMC no aceptados."
#define LANG_NBK_OPT_ACCEPTED_FROM "Optimización aceptada desde: "
#define LANG_NBK_UNIT_LPH_SP " l/h "
#define LANG_NBK_SET_PARAMS_PREFIX "Los valores de "
#define LANG_NBK_AND_SPEED_TOO_HIGH_OPT_STOP " y Velocidad son demasiado altos: optimización imposible. Parada."
#define LANG_NBK_TN_REFINED_BY_SENSOR "Tn de referencia corregida por sensor de vinaza: "
#define LANG_NBK_OPT_NO_FLOOD_SENSOR "Optimización imposible: falta el sensor de inundación. Fije a mano los parámetros en el programa de la etapa Trabajo y pulse Siguiente programa. A los 10 minutos el proceso pasará a espera segura (calentamiento y aporte apagados)."
#define LANG_NBK_C_IN_SETTINGS " °C (en ajustes "
#define LANG_NBK_FEED_LIMIT_REACHED "Alcanzado el aporte límite ("
#define LANG_NBK_LPH_RESULT_COLON " l/h). Resultado: "
#define LANG_NBK_OPT_TB_GE_TN "Optimización: Tb >= Tn ("
#define LANG_NBK_INCREASING_FEED_ITER "), aumentamos el aporte. Iteración "
#define LANG_NBK_POWER_LIMIT_REACHED "Alcanzada la potencia límite. ("
#define LANG_NBK_W_RESULT_COLON " W.). Resultado: "
#define LANG_NBK_UNIT_LPH_DOT " l/h."
#define LANG_NBK_OPT_NOT_FOUND_TB_TN "Óptimo no hallado: Tb no alcanzó Tn ("
#define LANG_NBK_NO_ITERATION_CHECK_TB ") en ninguna iteración. Revise el sensor Tb."
#define LANG_NBK_OPT_TP_LT_TPMIN "Optimización: Tp < Tp mín("
#define LANG_NBK_INCREASING "), aumentamos "
#define LANG_NBK_ITERATION_SP ". Iteración "
#define LANG_NBK_OPT_TB_LT_TN "Optimización: Tb < Tn("
#define LANG_NBK_OPT_CORRECTION_REJECTED "Corrección de Optimización CMC no aceptada."
#define LANG_NBK_ITER_LIMIT_RESULT "Alcanzado el límite de iteraciones. Resultado: "
#define LANG_NBK_UNIT_LPH " l/h"
#define LANG_NBK_TEMP_REDUCE_FEED_HEATING "Reducción temporal de aporte y calentamiento."
#define LANG_NBK_WORK_WASH_SPILL "Trabajo: derrame de mosto (Tb "
#define LANG_NBK_FEED_REDUCED_BY "), aporte reducido en "
#define LANG_NBK_TO_COLON ", a: "
#define LANG_NBK_WORK_TB_LT_TN_DT "Trabajo: Tb < Tn-dT ("
#define LANG_NBK_REDUCING_FEED_BY "), reducimos el aporte en "
#define LANG_NBK_WORK_TP_BELOW_LIMIT "Trabajo: Tp bajo el límite ("
#define LANG_NBK_WORK_PRESSURE "Trabajo: presión "
#define LANG_NBK_GE_CEILING " ≥ techo "
#define LANG_NBK_MM_REDUCING_FEED_BY " mm, reducimos el aporte en "
#define LANG_NBK_WORK_TB_GT_TN_DT "Trabajo: Tb > Tn+dT ("
#define LANG_NBK_INCREASING_FEED_BY "), aumentamos el aporte en "
#define LANG_NBK_WORK_CORRECTION_REJECTED "Corrección de Trabajo CMC no aceptada."
#define LANG_NBK_REPEAT_FLOODING_BY "Inundación repetida por "
#define LANG_NBK_DURING_PAUSE_EXTENDED " durante la pausa. Pausa ampliada, potencia a la mitad."
#define LANG_NBK_REPEAT_POWER_REDUCE_REJECTED "Nueva reducción de potencia CMC no aceptada."
#define LANG_NBK_WORK_RESUME_REJECTED "Reanudación del Trabajo CMC no aceptada."
#define LANG_NBK_WORK_RESUME_AFTER_FLOOD "Trabajo: reanudación tras inundación, parámetros corregidos: "
#define LANG_NBK_WORK_CONTINUE_AFTER_PAUSE "Trabajo: continuamos el ciclo tras la pausa."
#define LANG_NBK_RESUME_IMPOSSIBLE_EMERGENCY "Reanudación del Trabajo CMC imposible: emergencia registrada."
#define LANG_NBK_RESUME_IMPOSSIBLE_NO_SNAPSHOT "Reanudación del Trabajo CMC imposible: sin instantánea de configuración de sesión."
#define LANG_NBK_RESUME_REJECTED_CMD_BUSY "Reanudación del Trabajo CMC rechazada: el comando anterior de actuadores sigue en curso."
#define LANG_NBK_WORK_WAITS_HEATING_OFF "El Trabajo CMC espera a que se apague el calentamiento."
#define LANG_NBK_RESUME_UNAVAILABLE_PUMP_STOP "Reanudación del Trabajo CMC no disponible: parada de bomba no confirmada."
#define LANG_NBK_HEATING_NOT_ON_RESUME "Calentamiento CMC apagado al intentar reanudar el Trabajo."
#define LANG_NBK_RESUME_PARAMS_REJECTED "Reanudación del Trabajo CMC: parámetros no aceptados por actuadores."
#define LANG_NBK_WORK_RESUMED_M "Trabajo CMC reanudado: M="
#define LANG_NBK_COMMA_P ", P="
#define LANG_NBK_START_REJECTED_NO_REGULATOR "Inicio de CMC rechazado: regulador de potencia no disponible en esta versión."
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_NO_REGULATOR "Parada de bomba CMC en configuración no disponible no confirmada."
#define LANG_NBK_LINE_SWITCH_HEATING_STARTING "Cambio de línea CMC rechazado: el inicio del calentamiento no ha terminado"
#define LANG_NBK_PROGRAM_NOT_SET "Programa CMC no definido"
#define LANG_NBK_GOTO_WORK_NO_SNAPSHOT "Paso a Trabajo CMC rechazado: sin instantánea de configuración de sesión."
#define LANG_NBK_AUTO_WORK_IMPOSSIBLE "Entrada automática a Trabajo CMC imposible: calentamiento apagado u óptimo no hallado."
#define LANG_NBK_AUTO_WORK_PARAMS_REJECTED "Parámetros de entrada automática a Trabajo no aceptados por actuadores CMC."
#define LANG_NBK_OPT_FINISHED "Optimización terminada"
#define LANG_NBK_BY_PRESSURE " por presión ("
#define LANG_NBK_COLON_MO ": Mo="
#define LANG_NBK_COMMA_PO ", Po="
#define LANG_NBK_LPH_PAUSE " l/h. Pausa "
#define LANG_NBK_S_THEN_WORK " s, luego Trabajo."
#define LANG_NBK_AUTO_WORK_FORBIDDEN "Paso automático a Trabajo CMC prohibido. Fije Power/Speed de la línea W y pulse «Siguiente programa»."
#define LANG_NBK_LINE_W_NEEDS_NONZERO "La línea W requiere Power y Speed distintos de cero, o valores óptimos guardados."
#define LANG_NBK_WORK_UNAVAILABLE_PUMP_STOP "Trabajo CMC no disponible: parada de bomba no confirmada."
#define LANG_NBK_HEATING_NOT_ON_EXPLICIT_WORK "Calentamiento CMC apagado tras el comando explícito de paso a Trabajo."
#define LANG_NBK_HEATING_OFF_WORK_REJECTED "Calentamiento CMC apagado. Paso a Trabajo rechazado."
#define LANG_NBK_LINE_W_PARAMS_REJECTED "Parámetros de la línea W no aceptados por actuadores CMC."
#define LANG_NBK_EXPLICIT_WORK_ACCEPTED_M "Paso explícito a Trabajo CMC aceptado: M="
#define LANG_NBK_W_COMMA_P " W, P="
#define LANG_NBK_SAFE_WAIT_STOPPED_BY_OPERATOR "Espera segura detenida por el operador."
#define LANG_NBK_SAFE_WAIT_SESSION_ENDED "Espera segura CMC: sesión terminada por comando del operador."
#define LANG_NBK_START_HEATING_OFF_PENDING "El apagado del calentamiento no ha terminado. Inicio de CMC cancelado."
#define LANG_NBK_HEATING_OFF_GOTO_LINE "Calentamiento CMC apagado. Pasando a la línea #"
#define LANG_NBK_CANCELLED_DOT " cancelado."
#define LANG_NBK_START_REJECTED_BAD_SETTING "Inicio de CMC rechazado: ajuste incorrecto - "
#define LANG_NBK_START_LOG_FILE_ERROR "Error al crear el archivo de registro. Inicio de CMC cancelado."
#define LANG_NBK_PROGRAM_STARTED_WARMUP "Inicio del programa CMC. Precalentamiento"
#define LANG_NBK_NO_FLOOD_SENSORS_WARNING "Atención: no hay ningún sensor de inundación (FS apagado, PS no responde). La protección contra inundación no funciona."
#define LANG_NBK_START_SESSION_BUSY "Descripción de sesión ocupada. Inicio de CMC cancelado."
#define LANG_NBK_GOTO_LINE "Pasando a la línea #"
#define LANG_NBK_TYPE_SP ". Tipo: "
#define LANG_NBK_START_HEATING_NOT_ON "Calentamiento CMC no encendido. Inicio cancelado."
#define LANG_NBK_HEATUP_TRANSITION_STARTED "Transición de arranque de CMC iniciada."
#define LANG_NBK_MANUAL_NEEDS_NONZERO "El ajuste manual de CMC requiere potencia y aporte distintos de cero."
#define LANG_NBK_MANUAL_PARAMS_REJECTED "Parámetros del ajuste manual de CMC no aceptados."
#define LANG_NBK_PROGRAM_LINE_EMPTY "Error de programa CMC: línea de programa vacía"
#define LANG_NBK_STEAM_98_WASH_OUT "Temperatura de vapor superior a 98°C durante 60 segundos. Se acabó el mosto. Programa CMC terminado."
#define LANG_NBK_EMERGENCY_WASH_OUT "¡Apagado de emergencia! No se pudo terminar el programa CMC con normalidad (se acabó el mosto)"
#define LANG_NBK_TP_ROSE_BY "Tp subió "
#define LANG_NBK_C_RELATIVE_TO_MIN " °C respecto al mínimo "
#define LANG_NBK_C_WASH_ENDING " °C: el mosto se acaba. Programa CMC terminado."
#define LANG_NBK_EMERGENCY_TP_RISE "¡Apagado de emergencia! No se pudo terminar el programa CMC con normalidad (subida de Tp del vapor)"
#define LANG_NBK_STEAM_OVER_LIMIT_MANUAL "T vapor sobre el límite 60 segundos en ajuste manual. Posible marcha en seco del generador de vapor. Programa CMC terminado."
#define LANG_NBK_EMERGENCY_STEAM_OVERHEAT_MANUAL "¡Apagado de emergencia! No se pudo terminar el programa CMC con normalidad (sobrecalentamiento de vapor en ajuste manual)"
#define LANG_NBK_INSUFFICIENT_COOLING "¡Refrigeración insuficiente! Parada."
#define LANG_NBK_PRESSURE_SENSOR_FAILED "¡Fallo del sensor de presión! Sin lecturas más de 60 segundos. Parada."
#define LANG_NBK_LOG_BUSY_CLOSE_SKIPPED "Archivo de registro ocupado: cierre no realizado"
#define LANG_NBK_HEATUP_TRANSITION_ABORTED "Transición de arranque de CMC interrumpida."
#define LANG_NBK_HEATING_START_ABORTED "Inicio de calentamiento CMC interrumpido: condición de inicio incumplida, proceso detenido."
#define LANG_NBK_HEATUP_NEEDS_CONFIRMED_FEED "El arranque de CMC requiere un aporte distinto de cero y confirmado."
#define LANG_NBK_RUN_FINISHED "Trabajo CMC terminado"
#define LANG_NBK_PUMP_STOP_UNCONFIRMED_ON_FINISH "Parada de bomba CMC no confirmada al terminar."
#define LANG_NBK_AVG_SESSION_RATE "con velocidad media de sesión "
#define LANG_NBK_AND_AVG_FEED_RATE "y velocidad media de aporte "
#define LANG_NBK_OVER_COLON "en: "
#define LANG_NBK_UNIT_H_DOT " h."
#define LANG_NBK_RUN_FINISHED_DOT "Trabajo CMC terminado."
#define LANG_NBK_RUN_ABORTED_EMERGENCY "Trabajo CMC interrumpido por emergencia."
#define LANG_NBK_FLOOD_FEED_REDUCE_UNCONFIRMED "Reducción de aporte CMC por inundación no confirmada."
#define LANG_NBK_EMERGENCY_FLOODING "¡Apagado de emergencia! No se pudo terminar el programa CMC con normalidad (inundación)"
#define LANG_NBK_FLOOD_ACTUATOR_REDUCE_REJECTED "Reducción de actuadores CMC por inundación no aceptada."
// BK.h
#define LANG_BK_WORK_POWER_APPLIED "Potencia de trabajo CM aplicada."
#define LANG_BK_PROGRAMS_DONE_CONTINUE "Programas terminados, la extracción continúa"
#define LANG_BK_LUA_LINE_SCRIPT_NOT_STARTED "Error de Lua: script de línea no iniciado"
#define LANG_BK_PROGRAM_L_NEEDS_LUA "Error de programa: el tipo L requiere USE_LUA"
#define LANG_BK_GOTO_PROGRAM_LINE "Pasando a la línea de programa #"
#define LANG_BK_DEPHLEGMATOR_WATER_MANUAL "Agua del deflemador: control manual"
#define LANG_BK_PUMP_CONTROL_UNSUPPORTED "Su equipo no admite el control de la bomba"
#define LANG_BK_MODE_NAME "CM"
#define LANG_BK_SENSOR_BOILER "calder."
#define LANG_BK_SENSOR_VAPOR "vapor"
#define LANG_BK_START_NO_TANK_SENSOR "CM no iniciada: sensor de calderín no asignado o sin respuesta"
#define LANG_BK_START_NEEDS_STEAM_SENSOR "CM no iniciada: el programa requiere sensor de vapor"
#define LANG_BK_START_LOG_FILE_ERROR "Error al crear el archivo de registro. Inicio de CM cancelado."
#define LANG_BK_START_SESSION_BUSY "Descripción de sesión ocupada. Inicio de CM cancelado."
#define LANG_BK_HEATING_ON "Calentamiento de columna de mosto encendido"
#define LANG_BK_WAIT_WORK_POWER "Esperando la potencia de trabajo de CM."
#define LANG_BK_LUA_TIMEOUT "Lua no terminó la operación antes del tiempo límite"
#define LANG_BK_LUA_FAILED "Lua terminó con un error"
#define LANG_BK_RUN_FINISHED_DOT "Trabajo CM terminado."
#define LANG_BK_RUN_FINISHED "Trabajo de la columna de mosto terminado"
// distiller.h
#define LANG_DIST_NO_ALCOHOL_LEFT "No queda alcohol en el calderín"
#define LANG_DIST_ABV_UNAVAILABLE "Graduación no disponible: la línea por porcentaje continúa"
#define LANG_DIST_MODE_NAME "Destilación"
#define LANG_DIST_SENSOR_BOILER "calder."
#define LANG_DIST_START_NO_TANK_SENSOR "Destilación no iniciada: sensor de calderín no asignado o sin respuesta. Abra ajustes y revise la asignación del sensor de calderín."
#define LANG_DIST_START_LOG_FILE_ERROR "Error al crear el archivo de registro. Inicio de destilación cancelado."
#define LANG_DIST_START_SESSION_BUSY "Descripción de sesión ocupada. Inicio de destilación cancelado."
#define LANG_DIST_HEATING_ON "Calentamiento del destilador encendido"
#define LANG_DIST_LUA_TIMEOUT "Lua no terminó la operación antes del tiempo límite"
#define LANG_DIST_LUA_FAILED "Lua terminó con un error"
#define LANG_DIST_FINISHED "Destilación terminada."
#define LANG_DIST_TOTAL_TIME " Tiempo total: "
#define LANG_DIST_UNIT_MIN " min."
#define LANG_DIST_PROGRAMS_DONE_CONTINUE "Programas terminados, la extracción continúa"
#define LANG_DIST_LUA_LINE_SCRIPT_NOT_STARTED "Error de Lua: script de línea no iniciado"
#define LANG_DIST_PROGRAM_L_NEEDS_LUA "Error de programa: el tipo L requiere USE_LUA"
#define LANG_DIST_GOTO_PROGRAM_LINE "Pasando a la línea de programa #"

// logic.h
#define LANG_LOGIC_PRG_NUM "Prg n.º"
#define LANG_LOGIC_PROG_LINE_START "Programa: inicio de línea  n.º"
#define LANG_LOGIC_PROG_LINE_START_LUA "Programa: inicio de línea n.º"
#define LANG_LOGIC_TAKEOFF_TO_CONTAINER ", extracción al recipiente "
#define LANG_LOGIC_I2C_PUMP_CMD_HEAD "Bomba I2C sobre PC: comando «"
#define LANG_LOGIC_I2C_PUMP_CMD_TAIL "» no confirmado tras 10 envíos."
#define LANG_LOGIC_LUA_OP_DONE "Operación Lua completada"
#define LANG_LOGIC_LUA_OP_NOT_DONE "Operación Lua no completada"
#define LANG_LOGIC_LUA_TIMEOUT "Lua no terminó la operación antes del tiempo límite"
#define LANG_LOGIC_LUA_OP_FAILED "La operación Lua terminó con error"
#define LANG_LOGIC_LUA_ERROR "Lua terminó con un error"
#define LANG_LOGIC_AUTOPAUSE_BUSY_SKIP "Tipo de pausa automática ocupado. Control de extracción omitido."
#define LANG_LOGIC_PAUSE_SET_FAIL_HEAD "No se pudo fijar la pausa por "
#define LANG_LOGIC_PAUSE_TYPE_BUSY_TAIL ": tipo de pausa ocupado."
#define LANG_LOGIC_AUTOPAUSE_TAIL "Pausa automática de extracción"
#define LANG_LOGIC_PAUSE_BY "Pausa por "
#define LANG_LOGIC_RESUME_AFTER_AUTOPAUSE "Continuamos la extracción tras la pausa automática"
#define LANG_LOGIC_TAKEOFF_RESUMED "Extracción reanudada"
#define LANG_LOGIC_LABEL_T_STEAM "T vapor"
#define LANG_LOGIC_LABEL_T_PIPE "T columna"
#define LANG_LOGIC_DETECTOR_RESUME "Detector: continuamos la extracción tras la pausa"
#define LANG_LOGIC_PUMP_CAL_BAD_STEPS "Error de calibración de bomba: número de pasos incorrecto"
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_HEAD "Calibración de bomba no guardada: "
#define LANG_LOGIC_PUMP_CAL_NOT_SAVED_TAIL ". Resultado perdido, repita la calibración."
#define LANG_LOGIC_ACTION_PAUSE "pausa"
#define LANG_LOGIC_ACTION_RESUME "continuación"
#define LANG_LOGIC_MANUAL_PAUSE_TAKEOFF "Pausa manual de extracción"
#define LANG_LOGIC_MANUAL_PAUSE_MASH "Pausa manual de maceración"
#define LANG_LOGIC_MASH_PAUSE_NEXT_STEP "La pausa se aplicará en el próximo paso de maceración."
#define LANG_LOGIC_MASH_PAUSED "Maceración en pausa."
#define LANG_LOGIC_AUTOPAUSE_RESET_FAIL "No se pudo restablecer el tipo de pausa automática."
#define LANG_LOGIC_MASH_RESUMED_TAIL "Maceración continuada"
#define LANG_LOGIC_MASH_RESUMED_MSG "Maceración continuada."
#define LANG_LOGIC_DIST_MODE_SEP "; Modo destilación"
#define LANG_LOGIC_DIST_PROGRAMS_DONE "Programas ejecutados, extracción hasta T calderín "
#define LANG_LOGIC_DIST_MODE_DEG "°; Modo destilación"
#define LANG_LOGIC_DIST_ROW_LEFT "; Línea: quedan "
#define LANG_LOGIC_OF_APPROX " de ~"
#define LANG_LOGIC_UNIT_MIN " min"
#define LANG_LOGIC_DIST_ROW_FORECAST_WAIT "; Pronóstico de línea: esperando datos"
#define LANG_LOGIC_DIST_PROCESS_LEFT "; Proceso hasta DistTemp, quedan:"
#define LANG_LOGIC_DIST_TOTAL "; Total:"
#define LANG_LOGIC_DIST_PROCESS_FORECAST_WAIT "; Pronóstico de proceso: esperando hervor/datos"
#define LANG_LOGIC_BK_MODE "Modo columna de mosto"
#define LANG_LOGIC_NBK_STAGE_H "Precalent."
#define LANG_LOGIC_NBK_STAGE_S "Ajuste"
#define LANG_LOGIC_NBK_STAGE_O "Optimización"
#define LANG_LOGIC_NBK_STAGE_W "Trabajo"
#define LANG_LOGIC_BEER_ON_PAUSE "En pausa; "
#define LANG_LOGIC_BEER_WAIT_SKIP_COOL "Esperando confirmar omisión de refrigeración; "
#define LANG_LOGIC_BEER_HEAT_TO_MALT "Calentando a temperatura de adición de malta"
#define LANG_LOGIC_CUR_T "; T actual: "
#define LANG_LOGIC_BEER_WAIT_MALT "Esperando adición de malta"
#define LANG_LOGIC_BEER_PAUSE "Pausa "
#define LANG_LOGIC_BEER_DEG_HEATING "°; Calentamiento"
#define LANG_LOGIC_BEER_COOL_TO "Refrigeración a "
#define LANG_LOGIC_BEER_WAIT_PRESS_NEXT "Espera. Pulse 'Siguiente programa'; "
#define LANG_LOGIC_BEER_AUTOCAL "Autocalibración. Al terminar "
#define LANG_LOGIC_BEER_AUTOCAL_POWER_OFF "se apagará la alimentación"
#define LANG_LOGIC_BEER_AUTOCAL_NEXT_LINE "paso a la siguiente línea"
#define LANG_LOGIC_BEER_BOIL_HEATING "Hervido - calentamiento"
#define LANG_LOGIC_BEER_BOIL "Hervido "
#define LANG_LOGIC_BEER_FERM_HOLD "Fermentación; Mant. T="
#define LANG_LOGIC_CUR_SHORT "; Act: "
#define LANG_LOGIC_PAREN_HEATING " (Calent.)"
#define LANG_LOGIC_PAREN_THERMOSTAT " (Termostato)"
#define LANG_LOGIC_BEER_FERM_STOPPED "Fermentación (detenida)"
#define LANG_LOGIC_RUNNING_LUA_SCRIPT "Ejecutando script Lua"
#define LANG_LOGIC_PROGRESS "; Progreso: "
#define LANG_LOGIC_STATUS_OFF "Apagado"
#define LANG_LOGIC_PAREN_ERROR "(error)"
#define LANG_LOGIC_AUTOPAUSE_READ_FAIL "No se pudo leer el tipo de pausa automática."
#define LANG_LOGIC_PAUSE_SP " pausa "
#define LANG_LOGIC_RESUME_IN ". Continuación en "
#define LANG_LOGIC_UNIT_SEC " s."
#define LANG_LOGIC_PROGRAM_DONE_STATUS "Ejecución del programa terminada"
#define LANG_LOGIC_STATUS_CALIBRATION "Calibración"
#define LANG_LOGIC_STATUS_PAUSE "Pausa"
#define LANG_LOGIC_SUVID_HOLD "Sous vide; Mant. T="
#define LANG_LOGIC_DEG_CUR "°; Act: "
#define LANG_LOGIC_SUVID_HOLD_TIME "; Espera: "
#define LANG_LOGIC_COLUMN_HEATUP "Arranque de columna"
#define LANG_LOGIC_HEATUP_DONE_STAB "Arranque terminado. Estabilización/reflujo total"
#define LANG_LOGIC_STAB_DONE "Estabilización terminada/reflujo total"
#define LANG_LOGIC_LEFT "; Queda:"
#define LANG_LOGIC_BODY_T_STEAM ";T cuerpo vapor:"
#define LANG_LOGIC_BODY_T_PIPE ";T cuerpo columna:"
#define LANG_LOGIC_PUMP_NOT_CALIBRATED "Bomba sin calibrar (pasos por ml = 0). Imposible iniciar la rectificación."
#define LANG_LOGIC_RECT_PROG_LINE_UNSET "Error de programa de rectificación: línea no definida"
#define LANG_LOGIC_RECT_PROG_FIRST_LINE "Error de programa: la primera línea debe fijar potencia/tensión absoluta. Imposible iniciar la rectificación."
#define LANG_LOGIC_PROG_ERR_LINE "Error de programa: la línea "
#define LANG_LOGIC_PROG_LINE_NEVER_ENDS " nunca terminará (volumen y temperatura no definidos)"
#define LANG_LOGIC_ACTION_PROGRAM_END "fin del programa"
#define LANG_LOGIC_PROGRAM_FINISHED "Programa terminado"
#define LANG_LOGIC_LOG_BUSY_CLOSE_SKIPPED "Archivo de registro ocupado: cierre omitido"
#define LANG_LOGIC_PROGRAM_DONE_MSG "Ejecución del programa terminada."
#define LANG_LOGIC_LUA_LINE_SCRIPT_NOT_STARTED "Error de Lua: script de línea no iniciado"
#define LANG_LOGIC_NEXT_LINE "Pasando a la siguiente línea"
#define LANG_LOGIC_LUA_OP_STARTED "Operación Lua iniciada"
#define LANG_LOGIC_PROG_TYPE_L_NEEDS_LUA "Error de programa: el tipo L requiere USE_LUA"
#define LANG_LOGIC_ACTION_LINE_START "inicio de línea "
#define LANG_LOGIC_PROG_LINE_SPEED "Programa: velocidad de línea n.º"
#define LANG_LOGIC_SPEED_OVER_PUMP_LIMIT " l/h) supera el límite de la bomba, limitada a "
#define LANG_LOGIC_UNIT_LPH_DOT " l/h."
#define LANG_LOGIC_COMMA_PAUSE ", pausa "
#define LANG_LOGIC_PROGRAM_PAUSE "Pausa de programa"
#define LANG_LOGIC_NEW_BODY_T_STEAM "Nuevas T cuerpo: vapor = "
#define LANG_LOGIC_COMMA_PIPE_EQ ", columna = "
#define LANG_LOGIC_BODY_T_SET_FAIL "No se puede fijar la T del cuerpo."
#define LANG_LOGIC_BOILING_STARTED_ABV "¡Empezó el hervor en el calderín! Graduación "
#define LANG_LOGIC_BOILING_STARTED "¡Empezó el hervor en el calderín!"
#define LANG_LOGIC_WETTING_START "Inicio del humedecimiento del relleno de columna. ¡Vigile el nivel de flema!"
#define LANG_LOGIC_WETTING_OK "¡Relleno de columna humedecido con éxito!"
#define LANG_LOGIC_WETTING_TIMEOUT "Superado el tiempo máximo de humedecimiento. Humedecimiento fallido: detenga el proceso a mano."
#define LANG_LOGIC_WETTING_VOLT_RAMP_START "Iniciamos la reducción gradual de tensión"
#define LANG_LOGIC_WETTING_VOLT_TO "Reduciendo tensión a "
#define LANG_LOGIC_WETTING_MIN_VOLT "Alcanzada la tensión mínima: "
#define LANG_LOGIC_WETTING_WAIT_SENSOR ". Esperamos que actúe el sensor."
#define LANG_LOGIC_WETTING_MIN_VOLT_TIMEOUT "Superado el tiempo de espera a tensión mínima. Humedecimiento fallido: detenga el proceso a mano."
#define LANG_LOGIC_WETTING_NO_SENSOR "Sensor de nivel de flema no instalado, humedecimiento del relleno imposible"
// alarm.h
#define LANG_ALARM_SENSORS_UNASSIGNED "Sensores sin asignar. Abra ajustes y asigne los sensores de vapor, agua y calderín."
#define LANG_ALARM_EMERGENCY_STOP "¡Apagado de emergencia!"
#define LANG_ALARM_COOLING_HOLD_3MIN "La refrigeración seguirá 3 minutos más y se cerrará."
#define LANG_ALARM_EMERGENCY_STOP_TAIL "Apagado de emergencia"
#define LANG_ALARM_EMERGENCY_STOP_SP "¡Apagado de emergencia! "
#define LANG_ALARM_NO_SENSOR_DATA ": sin datos del sensor "
#define LANG_ALARM_RECT_SENSORS_UNASSIGNED "¡Apagado de emergencia! Rectificación: sensores sin asignar"
#define LANG_ALARM_MODE_RECT "Rectificación"
#define LANG_ALARM_SENSOR_STEAM "vapor"
#define LANG_ALARM_SENSOR_TANK "calder."
#define LANG_ALARM_FLOOD_SENSOR "¡Se activó el sensor de inundación!"
#define LANG_ALARM_REDUCING_FROM " bajamos de "
#define LANG_ALARM_RAISING_TO " subimos a "
#define LANG_ALARM_OVERTEMP_STEAM " Vapor"
#define LANG_ALARM_OVERTEMP_WATER " Agua"
#define LANG_ALARM_OVERTEMP_ACP " TCA"
#define LANG_ALARM_TANK_LIMIT_FINISHED "Límite de temperatura máxima del calderín. Programa terminado."
#define LANG_ALARM_TANK_LIMIT_FINISH_FAIL "¡Apagado de emergencia! No se pudo terminar el programa con normalidad por temperatura del calderín"
#define LANG_ALARM_MAX_TEMP_EXCEEDED "¡Apagado de emergencia! Superada la temperatura máxima"
#define LANG_ALARM_WATER_CRIT_SUPPLY_ERR "¡Temperatura crítica del agua! Error de suministro de agua. "
#define LANG_ALARM_HEATUP_DONE_STAB "Arranque terminado. Estabilización/reflujo total."
#define LANG_ALARM_ABV "Graduación "
#define LANG_ALARM_STAB_DONE_STABLE "Estabilización terminada, la columna trabaja estable."
// mode_switch.h
#define LANG_MSW_I2C_MIXER_STOP "El agitador I2C no confirmó la parada"
#define LANG_MSW_I2C_PUMP_STOP "La bomba I2C no confirmó la parada"
#define LANG_MSW_STEPPER_STOP "el motor paso a paso no se detuvo"
#define LANG_MSW_VALVE_CLOSE "la válvula no se cerró"
#define LANG_MSW_MIXER_STOP "el agitador no se detuvo"
#define LANG_MSW_COOLING_PUMP_STOP "la bomba de refrigeración no se detuvo"
#define LANG_MSW_PUMP_CAL_NOT_DONE "no terminó la calibración de la bomba"
#define LANG_MSW_HEATING_NOT_CONFIRMED "no se confirmó el calentamiento"
#define LANG_MSW_ACTUATOR_NOT_CONFIRMED "no se confirmó el actuador"
#define LANG_MSW_FORCE_COMPLETED "Cambio de modo forzado: "
#define LANG_MSW_LUA_NOT_CONFIRMED "no se confirmó Lua"
#define LANG_MSW_QUEUE_NOT_CONFIRMED "no se confirmó la cola"
#define LANG_MSW_PENDING_CMDS_CANCELLED "Comandos de control pendientes cancelados por cambio de modo"
#define LANG_MSW_READINESS_NOT_CONFIRMED "no se confirmó la disponibilidad"
#define LANG_MSW_LOG_NOT_CONFIRMED "no se confirmó el registro"
#define LANG_MSW_POWER_TRANSITION_NOT_CONFIRMED "no se confirmó la transición de potencia"
#define LANG_MSW_NBK_TRANSITION_NOT_CONFIRMED "no se confirmó la transición de CMC"
#define LANG_MSW_HEATING_START_NOT_CONFIRMED "no se confirmó el inicio del calentamiento"
#define LANG_MSW_SELF_TEST_NOT_CONFIRMED "no se confirmó el autotest"
#define LANG_MSW_OWNER_NOT_CONFIRMED "no se confirmó el propietario del modo"
#define LANG_MSW_LUA_NOT_RELOADED "script Lua no recargado"
#define LANG_MSW_PROFILE_NOT_SAVED "perfil no guardado"
// mode_common.h
#define LANG_MCOM_SENSOR_WATER "agua"
#define LANG_MCOM_SENSOR_ACP "TCA"
#define LANG_MCOM_WATER_SUPPLY_STOPPED "¡Apagado de emergencia! Suministro de agua interrumpido."
#define LANG_MCOM_OVERTEMP_WATER " Agua"
#define LANG_MCOM_OVERTEMP_ACP " TCA"
#define LANG_MCOM_MAX_TEMP_EXCEEDED "¡Apagado de emergencia! Superada la temperatura máxima"
#define LANG_MCOM_WATER_HIGH_HEAD "Temperatura del agua alta: "
#define LANG_MCOM_WATER_WARN_THRESHOLD "°C (umbral de advertencia "
#define LANG_MCOM_CHECK_COOLING_DOT "°C). Revise la refrigeración."
#define LANG_MCOM_ACP_HIGH_HEAD "Temperatura de TCA alta: "
#define LANG_MCOM_ACP_THRESHOLD "°C (umbral "
#define LANG_MCOM_CHECK_COOLING_BANG "°C)! Revise la refrigeración."
#define LANG_MCOM_WATER_CRIT_REDUCING "¡Temperatura crítica del agua! Reducimos "
#define LANG_MCOM_FROM " de "
#define LANG_MCOM_LOG_BUSY_CLOSE_SKIPPED "Archivo de registro ocupado: cierre omitido"
#define LANG_MCOM_HEATING_LATCHED "Calentamiento bloqueado por protección de emergencia, se requiere reinicio"
#define LANG_MCOM_HEATING_OFF_PENDING "El apagado del calentamiento no ha terminado. Inicio cancelado."
#define LANG_MCOM_HEATING_NOT_RESUMED "El calentamiento no se reanudó automáticamente. Se requiere repetir el comando de inicio."
// mode_registry.h
#define LANG_MREG_NAME_DIST "destilación"
#define LANG_MREG_NAME_BEER "cerveza"
#define LANG_MREG_NAME_BK "CM"
#define LANG_MREG_NAME_NBK "CMC"
#define LANG_MREG_NAME_CHEESE "elaboración de queso"
#define LANG_MREG_UNAVAILABLE_NO_REGULATOR "No disponible en esta versión del firmware: falta regulador de potencia"
#define LANG_MREG_UNAVAILABLE_NO_LUA "No disponible en esta versión del firmware: Lua no está activado"
#define LANG_MREG_START_REJECTED_SWITCH "Comando de inicio rechazado: el cambio de modo no ha terminado"
#define LANG_MREG_START_UNAVAILABLE_MODE "Comando de inicio no disponible en el modo actual"
#define LANG_MREG_QUEUE_BUSY_START "Cola de comandos ocupada: inicio "
#define LANG_MREG_NOT_QUEUED " no encolado"
#define LANG_MREG_STATUS_MISMATCH "El estado no pertenece al modo actual: ciclo omitido, revise la sincronización del modo"

// beer.h
#define LANG_BEER_ADD_HOPS "¡Añada el lúpulo!"
#define LANG_BEER_ESTOP_COOLING_OPEN "¡Apagado de emergencia! No se pudo abrir la refrigeración"
#define LANG_BEER_ESTOP_COOLING_SAFE "¡Apagado de emergencia! No se pudo devolver la refrigeración a estado seguro"
#define LANG_BEER_ESTOP_COOL_PUMP_ON "¡Apagado de emergencia! No se pudo encender la bomba de refrigeración"
#define LANG_BEER_ESTOP_COOL_PUMP_OFF "¡Apagado de emergencia! No se pudo apagar la bomba de refrigeración"
#define LANG_BEER_ESTOP_COOLING_RESTORE "¡Apagado de emergencia! No se pudo devolver la refrigeración a estado de trabajo"
#define LANG_BEER_ESTOP_COOLING_CLOSE "¡Apagado de emergencia! No se pudo cerrar la refrigeración"
#define LANG_BEER_SENSOR_TANK "calder."
#define LANG_BEER_SENSOR_WATER "agua"
#define LANG_BEER_SENSOR_PIPE "columna"
#define LANG_BEER_SENSOR_STEAM "vapor"
#define LANG_BEER_SENSOR_ACP "TCA"
#define LANG_BEER_ERR_ROW_NOT_SET "Error de programa Cerveza: línea no definida"
#define LANG_BEER_ERR_BAD_STAGE_TYPE "Error de programa: tipo de etapa incorrecto en la línea "
#define LANG_BEER_ERR_PROGRAM_PREFIX "Error de programa: "
#define LANG_BEER_ERR_PROGRAM "Error de programa"
#define LANG_BEER_IN_LINE " en la línea "
#define LANG_BEER_ERR_BAD_TEMP_SENSOR "Error de programa: sensor de temperatura incorrecto en la línea "
#define LANG_BEER_ERR_I2C_PUMP_LINE "Bomba I2C no disponible en la línea "
#define LANG_BEER_ERR_I2C_PUMP_RELAY_LINE "Relé I2C de bomba no disponible en la línea "
#define LANG_BEER_ERR_I2C_MIXER_LINE "Agitador I2C no disponible en la línea "
#define LANG_BEER_MODE_NAME "Cerveza"
#define LANG_BEER_START_HEAT_OFF_PENDING "El apagado del calentamiento no ha terminado. Inicio de maceración cancelado."
#define LANG_BEER_START_SAFETY_LATCH "Bloqueo de seguridad del calentamiento activo. Inicio de maceración cancelado."
#define LANG_BEER_START_LOG_FILE "Error al crear el archivo de registro. Inicio de maceración cancelado."
#define LANG_BEER_START_SESSION_BUSY "Descripción de sesión ocupada. Inicio de maceración cancelado."
#define LANG_BEER_START_POWER_ON_FAILED "No se pudo encender la alimentación del calentamiento. Inicio de maceración cancelado."
#define LANG_BEER_WAIT_SKIP_COOL_CONFIRM "Esperando confirmar omisión de refrigeración"
#define LANG_BEER_WORT_NOT_COOLED "El mosto aún no se enfrió a la meta. Repita el paso en 10 segundos para confirmar."
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_NEXT "Error de Lua: no se pudo apagar el agitador antes del paso"
#define LANG_BEER_LUA_STOP_LOCK_BUSY "No se pudo detener el job de Lua al instante: bloqueo ocupado. Repita el paso en un segundo."
#define LANG_BEER_LUA_STOP_REQUEST_FAILED "Error de Lua: no se pudo solicitar la parada del job"
#define LANG_BEER_ERR_L_NEEDS_USE_LUA "Error de programa: el tipo L requiere USE_LUA"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_START "Error de Lua: no se pudo apagar el agitador antes del inicio"
#define LANG_BEER_LUA_JOB_NOT_ACCEPTED "Error de Lua: el job no fue aceptado para iniciar"
#define LANG_BEER_MOVE_TO_LINE "Pasando a la línea de programa #"
#define LANG_BEER_MSG_HEAT_MALT "; Calentamiento a temperatura de adición de malta: "
#define LANG_BEER_MSG_TEMP_PAUSE "; Pausa de temperatura: "
#define LANG_BEER_MSG_DEG_TIME "°, tiempo: "
#define LANG_BEER_MIN " min"
#define LANG_BEER_MSG_BOIL_TIME "; Hervido, tiempo: "
#define LANG_BEER_MSG_COOL_TO "; Refrigeración a temperatura: "
#define LANG_BEER_MSG_FERMENT_HOLD "; Fermentación, mantenimiento de temperatura: "
#define LANG_BEER_MSG_WAIT_MODE "; Modo espera"
#define LANG_BEER_NEXT_LINE "Pasando a la siguiente línea"
#define LANG_BEER_LUA_JOB_ACCEPTED_MSG "Tarea Lua aceptada"
#define LANG_BEER_FINISH_ACTUATOR_FAILED "Error al terminar la elaboración: no se pudo apagar el actuador"
#define LANG_BEER_LUA_JOB_WITHOUT_USE_LUA "Error de Lua: job activo sin USE_LUA"
#define LANG_BEER_BREW_STOPPED_ERROR "Elaboración detenida por error"
#define LANG_BEER_BREW_DONE "Elaboración terminada"
#define LANG_BEER_MASH_PROGRAM_DONE "Programa de maceración terminado"
#define LANG_BEER_ESTOP_WORT_OVERTEMP "¡Apagado de emergencia! Superada la temperatura máxima del mosto"
#define LANG_BEER_HOLD_PAUSE_BELOW_TARGET "Pausa de espera: temperatura bajo la meta"
#define LANG_BEER_HOLD_RESUMED "Espera reanudada"
#define LANG_BEER_MANUAL_PAUSE_ACTUATOR_FAILED "Error de pausa manual: no se pudo apagar el actuador"
#define LANG_BEER_ERR_UNKNOWN_STAGE_TYPE "Error de programa: tipo de etapa desconocido en la línea "
#define LANG_BEER_LUA_TIMEOUT "Lua no terminó la operación antes del tiempo límite"
#define LANG_BEER_LUA_MIXER_OFF_ON_STOP "Error de Lua: no se pudo apagar el agitador al detener el job"
#define LANG_BEER_LUA_MIXER_OFF_BEFORE_CONFIRM "Error de Lua: no se pudo apagar el agitador antes de confirmar el job"
#define LANG_BEER_LUA_JOB_CONFIRMED "Tarea Lua confirmada"
#define LANG_BEER_LUA_JOB_NO_START_CONFIRM "Error de Lua: el job no confirmó el inicio"
#define LANG_BEER_LUA_JOB_FAILED "Error de Lua: el job terminó con error"
#define LANG_BEER_WAIT_OPERATOR "Esperando acción del operador"
#define LANG_BEER_AUTOTUNE_QUEUE_BUSY "Cola de comandos ocupada: se repetirá el fin del autoajuste de cerveza"
#define LANG_BEER_MALT_TEMP_REACHED "¡Alcanzada la temperatura de adición de malta!"
#define LANG_BEER_WAIT_MALT "Esperando adición de malta"
#define LANG_BEER_TEMP_PAUSE_REACHED "Alcanzada la pausa de temperatura "
#define LANG_BEER_DEG_WAITING "°. Espera "
#define LANG_BEER_MINUTES_DOT " minutos."
#define LANG_BEER_COOL_TIMEOUT_24H "No se pudo enfriar el calderín a la temperatura objetivo en 24 horas. Revise el sensor del calderín, el agua de refrigeración y la válvula de refrigeración."
#define LANG_BEER_BOIL_STARTED "Comenzó el modo de hervido"
#define LANG_BEER_BOIL_NOT_DETECTED_120 "No se detectó el inicio del hervor en 120 minutos. Revise el sensor del calderín, el volumen de líquido, la tapa y si se alcanza el umbral de hervor (baja presión)."
#define LANG_BEER_ESTOP_MIXER_RESTORE "¡Apagado de emergencia! No se pudo restaurar el estado del agitador"
#define LANG_BEER_PID_AUTOTUNE_NO_MEM "Autoajuste PID no iniciado: falta memoria"
#define LANG_BEER_PID_AUTOTUNE_NOT_SAVED "Autoajuste PID no guardado: "
// cheese.h
#define LANG_CHEESE_TEMP_CONFIRM_STARTED "Confirmación de temperatura iniciada"
#define LANG_CHEESE_PH_CONFIRM_STARTED "Confirmación de pH iniciada"
#define LANG_CHEESE_ESTOP_EQUIPMENT_OFF "¡Apagado de emergencia! No se pudo apagar el equipo de elaboración de queso"
#define LANG_CHEESE_STAGE_HEAT "Calent."
#define LANG_CHEESE_STAGE_HOLD "Espera"
#define LANG_CHEESE_STAGE_COOL "Refrigeración"
#define LANG_CHEESE_STAGE_MIX "Agitación"
#define LANG_CHEESE_STAGE_DOSE "Dosificación"
#define LANG_CHEESE_STAGE_PH "Espera de pH"
#define LANG_CHEESE_STAGE_MANUAL "Acción manual"
#define LANG_CHEESE_STAGE_DRAIN "Vaciado"
#define LANG_CHEESE_STAGE_FLOC "Floculación"
#define LANG_CHEESE_STAGE_UNKNOWN "Operación desconocida"
#define LANG_CHEESE_ROW "Línea "
#define LANG_CHEESE_ERR_ROW_NOT_SET "Error de programa Queso: línea no definida"
#define LANG_CHEESE_ERR_PROGRAM_PREFIX "Error de programa: "
#define LANG_CHEESE_ERR_PROGRAM "Error de programa"
#define LANG_CHEESE_IN_LINE " en la línea "
#define LANG_CHEESE_ERR_TEMP_SENSOR_LINE "Error del sensor de temperatura en la línea "
#define LANG_CHEESE_ERR_I2C_MIXER_LINE "Agitador I2C no disponible en la línea "
#define LANG_CHEESE_ERR_LOCAL_DOSER_LINE "Dosificador local no disponible en la línea "
#define LANG_CHEESE_ERR_I2C_PUMP_LINE "Bomba I2C no disponible en la línea "
#define LANG_CHEESE_ERR_COOLING_NOT_IN_BUILD "Refrigeración no disponible en esta versión"
#define LANG_CHEESE_ERR_PH_CAL_LINE "Calibración de pH no válida en la línea "
#define LANG_CHEESE_ERR_LUA_NOT_IN_BUILD "Lua no disponible en esta versión"
#define LANG_CHEESE_ERR_LUA_FILE_LINE "Archivo Lua /cheese.lua no encontrado en la línea "
#define LANG_CHEESE_LUA_JOB_ACCEPTED "Tarea Lua aceptada"
#define LANG_CHEESE_NEXT_LINE "Pasando a la siguiente línea"
#define LANG_CHEESE_WAIT_OPERATOR "Esperando acción del operador"
#define LANG_CHEESE_DOSER_STARTED "Dosificador iniciado"
#define LANG_CHEESE_LUA_OUTPUTS_OFF_FAILED "Error de Lua: no se pudieron apagar las salidas"
#define LANG_CHEESE_ERR_ROW_TRANSITION "Error al pasar a la línea del programa de queso"
#define LANG_CHEESE_FLOC_RECORDED "|Flóculo registrado: "
#define LANG_CHEESE_SEC_UNIT " s"
#define LANG_CHEESE_FLOC_TIMEOUT "Tiempo de floculación agotado"
#define LANG_CHEESE_CUT_AFTER_TIMEOUT "El momento de corte calculado es posterior al tiempo de floculación"
#define LANG_CHEESE_FLOC_NO_SESSION "Sesión de floculación no creada"
#define LANG_CHEESE_LUA_TIMEOUT "Lua no terminó la operación antes del tiempo límite"
#define LANG_CHEESE_LUA_JOB_DONE "Tarea Lua terminada"
#define LANG_CHEESE_ERR_AFTER_LUA "Error al pasar tras Lua"
#define LANG_CHEESE_LUA_NO_NEXT_LINE "Lua terminó sin pasar a la siguiente línea"
#define LANG_CHEESE_LUA_FAILED "Lua terminó con un error"
#define LANG_CHEESE_ERR_UNKNOWN_OPERATION "Error de programa: operación desconocida"
#define LANG_CHEESE_MODE_NAME "Queso"
#define LANG_CHEESE_ERR_TEMP_SENSOR "Error del sensor de temperatura"
#define LANG_CHEESE_ERR_MIXER "Error del agitador"
#define LANG_CHEESE_OPERATION_TIMEOUT "Tiempo agotado de operación del programa de queso"
#define LANG_CHEESE_TEMP_CONFIRMED "Temperatura confirmada"
#define LANG_CHEESE_HOLD_RESUMED "Espera reanudada"
#define LANG_CHEESE_HOLD_PAUSED_OUT_OF_BAND "Espera en pausa: temperatura fuera de banda"
#define LANG_CHEESE_HOLD_TIMEOUT "Tiempo de espera agotado"
#define LANG_CHEESE_ERR_COOLING "Error de refrigeración"
#define LANG_CHEESE_COOLING_OFF_FAILED "No se pudo apagar la refrigeración"
#define LANG_CHEESE_DOSING_DONE "Dosificación terminada"
#define LANG_CHEESE_I2C_DOSING_ABORTED "Dosificación con bomba I2C interrumpida"
#define LANG_CHEESE_PH_INVALID_10S "pH no fiable durante 10 segundos"
#define LANG_CHEESE_PH_CONFIRMED "pH confirmado"
#define LANG_CHEESE_FINISH_OUTPUTS_NOT_OFF "Error al terminar la elaboración de queso: salidas sin apagar"
#define LANG_CHEESE_STOPPED_ERROR "Elaboración de queso detenida por error"
#define LANG_CHEESE_DONE "Elaboración de queso terminada"
#define LANG_CHEESE_PROGRAM_DONE "Programa de elaboración de queso terminado"
#define LANG_CHEESE_START_NO_ADS1115 "ADS1115 no encontrado. Inicio de elaboración de queso cancelado."
#define LANG_CHEESE_START_HEAT_UNAVAILABLE "Calentamiento no disponible. Inicio de elaboración de queso cancelado."
#define LANG_CHEESE_START_LOG_FILE "Error al crear el archivo de registro. Inicio de elaboración de queso cancelado."
#define LANG_CHEESE_START_SESSION_BUSY "Descripción de sesión ocupada. Inicio de elaboración de queso cancelado."
#define LANG_CHEESE_START_POWER_ON_FAILED "No se pudo encender la alimentación del calentamiento. Inicio de elaboración de queso cancelado."
#define LANG_CHEESE_STATUS_WAITING "Espera"
#define LANG_CHEESE_STATUS_LINE "; línea "
// suvid.h
#define LANG_SUVID_MODE_NAME "Sous vide"
#define LANG_SUVID_SENSOR_WATER "agua"
#define LANG_SUVID_SENSOR_ACP "TCA"
#define LANG_SUVID_SENSOR_TANK "calder."
#define LANG_SUVID_FINISHED "Sous vide terminado"
#define LANG_SUVID_HOLD_PAUSED_OUT_OF_BAND "Espera en pausa: temperatura fuera de banda"
#define LANG_SUVID_DEVIATION_WARNING "Sous vide: la temperatura se desvía de la consigna más de 2° desde hace 60 s."
#define LANG_SUVID_HOLD_RESUMED "Espera reanudada"
#define LANG_SUVID_REACH_TIMEOUT "Sous vide: no se alcanzó la temperatura de trabajo en 120 minutos, se apaga el calentamiento. Revise el TEN, el sensor del calderín y el volumen de carga."
#define LANG_SUVID_HOLD_DONE "Sous vide: espera terminada, calentamiento apagado."
#define LANG_SUVID_HOLD_DONE_QUEUE_BUSY "Sous vide: espera terminada, pero el apagado normal no se encoló: cola de comandos ocupada."
// program_io.h
#define LANG_PROG_ERR_PROGRAM "Error de programa"
#define LANG_PROG_LINE_OPEN " (línea "
#define LANG_PROG_LUA_TEXT_BAD "el texto Lua está vacío o es demasiado largo"
#define LANG_PROG_LUA_FILE_REQUIRED "indique un archivo .lua; el argumento vacío se escribe como «»"
#define LANG_PROG_BEER_DEVICE_MASK "el dispositivo debe ser 0^0^0^0^0 o máscara 1..3 con horario distinto de cero"
#define LANG_PROG_BEER_TYPE_MC "para tipo M/C Temp mayor que 0 y Time=0"
#define LANG_PROG_BEER_TYPE_F "para tipo F Temp mayor que 0"
#define LANG_PROG_BEER_TYPE_P "para tipo P Temp y Time deben ser mayores que 0"
#define LANG_PROG_BEER_TYPE_B "para tipo B Temp=0 y Time mayor que 0"
#define LANG_PROG_BEER_TYPE_W "para tipo W Temp=0 y Time=0"
#define LANG_PROG_BEER_TYPE_L "para tipo L se requiere tiempo límite y parámetros en cero"
#define LANG_PROG_L_NEEDS_USE_LUA "el tipo L requiere USE_LUA"
#define LANG_PROG_BEER_TYPE_A "para tipo A Temp mayor que 0, Time=0 y dispositivo=0^0^0^0^0"
#define LANG_PROG_BEER_UNKNOWN_TYPE "tipo beer desconocido"
#define LANG_PROG_L_TIMEOUT_RANGE "L requiere tiempo límite 1..65535 segundos y campos numéricos en cero"
#define LANG_PROG_SPEED_SR "para tipo S/R Speed debe estar en el rango (0,1)"
#define LANG_PROG_SPEED_AP "para tipo A/P Speed debe estar en el rango [0,100)"
#define LANG_PROG_SPEED_T "para tipo T Speed debe estar en el rango (0,150]"
#define LANG_PROG_STEAM_TEMP_RANGE "T vapor: 0 o 30..100"
#define LANG_PROG_BEER_BAD_DEVICE "plantilla de dispositivo beer incorrecta"
#define LANG_PROG_CHEESE_MIXER_FORM "agitador debe ser 0^0^0^0, relé 1^0, I2C 2 con RPM distinto de cero o I2C con reversa 3 con RPM, ON y OFF"
#define LANG_PROG_CHEESE_H "H requiere Temp, Time, velocidad de calentamiento y sensor"
#define LANG_PROG_CHEESE_P "P requiere sensor y Param no menor que Time"
#define LANG_PROG_CHEESE_C "C requiere Temp, Time, sensor y Param=0"
#define LANG_PROG_CHEESE_M "M requiere Time, agitador y Temp/Param/sensor en cero"
#define LANG_PROG_CHEESE_D "D requiere Time, método y parámetros de dosificación manual, por volumen o por pasos"
#define LANG_PROG_CHEESE_N "N requiere Temp, Time, pH 0..14 y sensor"
#define LANG_PROG_CHEESE_F "F requiere Temp, Time, multiplicador no menor que 1 y sensor"
#define LANG_PROG_CHEESE_W "W requiere Time, código de acción 1..8 y TempSensor=0"
#define LANG_PROG_CHEESE_S "S requiere salidas seguras, Time y campos en cero"
#define LANG_PROG_CHEESE_L "L requiere salidas seguras, Time y campos en cero"
#define LANG_PROG_CHEESE_UNKNOWN_TYPE "tipo cheese desconocido"
#define LANG_PROG_CHEESE_F_MULT "el multiplicador F no se representa como m=round(MULTIPLIER*1000)"
#define LANG_PROG_CHEESE_BAD_DEVICE "plantilla de dispositivo cheese incorrecta"
#define LANG_PROG_EMPTY_USE_CLEAR "Programa vacío: use la limpieza explícita"
#define LANG_PROG_RECT_LINE_TOO_LONG "línea demasiado larga (rect)"
#define LANG_PROG_RECT_BAD_FORMAT "formato de línea rect incorrecto"
#define LANG_PROG_RECT_TOO_MANY "demasiadas líneas rect"
#define LANG_PROG_DIST_LINE_TOO_LONG "línea demasiado larga (dist)"
#define LANG_PROG_DIST_BAD_FORMAT "formato de línea dist incorrecto"
#define LANG_PROG_DIST_TOO_MANY "demasiadas líneas dist"
#define LANG_PROG_BK_LINE_TOO_LONG "línea demasiado larga (bk)"
#define LANG_PROG_BK_BAD_FORMAT "formato de línea bk incorrecto"
#define LANG_PROG_BK_TOO_MANY "demasiadas líneas bk"
#define LANG_PROG_BEER_LINE_TOO_LONG "línea demasiado larga (beer)"
#define LANG_PROG_BEER_BAD_FORMAT "formato de línea beer incorrecto"
#define LANG_PROG_BEER_TOO_MANY "demasiadas líneas beer"
#define LANG_PROG_NBK_LINE_TOO_LONG "línea demasiado larga (nbk)"
#define LANG_PROG_NBK_BAD_FORMAT "formato de línea nbk incorrecto"
#define LANG_PROG_NBK_TOO_MANY "demasiadas líneas nbk"
#define LANG_PROG_CHEESE_LINE_TOO_LONG "línea demasiado larga (cheese)"
#define LANG_PROG_CHEESE_BAD_FORMAT "formato de línea cheese incorrecto"
#define LANG_PROG_CHEESE_TOO_MANY "demasiadas líneas cheese"
#define LANG_PROG_NBK_FOUR_ROWS "CMC debe contener 4 líneas H/S/O/W"
#define LANG_PROG_UNSUPPORTED_MODE "modo no admitido"
#define LANG_PROG_FIRST_ROW_ABSOLUTE "la primera línea debe fijar potencia/tensión absoluta (si no, la columna queda a plena potencia de arranque)"
#define LANG_PROG_FIRST_NONZERO_ABSOLUTE "la primera línea con tensión/potencia distinta de cero debe fijar un valor absoluto, no una corrección (si no, el calentamiento en el arranque puede apagarse sin avisar)"

// Samovar.ino
// Заголовок уровня V26/push: в любом языке, кроме русского, - только знак ⛔/⚠ (PIN_SPEC.md §6).
#define LANG_MAIN_V26_ALARM_HEADER "⛔ "
#define LANG_MAIN_V26_WARNING_HEADER "⚠ "
#define LANG_MAIN_ASSERT_BLYNK_TIMEOUT "BLYNK_TIMEOUT_MS de Samovar.h no surtió efecto: BlynkConfig.h se incluye antes"
#define LANG_MAIN_ASSERT_BLYNK_SENDBYTES "BLYNK_MAX_SENDBYTES de Samovar.h no surtió efecto: BlynkConfig.h se incluye antes"
#define LANG_MAIN_ASSERT_BLYNK_MSG_LIMIT "BLYNK_MSG_LIMIT de Samovar.h no surtió efecto: BlynkConfig.h se incluye antes"
#define LANG_MAIN_ERR_SENSOR_STEAM "¡Error del sensor de temperatura de vapor!"
#define LANG_MAIN_ERR_SENSOR_PIPE "¡Error del sensor de temperatura de columna!"
#define LANG_MAIN_ERR_SENSOR_WATER "¡Error del sensor de temperatura del agua!"
#define LANG_MAIN_ERR_SENSOR_TANK "¡Error del sensor de temperatura del calderín!"
#define LANG_MAIN_ERR_SENSOR_ACP "¡Error del sensor de temperatura en TCA!"
#define LANG_MAIN_PROG_UNCHANGED_ALL_DONE "Programa sin cambios: todas sus líneas ya se ejecutaron."
#define LANG_MAIN_PROG_UNCHANGED_LINE "Programa sin cambios: la línea "
#define LANG_MAIN_PROG_LINE_LOCKED " ya no se puede cambiar: se está ejecutando o ya se ejecutó."
#define LANG_MAIN_PROFILE_OP_CANCELLED_BUSY "Operación de perfil cancelada: runtime state ocupado."
#define LANG_MAIN_NBK_PROG_NOT_SAVED "Programa CMC no guardado: "
#define LANG_MAIN_MODE_SWITCHED_NOT_SAVED "Modo cambiado pero no guardado, el reinicio restaura el anterior: "
#define LANG_MAIN_SETTINGS_NOT_SAVED "Ajustes no guardados: "
#define LANG_MAIN_PROFILE_OP_TERMINAL_NOT_PUBLISHED "Operación de perfil: terminal state no publicado; se requiere reinicio."
#define LANG_MAIN_PROFILE_OP_RECORD_UNAVAILABLE "Operación de perfil: record no disponible al inicio; se requiere reinicio."
#define LANG_MAIN_EMERGENCY_BUTTON_TRIGGERED "¡Apagado de emergencia! Se activó la entrada del botón de emergencia (botón o sensor conectado a él)."
#define LANG_MAIN_ACP_TEMP_LABEL " Temperatura TCA "
#define LANG_MAIN_PRESSURE_LIMIT_EXCEEDED "¡Superada la presión límite!"
#define LANG_MAIN_SENSOR_SCAN_REJECTED "Escaneo de sensores rechazado: proceso activo."
#define LANG_MAIN_UNFINISHED_SESSION_MODE "Sesión sin terminar detectada, modo "
#define LANG_MAIN_PROGRAM_NUM ", programa n.º"
#define LANG_MAIN_HEATING_NOT_RESUMED_AUTO "; calentamiento NO reanudado automáticamente."
#define LANG_MAIN_NBK_PROG_LEN_BAD_NVS "Longitud de programa CMC incorrecta en NVS"
#define LANG_MAIN_SESSION_INTERRUPTED_LINE "Sesión interrumpida por reinicio: línea "
#define LANG_MAIN_PROGRAM_RESTORED ", programa restaurado"
#define LANG_MAIN_PROGRAM_NOT_RESTORED ", programa no restaurado"
#define LANG_MAIN_HEATING_NOT_RESUMED ". Calentamiento no reanudado."
#define LANG_MAIN_SUVID_HOLD_AT_FAILURE " Espera acumulada de Sous vide en el momento del fallo: "
#define LANG_MAIN_CHEESE_SNAPSHOT_CLEARED "Programa Queso de la instantánea no restaurado y borrado. Programa por defecto no establecido."
#define LANG_MAIN_SNAPSHOT_DEFAULT_SET "Programa de la instantánea no restaurado, programa por defecto establecido."
#define LANG_MAIN_REASON_LABEL " Causa: "
#define LANG_MAIN_EMERGENCY_BUTTON_TASK_NOT_STARTED "¡Apagado de emergencia! Tarea del botón de emergencia no iniciada"
#define LANG_MAIN_BOOT_WITH_ERRORS "Arranque con errores ("
#define LANG_MAIN_BOOT_LIMITED_MODE "). Algunas funciones no están disponibles, trabajamos en modo limitado."
#define LANG_MAIN_EMERGENCY_LOCKOUT "Bloqueo de emergencia: "
#define LANG_MAIN_EMERGENCY_LOCKOUT_NBK_NVS "Bloqueo de emergencia: programa CMC en NVS dañado: "
#define LANG_MAIN_EMERGENCY_REGULATOR_TASK_NOT_STARTED "¡Apagado de emergencia! Tarea del regulador no iniciada"
#define LANG_MAIN_EMERGENCY_STACK_LOW "¡Apagado de emergencia! Espacio de pila críticamente bajo"
#define LANG_MAIN_STACK_OVERFLOW_REBOOT "Desbordamiento de pila. Reiniciando"
#define LANG_MAIN_EMERGENCY_TASK_STACK_LOW "¡Apagado de emergencia! Espacio de pila críticamente bajo en la tarea "
#define LANG_MAIN_TASK_STACK_LABEL "Pila de la tarea "
#define LANG_MAIN_TASK_STACK_OVERFLOW_REBOOT " desbordada. Reiniciando"
#define LANG_MAIN_EMERGENCY_SYSTICKER_HUNG "¡Apagado de emergencia! Tarea de vigilancia SysTicker colgada"
#define LANG_MAIN_SYSTICKER_HUNG_REBOOT "Tarea de vigilancia SysTicker colgada. Reiniciando"
#define LANG_MAIN_OP_EXPIRED_FORCED "Operación caducada completada a la fuerza (reaper)"
#define LANG_MAIN_MIXER_CMD_FAILED "Comando del agitador no ejecutado: el ejecutor no confirmó el estado"
#define LANG_MAIN_NBK_MANUAL_UNAVAILABLE "Control manual no disponible en Optimización ni en Trabajo de CMC."
#define LANG_MAIN_NBK_BUTTON_ONLY_MANUAL_WORK "El botón solo está disponible en Ajuste manual y en Trabajo de CMC."
#define LANG_MAIN_OPTIMAL_VALUES_SET "Valores óptimos establecidos: "
#define LANG_MAIN_UNIT_LPH " l/h"
#define LANG_MAIN_NBK_CMD_PUMP_UNAVAILABLE "Comando CMC rechazado: la bomba I2C elegida no está disponible."
#define LANG_MAIN_NBK_CMD_BAD_SPEED_CAL "Comando CMC rechazado: calibración de velocidad incorrecta."
#define LANG_MAIN_NBK_START_NO_REGULATOR "Inicio de CMC rechazado: regulador de potencia no disponible en esta versión."
#define LANG_MAIN_MANUAL_TAKEOFF_PAUSE "Pausa manual de extracción"
#define LANG_MAIN_MODE_FROM_SETTINGS_NOT_ACTIVATED "Modo de los ajustes no activado: "
#define LANG_MAIN_UNAVAILABLE_IN_BUILD "no disponible en esta versión del firmware"
#define LANG_MAIN_CHEESE_FACT_QUEUE_OVERFLOW "F1: cola de hechos desbordada, programa de queso detenido"
#define LANG_MAIN_CHEESE_FLOCCULATION_SAVE_FAILED "No se pudo guardar el hecho de floculación"
// power_regulator.h
#define LANG_PWR_QUEUE_BUSY_RESET_AFTER_OFF "Cola de comandos ocupada: reset tras apagar el calentamiento no encolado"
#define LANG_PWR_HEAT_REJECTED_TASK_NOT_STARTED "Calentamiento rechazado: tarea del regulador no iniciada"
#define LANG_PWR_HEAT_BLOCKED_EMERGENCY "Calentamiento bloqueado por protección de emergencia, se requiere reinicio"
#define LANG_PWR_HEAT_REJECTED_OFF_IN_PROGRESS "Calentamiento rechazado: se está apagando el calentamiento, repita más tarde"
#define LANG_PWR_HEAT_REJECTED_EXCLUSIVE_OP "Calentamiento rechazado: operación exclusiva activa (autotest/calibración)"
#define LANG_PWR_HEAT_REJECTED_MODE_SWITCH "Calentamiento rechazado: cambio de modo en curso"
#define LANG_PWR_HEAT_REJECTED_START_PENDING "Calentamiento rechazado: el comando de encendido ya se ejecuta, repita más tarde"
#define LANG_PWR_CMD_TIMEOUT_HEAT_OFF "Tiempo de comando del regulador agotado; calentamiento apagado"
#define LANG_PWR_START_CMD_FAILED "El comando de inicio del regulador terminó con error"
#define LANG_PWR_START_CMD_TIMEOUT_HEAT_OFF "Tiempo del comando de inicio del regulador agotado; calentamiento apagado"
#define LANG_PWR_START_CMD_SUPERSEDED "El comando de inicio del regulador fue cancelado explícitamente por un nuevo comando"
#define LANG_PWR_SESSION_ABORTED_REGULATOR_FAILURE "Sesión interrumpida: fallo del regulador de calentamiento. Se requiere nuevo inicio."
#define LANG_PWR_CMD_TIMEOUT_AT_HEAT_OFF "Tiempo de comando del regulador agotado al apagar el calentamiento"
#define LANG_PWR_OFF_CMD_FAILED "El comando de apagado del regulador terminó con error"
#define LANG_PWR_OFF_CMD_TIMEOUT "Tiempo del comando de apagado del regulador agotado"
#define LANG_PWR_OFF_CMD_SUPERSEDED "El comando de apagado del regulador fue cancelado explícitamente por un nuevo comando"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_OFF "Tiempo de comando del regulador agotado con relés locales apagados"
#define LANG_PWR_NO_REGULATOR_LINK "¡Sin conexión con el regulador!"
#define LANG_PWR_EMERGENCY_NO_REGULATOR_LINK "¡Apagado de emergencia! Sin conexión con el regulador de calentamiento."
#define LANG_PWR_EMERGENCY_HEATER_CONTROL "¡Apagado de emergencia! Error de control del calentador."
#define LANG_PWR_UNKNOWN_REGULATOR_MODE "Modo de regulador desconocido: "
#define LANG_PWR_START_REJECTED_SAFETY_BARRIER "Comando de encendido del regulador rechazado por safety-barrier"
#define LANG_PWR_CMD_TIMEOUT_RELAYS_RELEASED "Tiempo de comando del regulador agotado; relés locales apagados"
#define LANG_PWR_BG_APPLY_TIMEOUT "Tiempo agotado al aplicar en segundo plano el comando del regulador"
#define LANG_PWR_BG_APPLY_FAILED "La aplicación en segundo plano del comando del regulador terminó con error"
// crash_handler.ino
#define LANG_CRASH_RST_UNKNOWN "Causa de reinicio desconocida (0)"
#define LANG_CRASH_RST_POWERON "Reinicio por conexión de alimentación (1)"
#define LANG_CRASH_RST_EXT "Reinicio externo por el pin RESET (2)"
#define LANG_CRASH_RST_SW "Reinicio por software con esp_restart() (3)"
#define LANG_CRASH_RST_PANIC "Reinicio por pánico o excepción no tratada (4)"
#define LANG_CRASH_RST_INT_WDT "Reinicio por el watchdog interno (5)"
#define LANG_CRASH_RST_TASK_WDT "Reinicio por el watchdog de tareas (6)"
#define LANG_CRASH_RST_WDT "Reinicio por cualquiera de los watchdogs (7)"
#define LANG_CRASH_RST_DEEPSLEEP "Reinicio tras salir del sueño profundo (8)"
#define LANG_CRASH_RST_BROWNOUT "Reinicio por detección de baja tensión (9)"
#define LANG_CRASH_RST_SDIO "Reinicio por error SDIO (10)"
#define LANG_CRASH_RST_UNKNOWN_CODE "Código de causa desconocido: "
#define LANG_CRASH_EMERGENCY_REBOOT "Reinicio de emergencia"
// WebServer.ino
#define LANG_WEB_STALE_SETTINGS "Los ajustes cambiaron en el propio dispositivo. Actualice la página y repita."
#define LANG_WEB_ADS1115_PH_BLOCKED "ADS1115 no disponible: calibración de pH bloqueada"
#define LANG_WEB_MODE_UNAVAILABLE_IN_BUILD "Modo no disponible en esta versión del firmware"
#define LANG_WEB_INVALID_REQUEST_PARAM "Parámetro de solicitud no válido"
#define LANG_WEB_PARAMS_MUST_BE_UNIQUE "Los parámetros numéricos y de texto deben ser únicos"
#define LANG_WEB_WPROGRAM_MUST_BE_TEXT "WProgram debe ser un parámetro de texto"
#define LANG_WEB_CLEAR_REQUIRES_CLEAR1 "Borrar el programa requiere exactamente clear=1"
#define LANG_WEB_CLEAR_MUST_BE_SEPARATE "Borrar el programa debe ser una acción aparte"
#define LANG_WEB_DESCR_INVALID "Descripción incorrecta"
#define LANG_WEB_DESCR_TOO_LONG "Descripción de más de 250 bytes"
#define LANG_WEB_UPDATE_CANCELLED_LOW_SPACE "Actualización de la interfaz web cancelada: poco espacio en disco"
#define LANG_WEB_UPDATE_INCOMPLETE "Actualización de la interfaz web sin terminar, la versión no cambió"
// Blynk.ino
// Подписи V21 без цифр: приложения берут первое число строки (PIN_SPEC.md §2).
#define LANG_BLYNK_V21_CURRENT "Act:"
#define LANG_BLYNK_V21_TARGET " Obj:"
#define LANG_BLYNK_QUEUE_BUSY_V12 "Cola de comandos ocupada: comando Blynk V12 no encolado"
#define LANG_BLYNK_QUEUE_BUSY_RESET "Cola de comandos ocupada: reset desde Blynk no encolado"
#define LANG_BLYNK_QUEUE_BUSY_V4 "Cola de comandos ocupada: comando Blynk V4 no encolado"
#define LANG_BLYNK_V34_LINE_BEGIN "V34: línea de registro ("
#define LANG_BLYNK_V34_BYTES_NO_FIT " bytes) no cabe en el búfer ("
#define LANG_BLYNK_V34_NOT_SENT "), no enviada"
#define LANG_BLYNK_V35_TRUNCATED_FROM "V35: descripción de sesión recortada de "
#define LANG_BLYNK_V35_TO " a "
#define LANG_BLYNK_V35_BYTES_BUFFER " bytes (búfer "
// lua.h
#define LANG_LUA_CHUNK_TIMEOUT "Lua: ejecución del chunk interrumpida por tiempo límite"
#define LANG_LUA_SENSOR_WATER "agua"
#define LANG_LUA_SENSOR_ACP "TCA"
#define LANG_LUA_SENSOR_TANK "calder."
#define LANG_LUA_SCRIPT1_STOPPED_AFTER "script.lua detenido tras "
#define LANG_LUA_ERRORS_IN_ROW_SEE_ERR " errores seguidos, vea los ERR anteriores"
#define LANG_LUA_SCRIPT1_DISABLED "Script común script.lua desactivado tras errores repetidos"
#define LANG_LUA_MODE_SCRIPT_BEGIN "script de modo ("
#define LANG_LUA_MODE_SCRIPT_STOPPED_AFTER ") detenido tras "
// Menu.ino
#define LANG_MENU_SETTINGS_NOT_SAVED "Ajustes del menú no guardados: "
#define LANG_MENU_QUEUE_BUSY_START "Cola de comandos ocupada: inicio desde el menú no encolado"
#define LANG_MENU_LOG_CREATE_FAILED "Error al crear el archivo de registro. Inicio de rectificación cancelado."
#define LANG_MENU_DESCR_BUSY "Descripción de sesión ocupada. Inicio de rectificación cancelado."
#define LANG_MENU_LAST_LINE_FINISH "fin de la última línea"
#define LANG_MENU_PROGRAM_DONE_SELF_RUN "Ejecución del programa terminada. Reflujo total ("
#define LANG_MENU_MIN_TO_AUTO_OFF " min hasta el apagado automático)."
#define LANG_MENU_STOPPED_BY_USER "Detenido por el usuario"
#define LANG_MENU_LUA_STOP_FAILED "No se pudo detener Lua: runtime lock ocupado."
#define LANG_MENU_RESET_STOP_UNCONFIRMED "Proceso detenido por reinicio: terminación no confirmada"
// impurity_detector.h
#define LANG_DET_LINE_NUM "Línea n.º"
#define LANG_DET_STOP_PAUSES_RATE_CUT " pausas de parada seguidas. Velocidad base de extracción reducida a "
#define LANG_DET_UNIT_LPH_DOT " l/h."
#define LANG_DET_PAUSE_TYPE_BUSY "Detector: tipo de pausa automática ocupado. Control omitido."
#define LANG_DET_PAUSE_TYPE_SET_FAILED "Detector: no se pudo fijar el tipo de pausa."
#define LANG_DET_PAUSE_CRITICAL_TREND "Pausa de extracción: tendencia crítica"
#define LANG_DET_CRITICAL_TREND_PAUSE "Detector: ¡Tendencia crítica! Pausa de extracción. (tendencia: "
#define LANG_DET_NEW_BODY_T "Detector: Fijando nueva T del cuerpo (primer programa del cuerpo, tendencia "
#define LANG_DET_RATE_REDUCTION "Detector: Reducción de velocidad (tendencia "
#define LANG_DET_THRESHOLD ", umbral: "
// FS.ino
#define LANG_FS_MOUNT_FAILED_FORMATTING "No se pudo montar el sistema de archivos, formateando..."
#define LANG_FS_FORMAT_FAILED "No se pudo formatear el sistema de archivos, cargue la interfaz desde Arduino"
#define LANG_FS_ERROR_UPLOAD "¡Error del sistema de archivos! Cargue desde Arduino"
#define LANG_FS_LOW_MEMORY_TOTAL "¡Se acaba la memoria! Total: "
#define LANG_FS_USED ", usado: "
// Samovar.h
#define LANG_SAMH_ASSERT_WPROGRAM_SIZE "WProgram: tamaño de estructura inesperado - revise el orden de campos y la alineación"
#define LANG_SAMH_PWR_MSG_POWER "Potencia"
#define LANG_SAMH_PWR_SIGN_W "W"
#define LANG_SAMH_PWR_MSG_VOLTAGE "Tensión"
#define LANG_SAMH_PWR_SIGN_V "V"
// runtime_helpers.h
#define LANG_RT_WAIT_STEAM "(vapor)"
#define LANG_RT_WAIT_PIPE "(columna)"
#define LANG_RT_WAIT_DETECTOR "(Detector)"
#define LANG_RT_EVENT_RING_REINIT "Registro de eventos reiniciado tras daño"
// valve_buzzer.h
#define LANG_VALVE_OPEN_WATER_SUPPLY "¡Abra el suministro de agua!"
#define LANG_VALVE_COOLING_OPENED "¡Válvula de agua de refrigeración abierta!"
#define LANG_VALVE_CLOSE_WATER_SUPPLY "¡Cierre el suministro de agua!"
#define LANG_VALVE_COOLING_CLOSED "¡Válvula de agua de refrigeración cerrada!"
// selftest.h
#define LANG_SELF_FINISHED "Autotest terminado."
#define LANG_SELF_REJECTED "Autotest rechazado: hay un proceso o cambio de modo activo"
#define LANG_SELF_STARTING "Iniciando autotest."
// sensorinit.h
#define LANG_SENS_UNSUPPORTED_DEFAULT_MODE "modo no admitido del programa por defecto"
#define LANG_SENS_LUA_STATUS_RESET_FAILED "No se pudo restablecer Lua_status: runtime lock ocupado."
#define LANG_SENS_LOG_BUSY_CLOSE_SKIPPED "Archivo de registro ocupado: cierre omitido"
// I2CStepper.h
#define LANG_I2C_LINK_LOST "Pérdida de conexión con el stepper I2C, dirección "
#define LANG_I2C_LOCAL_STOP "Parada local del stepper I2C, dirección "
// SPIFFSEditor.h
#define LANG_EDIT_JSON_ESCAPE_TRUNCATED "spiffsEditorJsonEscape: cadena recortada, falta memoria"
// string_utils.h
#define LANG_STR_JSON_STRING_TRUNCATED "toJsonString: cadena recortada, falta memoria"
