; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
default_envs = Samovar

[env:Samovar]
platform = https://github.com/platformio/platform-espressif32.git#3c076807e1f55b90799b50b946e76a0508e97778
board = esp32doit-devkit-v1
framework = arduino
build_type = release
lib_ignore = 
	LiquidCrystal_I2C
	SoftI2CMaster
	WebServer
lib_extra_dirs = ./libraries
build_src_filter = +<*> -<libraries/> -<Lua_UART/> -<pro_mini_ntc/> -<Stab-avr/> -<core/>
board_build.partitions = partitions/samovar.csv
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
platform_packages =
	tool-esp32partitiontool @ https://github.com/serifpersia/esp32partitiontool/releases/download/v1.4.4/esp32partitiontool-platformio.zip
	platformio/framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b
	platformio/tool-esptoolpy @ 2.40900.250804
	platformio/tool-mkfatfs @ 2.0.1
	platformio/tool-mklittlefs @ 1.203.210628
	platformio/tool-mkspiffs @ 2.230.0
board_build.filesystem = littlefs
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-ffile-prefix-map=${platformio.packages_dir}=.platformio/packages
	-fdebug-prefix-map=${platformio.src_dir}=.
	-Os
	-DCONFIG_OPTIMIZATION_LEVEL_RELEASE=CONFIG_COMPILER_OPTIMIZATION_SIZE
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	--specs=nano.specs
	-Wl,--print-memory-usage
	-Wl,-Map,firmware.map
	-DCONFIG_ESP_BROWNOUT_DET=1
	-DCONFIG_ESP_BROWNOUT_DET_LVL_SEL_3
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
build_src_flags =
	-Wall
	-Wextra

[env:Samovar_s3]
extends = env:Samovar
board = esp32-s3-devkitc-1

[env:Samovar_no_power]
extends = env:Samovar
build_flags =
	${env:Samovar.build_flags}
	-DSAMOVAR_BUILD_NO_POWER

[env:Samovar_rmvk]
extends = env:Samovar
build_flags =
	${env:Samovar.build_flags}
	-DSAMOVAR_BUILD_RMVK

[env:Samovar_sem]
extends = env:Samovar
build_flags =
	${env:Samovar.build_flags}
	-DSAMOVAR_BUILD_SEM

[env:Samovar_lua_mqtt]
extends = env:Samovar
build_flags =
	${env:Samovar.build_flags}
	-DSAMOVAR_BUILD_LUA
	-DSAMOVAR_BUILD_MQTT

[env:Samovar_alarm_button]
extends = env:Samovar
build_flags =
	${env:Samovar.build_flags}
	-DUSE_ALARM_BTN
