#ifdef ESP32
// autogenerated from https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv
// by script <esp8266 arduino core>/tools/TZupdate.sh
// Thu Nov 12 04:07:03 UTC 2020
//
// This database is autogenerated from IANA timezone database
//    https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv
//    (using https://www.iana.org/time-zones)
// and can be updated on demand in this repository
// or by yourself using the above script

#ifndef TZDB_H
#define TZDB_H


#endif // TZDB_H
#endif // ESP32